### ISSUE TITLE
Sessions files never deleted

### ISSUE THREAD

**Issue by karaarda** [adonisjs/core#1150]
Session files are never deleted since adonis version 2 and it results in no spave left in the server. It would be nice if it made some cleanup every once in a while. A crone-job might be set up for now as a workaround.

## Package version
5.0.13

## Node.js and npm version
node v8.16.0 npm v6.4.1

## Sample Code (to reproduce the issue)
Not applicable

**Comment by thetutlage** [comment]
Yeah, I believe, having a command or some other way to cleanup the old files is desired. Will work on it

**Comment by karaarda** [comment]
There are also files created under /tmp/ however I am not sure if they are created by Adonis or any other tool. That files also take too much space. I will further investigate that situation also. Thanks.
