### ISSUE TITLE
Is there any hook before shutdown/reload?

### ISSUE THREAD

**Issue by Patrick-Shih** [adonisjs/core#1154]
Hi,

I would like to add some clean-up code when service reload (run with --dev) or shutdown (with Crtl+C or something like kill).  Is there any hook like `beforeShutdown` existing in the framework to gracefully shutdown the server?

If there is no such hook, I can use something like `process.on('SIGTERM', clean_up_function);` but I do not sure what I supposed to call to gracefully stop everything used by adonis

**Comment by thetutlage** [comment]
In v5, you can use providers `shutdown` method to execute actions when processing is shutting down gracefully.

**Comment by miagg** [comment]
Is there any way to gracefully shutdown from an ace command that does not boot the app? I tried using `proccess.on('SIGINT', myCallback)` but on production (using pm2) this handler is never executed because the default adonis callback kicks in and shuts down the app.
