### ISSUE TITLE
What could be the reason of 'invalid media type' exception?

### ISSUE THREAD

**Issue by arvindkumarbadwal** [adonisjs/core#1165]
While uploading an image from an android device, then the application crashed and following error generate.

| /app/node_modules/media-typer/index.js:249
|     throw new TypeError('invalid media type')
|     ^
| 
| TypeError: invalid media type
|     at splitType (/app/node_modules/media-typer/index.js:249:11)
|     at Object.parse (/app/node_modules/media-typer/index.js:160:13)
|     at new File (/app/node_modules/@adonisjs/bodyparser/src/Multipart/File.js:147:36)
|     at Multipart.onPart (/app/node_modules/@adonisjs/bodyparser/src/Multipart/index.js:129:26)
|     at Form.<anonymous> (/app/node_modules/@adonisjs/bodyparser/src/Multipart/index.js:171:14)
|     at Form.emit (events.js:210:5)
|     at Object.cb (/app/node_modules/multiparty/index.js:642:10)
|     at flushEmitQueue (/app/node_modules/multiparty/index.js:626:10)
|     at /app/node_modules/multiparty/index.js:602:5
|     at handlePart (/app/node_modules/multiparty/index.js:641:3)
|     at Form.onParseHeadersEnd (/app/node_modules/multiparty/index.js:527:5)
|     at Form._write (/app/node_modules/multiparty/index.js:319:24)
|     at doWrite (_stream_writable.js:431:12)
|     at writeOrBuffer (_stream_writable.js:415:5)
|     at Form.Writable.write (_stream_writable.js:305:11)
|     at IncomingMessage.ondata (_stream_readable.js:726:22)
| Application crashed, make sure to kill all related running process, fix the issue and re-run the app
^CERROR: Aborting.

**Comment by RomainLanz** [comment]
Hey @arvindkumarbadwal! 👋 

It's hard to help you with the amount of information you gave us.
Since it's probably not an issue with the framework directly, I'd recommend you to post on the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6).

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
