### ISSUE TITLE
What the best way to block user JWT based on is_blocked User field?

### ISSUE THREAD

**Issue by vitorcremonez** [adonisjs/core#1191]
It's possible to instance new middleware for it. But I'll have to instance 2 middleware always together.
I need to do all in one middleware.
Not like this:
Route.get('/Posts', 'PostsController.index').middleware(['auth', 'auth_blocker'])
Like this:
Route.get('/Posts', 'PostsController.index').middleware(['auth'])

There is a good pratice in actual version for it?

**Comment by thetutlage** [comment]
I don't see any reason for not using two middleware. The entire point of middleware is to have chain of functions vs writing all code in one file or method.
