### ISSUE TITLE
Override public path

### ISSUE THREAD

**Issue by sorxrob** [adonisjs/core#1193]
Is there a way to override the public path? Or use relative paths something like this in express

`app.use('/somefolder', express.static('public'));`

Any help would be much appreciated.

**Comment by jualahmed** [comment]
look at the [ `'Adonis/Middleware/Static',` ](https://adonisjs.com/docs/4.1/middleware) Middleware. the Middleware handle static directory. unfortunately public path are not dynamic. your can change public path but you need to edit core code. [look at the image ](https://prnt.sc/qwbtwt)

**Comment by RomainLanz** [comment]
Hey @sorxrob! 👋 

If you want to use another public path, you will need to create your own middleware.
As said in the Discord, we do not recommend doing that and for production you should use a static server to manager your asset and not this middleware.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
