### ISSUE TITLE
Change S3 File Storage config dynamically

### ISSUE THREAD

**Issue by ansoncsh** [adonisjs/core#1196]
Hi,

Is there a way change the S3 config (including access key, secret key and bucket) on request?
We would like to use different AWS access keys which are provided by users.

**Comment by RomainLanz** [comment]
Hey @ansoncsh! 👋 

It's possible with the next version of Flydrive, but not the current one.
You can freely directly use this new release without using the provider if you want to have a try.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
