### ISSUE TITLE
Add list of recommended VS Code extensions

### ISSUE THREAD

**Issue by guledali** [adonisjs/core#1197]
A **list** of extensions,

adonis-js-goto-controller
adonis-js-goto-view
adonisjs-vscode

and maybe some linting as well? What do you think @thetutlage

**Comment by RomainLanz** [comment]
Hey @guledali! 👋 

An official extension for VSCode should be released in a short amount of time.
I don't believe it will be usefull to add all of those others extensions.

Let see what @thetutlage think about it.

**Comment by guledali** [comment]
@RomainLanz It would be nice as soon as you open a newly generated `adonis.js` project in your vscode you get this
 
<img width="659" alt="Screenshot 2020-02-08 at 13 48 33" src="https://user-images.githubusercontent.com/20647282/74085559-3f7f6300-4a7a-11ea-9014-905182c0bf5d.png">

**Comment by guledali** [comment]
When is new VSCode extension going to be available?
