### ISSUE TITLE
Route validation not working per instructions in the docs

### ISSUE THREAD

**Issue by MrToxy** [adonisjs/core#1202]
I've followed all the instructions in https://adonisjs.com/docs/4.1/validator#_validator_methods and every time I make a request to the route using the validator this is all I get back as a response:

"AdonisJs simplicity will make you feel confident about your cod
Don't know where to start? Read the documentation."

This is my code:

**/start/routes.js:**

`
Route.group(function() {
  Route.post('/', 'ContactController.newContact').validator('ContactForm')
}).prefix('api/contact')
`

**/app/Validators/ContactForm**:

```
'use strict'

class ContactForm {
  get rules() {
    return {
      email: 'required|email',
      type: 'string',
      name: 'required|string',
      message: 'required|string'
    }
  }
  get validateAll() {
    return true
  }
}

module.exports = ContactForm
```

and in **/app/start**:

```
const providers = [
   ...
  '@adonisjs/validator/providers/ValidatorProvider'
]
```

I've tested the manual validation in the controller and it works, but this way all I can get is that message.

[Request Preview](https://pasteboard.co/IU36kJq.png)

**Comment by thetutlage** [comment]
This happens because validator is trying to redirect the request from form validation failure. The simplest way to fix this is to set the `Accept` header to `application/json` when making the request

**Comment by MrToxy** [comment]
alright that seems to have fixed it
