### ISSUE TITLE
 Problems in the order of migrations

### ISSUE THREAD

**Issue by farnetani** [adonisjs/core#1205]
## Package version
"@adonisjs/framework": "^5.0.9"

## Node.js and npm version
v12.14.1

## Sample Code (to reproduce the issue)

The same project with the same version of the commit in one place is presenting me the order of migrations by the command: `adonis migration:status` in one way and in the same project in another place with the same version of git showing the different order, both are the same project with the same .env file.

## BONUS (a sample repo to reproduce the issue)

Incorrect Order Below:

![image](https://user-images.githubusercontent.com/564503/74551506-0dff0f80-4f32-11ea-8fe7-f87e08f27313.png)

Correct Order Below:

![image](https://user-images.githubusercontent.com/564503/74551596-3be45400-4f32-11ea-8449-20fa609f269e.png)

The images highlighted the problem that is in the migration: ecommerce_carrinho_schema, I simply edited the file on a machine from one of our developers and after I gave git pull started to present this problem keeping the migration edited to be executed last.

I wanted to understand why when adonisjs (knex-migrations) is experiencing this behavior?

I know that it is not a good practice to edit a migration file that has already been created, but the truth is that in a project still under development this is quite possible and much easier than creating new migrations of changes.

**Comment by McSneaky** [comment]
Quite late to the party, but as far as I know data is read off directly from database without any ordering, which means that DB will return the results in the order it finds them.
Adding and dropping random indexes and / or forcing DB to rebuild whole table structure should shuffle it around

**Comment by thetutlage** [comment]
Closing since not actionable
