### ISSUE TITLE
Validation in adonis

### ISSUE THREAD

**Issue by alirezazeynali75** [adonisjs/core#1209]
Hi!!!
can anybody help me??
I want to use adonis validation but I don't know which one is better 
Implement like django and separate rules or implement it at controller???

**Comment by Kaperskyguru** [comment]
I use @adonisjs/validator on all my project, i think it should be great for you too

**Comment by RomainLanz** [comment]
Hey! 👋 

Your issue do not follow our guidelines.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
**2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.**

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
