### ISSUE TITLE
.edge support on phpstorm/intellij idea

### ISSUE THREAD

**Issue by GENL** [adonisjs/core#1210]
Hi! I'm new to adonisJs. I know that this is not an issue directly related to this repo. It would be very useful to develop a phpstorm .edge file support.

**Comment by thetutlage** [comment]
Mind helping us out? I have never used both the editor, so I have no idea how to create a syntax extension for them. But to help, if someone wants to lead it

**Comment by GENL** [comment]
I'm ok try. I have never made an intellij plugin before but I will do my best. I inform you of my progress through this topic or on the discord.

**Comment by mateus4k** [comment]
@GENL Excellent idea! It would be quite useful.

**Comment by thetutlage** [comment]
Closing, since it is not something we can act upon right now. Can be opened as a discussion thread instead

**Comment by justrustyspoons** [comment]
Hope this helps https://plugins.jetbrains.com/plugin/31167-edgejs
