### ISSUE TITLE
Adonis 5 GraphQL support status

### ISSUE THREAD

**Issue by e200** [adonisjs/core#1213]
Is Adonis 5 coming with builtin GraphQL support? if yes, what's the current support status?

**Comment by thetutlage** [comment]
I have no plans for writing a package for GraphQL. Here's the roadmap, that lists all the features to be coming in next few months. https://trello.com/b/3klaHbfP

Isn't using existing tooling of GraphQL a better option? Asking, coz I am not an active user of GraphQL.

**Comment by e200** [comment]
> I have no plans for writing a package for GraphQL. Here's the roadmap, that lists all the features to be coming in next few months. https://trello.com/b/3klaHbfP
> 
> Isn't using existing tooling of GraphQL a better option? Asking, coz I am not an active user of GraphQL.

Nope, because existing ORMs aren't as good as Lucid. Maybe if Lucid wasn't strictly coupled to the Adonis Framework...

**Comment by thetutlage** [comment]
These seems to be two different things. Anyways I'll close this issue, since there is nothing to act on.
