### ISSUE TITLE
AdonisJs version question

### ISSUE THREAD

**Issue by Nothing-Works** [adonisjs/core#1214]
hi I am very new to AdonisJs, I am very confused by the version. I know V5 is coming, on the docs website the latest version is 4.1. However, on npm it's 2.10.4. can someone explain this, please.

**Comment by z808z** [comment]
Hello!
Version 5 at https://preview.adonisjs.com/

**Comment by RomainLanz** [comment]
Hey @Nothing-Works! 👋 

Please, read this https://preview.adonisjs.com/release-process.
