### ISSUE TITLE
Add ability to query resources from URL params

### ISSUE THREAD

**Issue by FrenchMajesty** [adonisjs/core#1222]
## Why this feature is required (specific use-cases will be appreciated)?

I have an application that is API driven. Say that I have users with multiple relationships (users can have phones, have a log history, messages, conversations, cars, purchases)

In some pages I want to fetch my users and their devices. On another page I want to get the users and the log history. The number of "I need data A, Y, and K about resource B" grows and becomes hard to manage.
Of course creating an API endpoint for each of these is awful. Instead I would like to be able to intelligently query my `User` model through the URI to get the data exactly as I want it.

## Have you tried any other work arounds?
I tried writing code to check the `request.get()` object and did things like this:

```js
const { devices } = request.get();
if(devices === 1) userQuery.with('devices');
```

You can get smart use an array

```js
const acceptableRelations = ['devices', 'logs', 'cars', 'purchases'];
const getParams = request.get();
acceptableRelations.forEach((relation) => {
  if(getParams[relation] === 1) userQuery.with(relation);
});
```

But this doesn't scale because what if I want to query 12 other Lucid models in the same way? I have to write this same ugly mess? For API driven application this is a real problem.

In Laravel there is [a great package](https://github.com/spatie/laravel-query-builder) that solves this problem elegantly.

This is my attempt at reproducing their API in JavaScript:
```js
const query = new QueryBuilder(request.get());
return query.for(User.query())
  .allowedFilters(['email', 'number'])
  .allowedIncludes(['conversations', 'devices', 'messages', 'purchases'])
  .fetch();
```

And in my frontend application I can now get the granular control I need `/api/users?include=devices,messages`.
## Are you willing to work on it with little guidance?

I have [implemented something](https://gist.github.com/FrenchMajesty/ca9348d62accd7f7d29219ddb1675a07) close to it and while it's good enough for me I believe it could help other developers by being included in the Adonis stack.

**Comment by thetutlage** [comment]
Please create a proper RFC for something, since it is not an issue with the existing codebase and more of a feature request.

Also, suggest you to look into the specs like https://jsonapi.org/, since creating a custom spec within the framework isn't ideal
