### ISSUE TITLE
fatal TypeError: Cannot read property 'AdonisRcFile' of undefined

### ISSUE THREAD

**Issue by jaysson** [adonisjs/core#1226]
Not able to initiate the projec.

## Package version
preview

## Node.js and npm version
NodeJS: `13.2.0`
npm: `6.13.4`

## Sample Code (to reproduce the issue)
`yarn create adonis-ts-app myapp` or `npx create-adonis-ts-app web`

**Comment by thetutlage** [comment]
Want to try it now? Happened coz, one of the packages meant to be published for next release was accidentally published

**Comment by jaysson** [comment]
Works. Thank you for the quick reply!
