### ISSUE TITLE
Make posible load ts files for config

### ISSUE THREAD

**Issue by alberto-leon-crespo** [adonisjs/core#1227]
## Prerequisites

When u try to use adonis with typescript is not possible. Adonis try to load config files in ".js" format but dont load config files with ".ts" extensión. Also is necesary to modify code to control default modules index and if exists return content of key. This change need a little modifications of ignitor to load "start/app" instead of using "start/app.js"

## Why this feature is required (specific use-cases will be appreciated)?
I try to use adonis with full typescript base. I can provide code to solve this feature.

## Have you tried any other work arounds?
No i cant make this work with other options.

## Are you willing to work on it with little guidance?
Yes i code solution some days ago.

**Comment by RomainLanz** [comment]
Hey @alberto-leon-crespo! 👋 

The new version of Adonis is fully compatible with TS. We will not change how V4 work.
