### ISSUE TITLE
Multiple route files with group

### ISSUE THREAD

**Issue by sangemi** [adonisjs/core#1229]
I want to run 2 website under 1 adonis.

1. The below code is now working. Is this impossible?

```
    Route.group(() =>  {
    	require ("./routes-common")
    	require ("./routes-ehon")
    }).domain('ehon.booboolife.com')

    Route.group(() =>  {
    	require ("./routes-common")
    	require ("./routes-main")
    }).domain('main.booboolife.com')
```

2. I want to use .domain method with multiple domain

```
    Route.group(() =>  {
    	require ("./routes-common")
    	require ("./routes-main")
    }).domain(['main.booboolife.com', 'booboolife.com'])
```

**Comment by RomainLanz** [comment]
Hey @sangemi! 👋 

Most of this should be managed by our Web Server that act as reverse proxies (like Nginx, Apache, or whatever you use).

**Comment by sangemi** [comment]
I already set all request redirect to my AdonisJS app.

1. Really I want to do is,
I want to write common code at once when running 2 websites.
The layout, plugins, login logic are same across all three sites. 
Different part is only the pages folder.

related question : https://stackoverflow.com/questions/61423734/i-want-to-run-two-web-site-in-one-adonisjs-nuxt-js

2. I think Using .domain method with multiple domain is needed. because

    Route.group(() =>  {
    	require ("./routes-common")
    	require ("./routes-main")
    }).domain(['main.booboolife.com', 'www.booboolife.com'])

    Route.group(() =>  {
    	require ("./routes-common")
    	require ("./routes-sub1")
    }).domain('sub1.booboolife.com')

If not allowed, I have to write

    Route.group(() =>  {
    	require ("./routes-common")
    	require ("./routes-main")
    }).domain('main.booboolife.com')

    Route.group(() =>  {
    	require ("./routes-common")
    	require ("./routes-main")
    }).domain('www.booboolife.com')       >>>>> duplicated !

    Route.group(() =>  {
    	require ("./routes-common")
    	require ("./routes-sub1")
    }).domain('sub1.booboolife.com')

Anyway, this type of code is not allowed as you said, so you don't have to think about it.

Thank you for your reply.

**Comment by sangemi** [comment]
I decided to create another Adonis app. Anyone reading this article shouldn't try to combine two sites like me. There are many problems except the routing. :-)
