### ISSUE TITLE
DeprecationWarning: REPLServer.rli is deprecated

### ISSUE THREAD

**Issue by gusilveiramp** [adonisjs/core#1231]
## Package version
4.1.0

## Node.js and npm version
12.16.3

## Sample Code (to reproduce the issue)
❯ adonis repl
> (node:93874) [DEP0124] DeprecationWarning: REPLServer.rli is deprecated

**Comment by thetutlage** [comment]
Sorry, I don't think, I have bandwidth to port fixes on v4 right now. The new repl will not be using depreciated code
