### ISSUE TITLE
`adonis serve --dev` does not watch & nor does it live reload

### ISSUE THREAD

**Issue by WhereJuly** [adonisjs/core#1234]
## Package version
Adonis v 4.1.0

## Node.js and npm version
Node: v12.16.1
npm: 6.14.4

## OS
Windows 8.1

## The Issue Description

1. I start development server with `adonis server --dev`;
2. It starts the server on 127.0.0.1:3333;
3. It detects JS files changes;
4. It does not detect `project/resources/views/welcome.edge changes`;
5. It does not live reload the page on 127.0.0.1:3333;

Is it expected behaviour?

**Comment by WhereJuly** [comment]
# Additional Experiment

## Package Version
Adonis 5
- fresh installation with `npx create-adonis-ts-app <project-name>`;
- run with `node ace serve --watch`;

## Node, npm, OS
Same as in the above

## Behavior

Same as Adonis 4.1.0 above except Adonis 5 see the changes in `project/resources/views/welcome.edge`

**Comment by McSneaky** [comment]
`.edge` files are re-rendered at every page refresh :wink: Unless you have `CACHE_VIEWS` variable set to `true`. There's no need to reload server because of .edge changes

Since Adonis is backend framework it doesn't do page refresh in browser, which is on client side only

**Comment by WhereJuly** [comment]
@McSneaky I am not talking about server reload. I am talking about live page reload within `--dev` process. This is strange to run a development server, have JS re-compiled on files change but not to reload a browser tab.

**Comment by RomainLanz** [comment]
This is completely intended.
We are a backend framework, it's a non-sense to have hot reload.

**Comment by WhereJuly** [comment]
@RomainLanz even if this is intented this is a drawback. Which makes use of the framework harder making its target audience smaller.

Adonis is not a backend framework. It is a full-stack framework with 50/50 front / back. It is clearly seen on its [Installation](https://adonisjs.com/docs/4.1/installation) page: the `adonis new yardstick` command installs [Adonis full-stack blueprint](https://github.com/adonisjs/adonis-fullstack-app) project structure. Thus by this fact Adoins is promoted by the authors as full-stack farmework.

With all this in mind my question is: do you really not to care for at least a receipe for your target audience on how to make live reload working for the full-stack framework?

I am just interested in the reasoning behind.

**Comment by WhereJuly** [comment]
For those who want to make a live reload for their Adonis full stack project keep reading.

The general reload system work process outline is as follows:
1. You run your Adonis project server with [`nodemon` ](https://www.npmjs.com/package/nodemon) instead ot `adonis serve --dev`, ensure the server is running all the time you are developing;
2. You use [`gulp`](https://gulpjs.com/) and [`browser-sync`](https://www.browsersync.io/) to run another continuous `watch` task to watch in `your-adonis-project-scr-folder/**/*.*` all the files.
3. The configuration of the Browsersync in the step 2 should [proxy](https://www.browsersync.io/docs/gulp#gulp-install) the Adonis server `127.0.0.1:3333`.

I will put a link to a snippet here for convenience soon,

**Comment by danielh-official** [comment]
For **Live Reload** in Adonisjs, you can install BrowserSync globally following the [instructions](https://browsersync.io/#install) on its site.

Afterward, run `browser-sync start --proxy "127.0.0.1:3333" --files "resources/**/*"` inside your app directory AFTER and WHILE running `node ace serve --watch`:

The default URL for the dev server is `127.0.0.1:3333`, though if you access it from a different one, replace it in the above command.

`"resources/**/*"` means all the files in your resources directory, located in the root of your project.

BrowserSync will give you a URL, usually `localhost:3000` and watch fro any changes in your resources directory. If there are any, `localhost:3000` will refresh automatically.

**Comment by xarhang** [comment]
> This is completely intended. We are a backend framework, it's a non-sense to have hot reload.

oh no if like you said, people will leave your framework soon...
