### ISSUE TITLE
Migration Error [ERR_ASSERTION] while migration with postgres

### ISSUE THREAD

**Issue by muflihfq** [adonisjs/core#1236]
## Package version
4.1.0

## Node.js and npm version
Node js : v12.16.1
npm : 6.13.4
postgres : 11.1

## Sample Code (to reproduce the issue)
`adonis migration:run`

I only add one schema beside pre-config migration (user and token)

here is the full log:

> assert.js:140
>   throw err;
>   ^
> 
> AssertionError [ERR_ASSERTION]: unknown message code: 4a
>     at Parser.handlePacket (D:\Adonis\bc-api\node_modules\pg-protocol\dist\parser.js:101:34)
>     at Parser.parse (D:\Adonis\bc-api\node_modules\pg-protocol\dist\parser.js:41:38)
>     at Socket.<anonymous> (D:\Adonis\bc-api\node_modules\pg-protocol\dist\index.js:8:42)
>     at Socket.emit (events.js:311:20)
>     at readableAddChunk (_stream_readable.js:275:11)
>     at Socket.Readable.push (_stream_readable.js:209:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
>   generatedMessage: false,
>   code: 'ERR_ASSERTION',
>   actual: undefined,
>   expected: undefined,
>   operator: 'fail'
> }

I tried to use mysql and it's works fine.

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by TimMurnaghan** [comment]
This isn't an adonis issue - so it's rightly closed - but it's the top google hit for this error message - so it's worth mentioning that it's caused by a postgres connection problem -  just badly reported by the pg driver.

In my case it was caused by an ubuntu upgrade starting the server on port 5433 instead of 5432 - but there could be other reasons. Try connecting with a command line psql client and you should be able to figure out a reason.

**Comment by thetutlage** [comment]
Thanks for sharing 🙂
