### ISSUE TITLE
4.1 user table migration: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by Jakobud** [adonisjs/core#1240]
## Package version
`4.1.0`

## Node.js and npm version
`10.20.1` and `6.14.4`

## Sample Code (to reproduce the issue)
`adonis migration:run`

When I install Adonis 4.1.0 and run the default migrations, I get the following error regarding the user table migration:

```
code: 'ER_TOO_LONG_KEY',
  errno: 1071,
  sqlMessage: 'Specified key was too long; max key length is 767 bytes',
  sqlState: '42000',
  index: 0,
  sql:
   'alter table `users` add unique `users_username_unique`(`username`)' }
```

I'm using MariaDB. Version: `mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

The table is InnoDB and the collation is `utf8mb4_general_ci`.

Pretty basic database installation. Nothing special there. This is all on a fresh Ubuntu 18.04.4 virtual machine (vagrant/virtualbox). Not sure why this error is occurring.

**Comment by McSneaky** [comment]
`mb4` uses more bytes per character than `utf8`. Which reduces max length of field down to 191 chars ( _VARCHAR(191)_ )

Easiest solution is to limit all strings to 191 chars, turn on `innodb_large_prefix` or even better would be to update DB engine to something newer
`innodb_large_prefix` is enabled by default for DBs newer than MariaDB 10.2.2

**Comment by Jakobud** [comment]
I figured it out. It was just because I was using an old version of MariaDB. Upgraded to the latest stable and that limitation is no longer there. Thanks,
