### ISSUE TITLE
TypeError: Cannot read property 'appNamespace' of undefined

### ISSUE THREAD

**Issue by bridgetsarah** [adonisjs/core#1241]
Hello,  I seem to be having an issue with Adonis, the last thing I did earlier was updated NPM due to NPM showing audit fixes since then I've had numerous issues of all the modules needing to be reinstalled pretty much. And... I thought I had sorted it until this issue raised.  I have tried looking for any kind of information but I cannot find the answer.

I have done nothing to this server file, and I have no idea how to fix it. Can someone please assist? I can't start with nodemon or ace.

Npm keep advises me to install npm WARN @adonisjs/lucid@8.1.1 requires a peer of @adonisjs/core@>=5.0.0-preview but none is installed. You must install peer dependencies yourself.

I have tried even forcing to install this and it will not work.

CLenovoTP220x portal # nodemon server.js
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`

**TypeError: Cannot read property 'appNamespace' of undefined**

at /home/bridgetsarah/github/adonisjs/portal-ajs-tw/portal/server.js(anonymous):24
19  
20  const { Ignitor } = require('@adonisjs/ignitor')
21  
22  new Ignitor(require('@adonisjs/fold'))
23    .appRoot(__dirname)
24    .fireHttpServer()
27    .catch(console.error)
28  

1 Ignitor._setupResolver
  /home/bridgetsarah/github/adonisjs/portal-ajs-tw/portal/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:173

2 anonymous
  /home/bridgetsarah/github/adonisjs/portal-ajs-tw/portal/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:211

3 Ignitor._registerAutoloadedDirectories
  /home/bridgetsarah/github/adonisjs/portal-ajs-tw/portal/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:208

4 Ignitor.fire
  /home/bridgetsarah/github/adonisjs/portal-ajs-tw/portal/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:744

5 Ignitor.fireHttpServer
  /home/bridgetsarah/github/adonisjs/portal-ajs-tw/portal/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:810

[nodemon] app crashed - waiting for file changes before starting...
`

## Prerequisites

Linux Mint (Sarah)

## Package version
Adonis Version (Installed directly from your website via npm) 4.1.0

## Node.js and npm version

NPM 6.14.4
Node v12.17.0
Nodemon 2.0.4

## Sample Code (to reproduce the issue)
nodemon server.js

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
