### ISSUE TITLE
Change inlineSvg tag to use a config'ed path instead of public path

### ISSUE THREAD

**Issue by Jakobud** [adonisjs/core#1243]
Currently the inlineSvg tag looks for a svg files relative to the public directory. Instead of hard-coding this to use the public directory, it would be a huge improvement to make this path a configurable value, like `Config.get('app.views.svgPath')`. Give it a default value of the public path so that there are no breaking changes, yet it makes the feature more flexible.

## Why this feature is required (specific use-cases will be appreciated)?
Two primary reasons that I have come across:

1. Keeping SVGs out of the public directory that are not mean't to be publicly accessible to anyone. Currently if an SVG has to be somewhere in the public directory then it's URL is accessible to everyone. Now in most cases, `inlineSvg` is used to render a little svg icon or something. No big deal there. But I have a situation where I have a website with some users that are logged in with special privileges and other users that are not logged in and do not have special privileges. It's important for certain SVG files (that are proprietary art files of users) to only be served up and available to my logged in users. But since the `inlineSvg` tag requires SVGs to be in the public directory then those SVGs are publicly available. They are available for anyone to download with the right URL and that just cannot work for both privacy and copyright reasons. Being able to change the path to something not public would be desirable for this reason.

2. Another use case is simply being able to specify shorter svg paths. If you have your SVGs located in `/public/images/svgs/fontawesome/solid/*.svg` then when you have to do `inlineSvg("images/svg/fontawesome/solid/facebook")`. Would be amazing if you could simply change the config path globally to `"public/images/svg/fontawesome/solid"` and then just type in svgs like `inlineSvg("facebook")`. It would save time but more importantly makes code more readable and maintainable.

## Have you tried any other work arounds?
The workarounds I have tried: 

hard coding the SVGs into the templates, which doesn't really work for a lot of my SVGs that are dynamically determined on page load. 

Loading the SVG code in the page via AJAX on page load. This works. Not ideal.

I have not tried it but you could also create a different custom tag to inline svgs with a custom path. I cannot find the documentation on how to do this exactly.

Another obvious workaround is to just specify a path relative to the public directory that is not in the public directory. For example `inlineSvg("../resources/images/svgs/fontawesome/solid/facebook")`. But again, see above for use case #2. Would sure be nice not to have to specify these stupidly long paths every time you want to put in a svg.

## Are you willing to work on it with little guidance?
Absolutely, I would think this would be pretty low effort. Just adding the config value and then changing the tag to use this config value. I have been looking through the v5 code but cannot make sense of some of it. Like I see the public path being fetched from `Helper.js` but its not clear where this `Helper.js` is at. If its in some other module or what.

**Comment by WhereJuly** [comment]
> I have not tried it but you could also create a different custom tag to inline svgs with a custom path. I cannot find the documentation on how to do this exactly.

@Jakobud There is no really documentation for the custom tag creation. The [main Adonis docs for custom tags](https://adonisjs.com/docs/4.1/views#_tags_2) refers to the [Edge custom tags section](https://edge.adonisjs.com/docs/tags#_writing_your_own_tags) which in turn refers to the missing video (@thetutlage if possible could you please check if this can be fixed).

Nevertheless you could explore the source code for the custom [inlineSvg tag](https://adonisjs.com/docs/4.1/views#_inlinesvg) which is available in the `your-project-root/node_modules/%40adonisjs/framework/src/View/Tags/InlineSvg.js`. Especially look up the following method where the path you need to change is defined:
``` javascript
    _getAbsPath (filePath) {
      return path.isAbsolute(filePath) ? filePath : path.join(this._publicPath, filePath)
    }
```

You could make your own version of it, say `inlineSvgFreePath` for which [the docs section](https://adonisjs.com/docs/4.1/views#_tags_2) I believe would be enough.

**Comment by Jakobud** [comment]
Looks like a lot of steps to essentially duplicate the `inlineSvg` tag. Would it be more worth my time to just update the core code with the ability to specify a configurable path? Surely I'm not the first person who has desired this feature.

**Comment by WhereJuly** [comment]
> Would it be more worth my time to just update the core code with the ability to specify a configurable path? 

No. This would come seriously inconvenient as you move your application to stage and production environment. 

The code in the `node_modules` would be overwrtten every time you reinstall your NPM dependencies under new environment. 

As well your updates would be lost as you do not commit `node_modules` to version control system (and you should not).

**Comment by Jakobud** [comment]
No no no. I mean make a pull request to the AdonisJS v5 core as a new feature. So that anyone could use this feature in the future if/when it was merged into the v5 framework.

**Comment by WhereJuly** [comment]
@Jakobud I see.
