### ISSUE TITLE
What to do with Testing in v5

### ISSUE THREAD

**Issue by WhereJuly** [adonisjs/core#1244]
## Prerequisites

I see you still hesitant to what to do with testing as per this: https://trello.com/c/LAmdkijN

## Proposal

1. Unit testing: Mocha as a sole unit / integratinon (including HTTP with Chai-http) tests runner and a test environment;
- Just need to make a framework / framework + server bootstrap as we discussed [here](https://github.com/adonisjs/core/issues/1242#issue-636824008). I have some 90% working example.

2. Browser testing: quit any Jest / Mocha attempts to test the browser thing. Replace it with [cypress.io](https://www.cypress.io/). They have an open source thing. I believe this would completely release the awkwardness of testing browser things with Jest / Mocha.

## Why Mocha

- Complies with most of Japa requirements:
  + Conscise async/await support, non-bloated with callbacks;
  + Tests retry, timeouts, groups;
  + However some quite feasible Japa things like [regression testing support](https://github.com/thetutlage/japa#regression-tests) and [assertions planning](https://github.com/thetutlage/japa#assertion-planning) are missing in Mocha. It is still to investigate if they can be implemented there via PR.
- Rather small yet very configurable: use different assertions libraries, reporters, make traditional browser testing out-of-the-box - all of these added within seconds at a developer will;
- ES6 `import` support;
- Hook some custom functionality before (or after) every test (test file) across all test files - [Root Hook Plugin](https://mochajs.org/#root-hook-plugins) - can be used for "magical" bootstrapping the application or any other custom Adonis things under tests.
- Supports TypeScript (if it is at all needed for tests to use TypeScript) via [Babel](https://github.com/mochajs/mocha-examples/tree/master/packages/babel#babel-application) (`ts-node` is supported too but the Adonis Trello card says against it);
- vs. Jest
  + ~280 issues vs ~1000 for Jest;
  + Jest has very weak assertions library. In Mocha you can use its own assertions as well as really rich [Chai](https://www.chaijs.com/api/) assertions library with either TDD or BDD styles.
  + Jest console reporting leaves very much to be desired: non-configurable, non-informative, very scarce information. Whereas in Mocha you can use one of 13 pre-configured [console reporters](https://mochajs.org/#reporters) with different levels of details (minimal to detailed), colored output, progress bars etc. as well as create your [own reporter](https://mochajs.org/#third-party-reporters).
  + Consoler error reporting in Jest is rather bloated. Mocha here is somewhat better (say 50% less bloat but still Japa wins here).
  + In general Jest looks like a half-baked testing utility made by Facebook team especially for its (edge) cases with React. Whereas Mocha is a versatile solid universal test runner.
  + Packages size wise Jest is [33MB](https://packagephobia.com/result?p=jest%4026.1.0) whereas Mocha is [7MB](https://packagephobia.com/result?p=mocha%408.0.1)

## Are you willing to work on it with little guidance?

Yes, if I could be of help I am ready to discuss the implementation details and a timeline.

**Comment by thetutlage** [comment]
Is there other specific reason for Mocha, coz the one mentioned are something already covered in Japa. Maintained by me, so I can guarantee future improvements.

**Comment by WhereJuly** [comment]
@thetutlage Proposing Mocha I had in mind this comment of yours from Adonis 5 Trello board [testing card](https://trello.com/c/LAmdkijN)

> The testing package of AdonisJS has not been migrated yet. I am currently looking into alternatives vs rolling our own test runner.

I got it as if you wanted to replace Japa with some third-party test runner.

If this is no more the case I personally have nothing against Japa except its implementation for Adonis (vow?) does not allow for [test groups](https://github.com/thetutlage/japa#test-groups).

Another more general reason could be the better adoption of the framework that provides the industry standard test runner = lower learning curve. Still you could keep Japa begind the scenes (fixiing the test grouping in vow) and provide first-party supported adapter to Mocha (I believe should be very easy in code and some small work in docs).

BTW did you see cypress.io? To my taste just outstanding value for E2E testing - simple but so powerful.

**Comment by thetutlage** [comment]
I believe, the learning curve of test runners is anyways not a huge issue in general, unless a test runner is doing something completely different. So I am less interested in trying out other frameworks, until they provide some real value.

Regarding cypress.io. Yes, it is great and no doubt about it. But few questions around it

Isn't cypress all about testing your apps from outside-in? It means, running your web server as normal and then using cypress like a real user is using it?

If so, then what extra AdonisJS has to do to support it?

**Comment by WhereJuly** [comment]
> I believe, the learning curve of test runners is anyways not a huge issue in general, unless a test runner is doing something completely different. So I am less interested in trying out other frameworks, until they provide some real value.

I believe so as well. 

But then why you had looked for alternatives to Japa? Just curious.

> Isn't cypress all about testing your apps from outside-in? It means, running your web server as normal and then using cypress like a real user is using it?

True. This is the nature of E2E tests. And the instrument that is more efficient alternative to the [traditional browser integration testing](https://adonisjs.com/docs/4.1/browser-tests).

> If so, then what extra AdonisJS has to do to support it?

A guide I believe would be good.

Along with promoting [traditional browser tests](https://adonisjs.com/docs/4.1/browser-tests) add a guide for Cypress in the context of Adonis app.

**Comment by krunaldodiya** [comment]
How can I authenticate with some user created by UserFactory ? previously i was able to do client.loginVia(user) but now, supertest has not support for that, we need to pass token for that, i am not sure how can i create token in TDD using auth.generate(user) ???

**Comment by krunaldodiya** [comment]
```

test.group('UserDashboard', async () => {
  test('only_authenticated_user_can_access', async () => {
    const token = await AuthManager.getAuthForRequest(req).attempt(user)
    await supertest(BASE_URL).set({token: `Bearer ${token}`}).post('/user/dashboard').expect(401)
  })
}
```
