### ISSUE TITLE
PUT / PATCH / DELETE Method spoofing results in "Route not found" Exception

### ISSUE THREAD

**Issue by tallredmanxyz** [adonisjs/core#1245]
```
 Exception
E_ROUTE_NOT_FOUND: Cannot POST:/posts/1 
```

Ensured that I followed advised way of method spoofing from this issue: https://github.com/adonisjs/core/issues/1116#issuecomment-514269382 

Tried both with and without CSRF protection enabled. 

## Package version

```
"dependencies": {
    "@adonisjs/ace": "^6.9.3",
    "@adonisjs/auth": "^4.2.3",
    "@adonisjs/core": "^5.0.0-preview-rc-1.9",
    "@adonisjs/fold": "^6.3.5",
    "@adonisjs/lucid": "^8.2.2",
    "@adonisjs/session": "^3.0.4",
    "@adonisjs/shield": "^3.0.4",
    "@adonisjs/view": "^2.0.7",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
```

## Node.js and npm version
node v12.18.1
npm v6.14.5

## Sample Code (to reproduce the issue)
```
{{--  edit.edge  --}}
<form action="/posts/{{post.id}}?_method=put" method="POST">
  <div>
    <p>
      <label for="title"> Post title </label>
    </p>
    <input type="text" name="title" value="{{post.title}}" />
  </div>

  <div>
    <p>
      <label for="body"> Post body </label>
    </p>
    <textarea name="body" cols="30" rows="10">{{post.content}}</textarea>
  </div>

  <div>
    <button type="submit"> Update Post </button>
  </div>
</form>
```

```
//routes.ts

import Route from '@ioc:Adonis/Core/Route'

Route.on('/').render('welcome');
Route.get('/about', async () => {
  return 'About page'
})
Route.resource("posts", "PostsController");

```

```
//PostsController.ts
  public async update(ctx: HttpContextContract) {
    const post = await Post.find(ctx.params.id);

    post?.merge({
      title: ctx.request.all().title,
      content: ctx.request.all().body,
    });

    if (post !== null) {
      await post.save();
      ctx.response
        .redirect()
        .toRoute("PostsController.show", { id: post.id });
    }
    ctx.response
        .redirect()
        .toRoute("PostsController.show", { id: ctx.params.id });
  }
```

## Request Details

URI | /posts/1?_method=put
-- | --
Request Method | POST
HTTP Version | 1.1
Connection | keep-alive

## Headers

HOST | localhost:3333
-- | --
USER-AGENT | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
ACCEPT | text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
ACCEPT-LANGUAGE | en-US,en;q=0.5
ACCEPT-ENCODING | gzip, deflate
CONTENT-TYPE | application/x-www-form-urlencoded
CONTENT-LENGTH | 27
ORIGIN | http://localhost:3333
REFERER | http://localhost:3333/posts/1/edit
UPGRADE-INSECURE-REQUESTS | 1

## list:routes
| Route                | Handler                 | Middleware | Name          | Domain |
| -- | -- | -- | -- | -- |
| GET /                | Closure                 |            |               |        |
| GET /about           | Closure                 |            |               |        |
| GET /posts           | PostsController.index   |            | posts.index   |        |
| GET /posts/create    | PostsController.create  |            | posts.create  |        |
| POST /posts          | PostsController.store   |            | posts.store   |        |
| GET /posts/:id       | PostsController.show    |            | posts.show    |        |
| GET /posts/:id/edit  | PostsController.edit    |            | posts.edit    |        |
| PUT,PATCH /posts/:id | PostsController.update  |            | posts.update  |        |
| DELETE /posts/:id    | PostsController.destroy |            | posts.destroy |        |

**Comment by RomainLanz** [comment]
Hey @tallredmanxyz ! 👋 

Have you activated the method spoofing [inside your configuration](https://github.com/adonisjs/core/blob/develop/templates/config/app.txt#L53)?

**Comment by tallredmanxyz** [comment]
oh dear! Thanks @RomainLanz I didn't realize this was a configuration setting!

Thanks so much for the quick response.  Will dig further into the docs. Still very new to adonis!
