### ISSUE TITLE
Bug: Duplicate route name, even with different prefix

### ISSUE THREAD

**Issue by yungsilva** [adonisjs/core#1246]
## Package version
`"@adonisjs/ace": "^6.9.3",`
`"@adonisjs/core": "^5.0.0-preview-rc-1.9"`
`"@adonisjs/fold": "^6.3.5"`

## Node.js and npm version
Node - v12.16.3
npm - 6.14.4

## Sample Code (to reproduce the issue)
```ts
Route.group(() => {
  Route.resource("/categories", "PostsController");
}).prefix("/blog");

Route.group(() => {
  Route.resource("/categories", "ProductsController");
}).prefix("/products");

```

`Exception: E_DUPLICATE_ROUTE_NAME: Duplicate route name categories.index`

I have a large application and divided as my routes by files, each file is usually a group of routes, but it remains conflicting, this is annoying

## BONUS (a sample repo to reproduce the issue)
https://github.com/yungsilva/route-group-issue/blob/master/start/routes.ts

**Comment by RomainLanz** [comment]
Hey @yungsilva! 👋 

You need to prefix the route's name by using the `as()` method in the group.

```js
Route.group(() => {
  Route.resource("/categories", "PostsController");
}).prefix("/blog").as('blog')
```

[Source Code](https://github.com/adonisjs/http-server/blob/develop/src/Router/Group.ts#L138)
