### ISSUE TITLE
Getting error as "TypeError: validator.rule is not a function" while starting server

### ISSUE THREAD

**Issue by SebFox2011** [adonisjs/core#1247]
## Package version
@adonisjs/core": "^5.0.0-preview-rc-1.6

## Node.js and npm version
npm v6.14.5 and node v12.16.2

## Sample Code (to reproduce the issue)
node ace serve --watch

Package.json:
{
  "name": "",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build",
    "start": "node ace serve --watch"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^2.1.2",
    "adonis-preset-ts": "^1.0.4",
    "pino-pretty": "^4.0.0",
    "typescript": "^3.9.5",
    "youch": "^2.0.10",
    "youch-terminal": "^1.0.0"
  },
  "dependencies": {
    "@adonisjs/ace": "^6.9.3",
    "@adonisjs/auth": "^4.1.5",
    "@adonisjs/core": "^5.0.0-preview-rc-1.6",
    "@adonisjs/fold": "^6.3.5",
    "@adonisjs/lucid": "^8.1.1",
    "@adonisjs/session": "^3.0.3",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "sqlite3": "^4.2.0"
  }
}

## BONUS (a sample repo to reproduce the issue)

npm start

ℹ  info      cleaning up build directory build
ℹ  info      copy .env,ace build
☐  pending   compiling typescript source files
✔  success   built successfully
ℹ  info      copy .adonisrc.json build
✔  create    ace-manifest.json
…  watch     watching file system for changes
ℹ  info      starting http server

TypeError: validator.rule is not a function

1 Object.extendValidator
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/lucid/build/src/Bindings/Validator.js:125

2 anonymous
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/lucid/build/providers/DatabaseProvider.js:118

3 Ioc.with
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/fold/build/src/Ioc/index.js:533

4 DatabaseServiceProvider.defineValidationRules
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/lucid/build/providers/DatabaseProvider.js:117

5 DatabaseServiceProvider.boot
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/lucid/build/providers/DatabaseProvider.js:136

6 Registrar.boot
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/fold/build/src/Registrar/index.js:101

7 Bootstrapper.bootProviders
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/core/build/src/Ignitor/Bootstrapper/index.js:179

8 HttpServer.wire
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:62

9 HttpServer.start
  /Users/sebfox/grafikart/RecipeApi/api/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:160

⚠  warn      Underlying HTTP server died with "0 code"

**Comment by RomainLanz** [comment]
Hey @SebFox2011! 👋 

Please, update your dependencies and try again.

**Comment by SebFox2011** [comment]
thks @RomainLanz for your answer.
How can i do this easily ?

**Comment by RomainLanz** [comment]
I'm personally using an utility called [`npm-check-updates`](https://www.npmjs.com/package/npm-check-updates).

```bash
ncu -i -u --greatest
```

**Comment by SebFox2011** [comment]
Yes ok thanks. I have reinsll every thing, and it' works now.
Thks for your help
