### ISSUE TITLE
Make RPC Request and Pull the Response

### ISSUE THREAD

**Issue by dagogodboss** [adonisjs/core#1248]
Am using Adonis to build a Bitcoin RPC system, so am making request with request.js Lib, so but the issue is with the callback when I make the request it works but I can’t see send the response to the web endpoint, when I console the response from the RPC server it works fine but on postman it is blank.

```
const request = require("request");
  getBlockCount({ response}){
    const dataString = `{"jsonrpc":"1.0","id":"curltext","method":"getblockcount","params":[]}`;
    const options = {
        url: `http://${USER}:${PASS}@${HOST}:${PORT}/`,
        method: "POST",
        headers: headers,
        body: dataString
    };
    const returnData;
    const callback = (error, nextRes, body) => {
      if (!error && nextRes.statusCode == 200) {
        const data = JSON.parse(body);
        console.log(data)
        returnData = data;
        response.status(200).send(returnData)
      }
      return response.send('data');
    };
    
    return request(options, callback);
    // const options = requestOption(dataString);
    // console.log(rpcRequest(options, callBack(response)));
}
```
Is there a better way to do this

**Comment by McSneaky** [comment]
Hello, might be more of a question to the forums, but if you need to deal with callbacks, then set implicitEnd to false or promisify the callback.
More about it in here:
https://adonisjs.com/docs/4.1/response#_making_response

**Comment by thetutlage** [comment]
Exactly as @McSneaky said. Closing since not actionable
