### ISSUE TITLE
adonis-ts-app cannot create project 

### ISSUE THREAD

**Issue by ynl** [adonisjs/core#1265]
## Package version
create-adonis-ts-app v2.0.3

## Node.js and npm version
nodejs  v14.5.0
yarn v1.22.4

## Sample Code (to reproduce the issue)
run 
```
yarn create adonis-ts-app blog
```
result
![image](https://user-images.githubusercontent.com/5300032/87865964-efec7e00-c9ad-11ea-82b3-f8e253f4d5bc.png)
```
error Couldn't find any versions for "@adonisjs/http-server" that matches "^2.1.2"
```

**Comment by RomainLanz** [comment]
Hey @ynl! 👋 

It seems to be an issue related to `yarn` directly.
Please, try to use `npm` to install a new project and let me know if it worked.

**Comment by ynl** [comment]
after run `npm init adonis-ts-app blog`
same result `npm ERR! notarget No matching version found for @adonisjs/http-server@^2.1.2.`
![image](https://user-images.githubusercontent.com/5300032/87877124-11ca1d00-ca0f-11ea-96d8-27bdaa4976b7.png)

**Comment by ynl** [comment]
npm version 6.14.5

**Comment by ynl** [comment]
run `npm install @adonisjs/http-server@^2.1.2 --save`
same error
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @adonisjs/http-server@^2.1.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by ynl** [comment]
i've got the reason: the package is not exist in my npm registry . close this issue

**Comment by RomainLanz** [comment]
@alfonsodav Update your Node.js version.

**Comment by bralash** [comment]
I am currently facing this same issue. 
node v20.5.0

<img width="584" alt="Screenshot 2023-08-08 at 9 14 32 AM" src="https://github.com/adonisjs/core/assets/6627275/3ba8d8cc-3ece-40e3-934a-385aecb92b3b">
