### ISSUE TITLE
How about ace make:migration on V5?

### ISSUE THREAD

**Issue by leandrowkz** [adonisjs/core#1282]
## Description
Hi folks! I'm trying to use migrations on preview V5, but i'm getting the following error: "make:migration" command not found. According with [this post](https://preview.adonisjs.com/blog/introducing-adonisjs-v5/) all adonis-cli commands would be moved to ace. This post also says ace commands are ready to be used.

What i'm i doing wrong in this case?
How can i use migrations on V5?

## Package version
"@adonisjs/ace": "^6.9.3",
"@adonisjs/core": "^5.0.0-preview-rc-1.9",

## Node.js and npm version
node v12.6.0
npm v6.13.1

## Sample Code (to reproduce the issue)
node ace make:migration create_accounts_table

## Result 
"make:migration" command not found

**Comment by facku** [comment]
This feature should not be implemented yet, you could try running
node ace --help
To show available ace commands, The V5 it's no ready for production/real world app yet....

**Comment by RomainLanz** [comment]
Hey @leandrowkz! 👋 

Have you installed Lucid, then scaffold the configuration and built the code once?
https://preview.adonisjs.com/guides/database/setup

**Comment by leandrowkz** [comment]
@RomainLanz, yes i dit it and it is working now. Thanks ;)
