### ISSUE TITLE
UUID Primary Key

### ISSUE THREAD

**Issue by mohux** [adonisjs/core#1296]
I'm using AdonisJS v5 and not v4
when i use User.create()

and add @beforeCreate hook to create a uuid 
it returns 0 instead of the stored uuid

therefore the solution of adding 
```static async get increments(){}```
does not work

I tried so many things to fix the issue
but it always return 0

**Comment by RomainLanz** [comment]
Hey @mohux! 👋 

There's no `increments` method inside the Lucid Model.
Also, if you are using PostgreSQL I'd recommend you to directly use the function `uuid_generate_v4()` as default instead of generating the `uuid` yourself.
