### ISSUE TITLE
optional() not supported in schema type enum

### ISSUE THREAD

**Issue by lukaserat** [adonisjs/core#1317]
## Package version
5.0.0-preview-rc-1.9

## Node.js and npm version
node v12.16.2
npm 6.14.6

## Sample Code (to reproduce the issue)
```js
// import lines
import { schema, rules } from '@ioc:Adonis/Core/Validator'
```
```js
return schema.create({
  group: schema.enum(GROUPS).optional(),
})
```

NOTE: `GROUPS` is just a array of string

See documentations regarding the use of `optional`
https://preview.adonisjs.com/guides/validator/usage#marking-fields-as-optional

**Comment by thetutlage** [comment]
Coz you are using it the wrong way. Just re-read the docs carefully. It should be

```ts
group: schema.enum.optional(GROUPS)
```

and please use discussions until you are sure that you are reporting an issue
