### ISSUE TITLE
Lucid and Database

### ISSUE THREAD

**Issue by mohux** [adonisjs/core#1335]
if I use Database, adding "as" inside select works perfectly 
but with Lucid it doesn't work at all 

![image](https://user-images.githubusercontent.com/57658626/88467942-50ffde80-cee5-11ea-9258-0ff3f638e626.png)

**Comment by thetutlage** [comment]
The issue is badly formatted and doesn't share much information. Also, please use discussions https://github.com/adonisjs/core/discussions
