### ISSUE TITLE
Scheduled tasks

### ISSUE THREAD

**Issue by Xstoudi** [adonisjs/core#1400]
## Why this feature is required (specific use-cases will be appreciated)?
It would be great to have someting like scheduled tasks : archive every day at XX:XX:XX, remove inactive users every month, etc.

## Have you tried any other work arounds?
There is obviously workarounds like cron tasks. But I think it will be good to get something built-in.

## Are you willing to work on it with little guidance?
Yes of course!

**Comment by thetutlage** [comment]
I suggest starting with a formal RFC will be a nice first step. You can create an issue in this repo https://github.com/adonisjs/rfcs and make sure to describe it thoroughly. For reference, you can check other RFCS like https://github.com/adonisjs/rfcs/issues/24

**Comment by Xstoudi** [comment]
Done :
[Scheduled tasks](https://github.com/adonisjs/rfcs/issues/25)

Do not hesistate to tell me if it's not complete enough.
