### ISSUE TITLE
Cannot find module 'phc-argon2

### ISSUE THREAD

**Issue by medievalcodercom** [adonisjs/core#1515]
I am having an error:
Can't find module phc-argon2

Code:
`   public async register ({ request, auth, response }: HttpContextContract) {
    // get user data from signup form

    const validationSchema = schema.create({
      email: schema.string({trim: true}, [
        rules.email(),
        rules.maxLength(255),
        rules.unique({ table: 'users', column: 'email'}),
      ]),
      password: schema.string({ trim: true}, [
        rules.confirmed(),
      ]),
    })

    const validateData = await request.validate({
      schema: validationSchema,
    })

    try {
      // save user to database
      const user = await User.create(validateData)

      // generate token
      const token = await auth.use('api').attempt(user.email, user.password)

      return response.json({
        status: 'success',
        token: token,
      })
    } catch (error) {
      console.log(error)
      return response.status(400).json({
        status: 'error',
        message: 'There was a problem creating the user, please try again later.',
      })
    }
  }`

**Comment by RomainLanz** [comment]
Hey @medievalcodercom! 👋 

You need to install `phc-argon2` to use Hashing.
Also, please, [do some research](https://github.com/adonisjs/core/discussions?discussions_q=argon) before opening an issue.
