### ISSUE TITLE
Cannot select database driver to continue for lucid commands

### ISSUE THREAD

**Issue by nickngqs** [adonisjs/core#1641]
## Package version
5.0.0-preview-rc-1.12
@adonisjs/lucid = ^8.4.3

## Node.js and npm version
node v12.18.3
npm v6.14.6

## Sample Code (to reproduce the issue)
1) Run `node ace invoke @adonisjs/lucid`
2) `Select the database driver you want to use`
3) Pressing enter result in Select at least one database driver to continue

Is there a way to select the options given by lucid command? Enter doesn't seem to work

<img width="576" alt="Screenshot 2020-09-22 at 12 51 47 PM" src="https://user-images.githubusercontent.com/3901903/93845276-d24fd380-fcd2-11ea-9c12-31a46c890732.png">

**Comment by thetutlage** [comment]
Press `space` to select. Also please use discussions in the future. The issues are reserved for identified bugs and improvements https://github.com/adonisjs/core/discussions
