### ISSUE TITLE
After install mysql - "Cannot find module 'proxy-addr' or int corresponding type declarations"

### ISSUE THREAD

**Issue by Happy-Child** [adonisjs/core#1674]
I follow strictly the documentation:

installation
yarn create adonis-ts-app some
node ace serve --watch

database
yarn add @adonisjs/lucid@alpha
node ace invoke @adonisjs/lucid - at this point the project starts normally

but after installing mysql - npm i mysql, the typescript swears at the package

## Package version
![image](https://user-images.githubusercontent.com/40471724/94371135-d75eb980-00fc-11eb-8cf0-99faaf9bd053.png)

## Node.js and npm version
![image](https://user-images.githubusercontent.com/40471724/94371097-936bb480-00fc-11eb-8420-69850245382e.png)

## OC version
![image](https://user-images.githubusercontent.com/40471724/94371328-6a4c2380-00fe-11eb-939a-a9c6308c1193.png)

## Error
![image](https://user-images.githubusercontent.com/40471724/94371074-60292580-00fc-11eb-8116-281e5062dd47.png)
![image](https://user-images.githubusercontent.com/40471724/94371113-aaaaa200-00fc-11eb-8deb-34e97176ed61.png)

**Comment by Happy-Child** [comment]
ADDITION
This error does not depend on mysql, when installing any database (pg, sqlite) this error appears

**Comment by Happy-Child** [comment]
I'm sorry) changed the user to another and back, rebooted the laptop - it worked

**Comment by thetutlage** [comment]
The main root cause is mixing `yarn` and `npm`. You begin by creating the app using yarn and then used `npm` to install mysql and hence the dependencies tree got messed up
