### ISSUE TITLE
whereNotIn() not working, but whereIn() is

### ISSUE THREAD

**Issue by D-Marc1** [adonisjs/core#1677]
For some reason, `whereNotIn()` is not working for me, yet `whereIn()` works perfectly fine.

## Package version

^5.0.0-preview-rc-1.11

## Node.js and npm version

Node version = v12.18.3

npm version = 6.14.8

## Sample Code (to reproduce the issue)

```js
const requestTags = [3];
const requestNotTags = [2, 4];

const resultQuery = Song.query()
  .select('id', 'title', 'duration', 'type')
  .preload('categories', (query) => {
    query.select('name');
  })
  .whereHas('categories', (query) => {
    if (requestTags.length > 0) {
      query.whereIn('categories.id', requestTags); // This works perfectly fine
    }

    if (requestNotTags.length > 0) {
      query.whereNotIn('categories.id', requestNotTags); // This doesn't work
  });
```

**Comment by thetutlage** [comment]
@D-Marc1 I suggest enabling query debugging and inspect the queries being executed by Lucid https://preview.adonisjs.com/guides/database/debugging-queries. Also are you sure that `requestNotTags` does have a length over `0`?

**Comment by D-Marc1** [comment]
@thetutlage Your fast response is very much appreciated!

Yes, I'm positive `requestNotTags` has a length over `0`. I actually enabled debugging and I do see see the `whereNotIn()` in the output. Let me know if you'd Like to see my output.

I actually revealed something new though. The `whereNotIn()` clause successfully filters out songs if there's only **one** category in the pivot table. So for this example, say a song had one category in the pivot table with the id `2`, then it would filter it out. But for some reason if that song had multiple ids, like `2` *and* `3`, then it would not filter it out.

Also, I should mention that Songs and Categories have a many to many relationship, if that's not clear.

**Comment by D-Marc1** [comment]
I think actually fixed this, though I'm not sure if this is how it's intended to work like this. I took out `requestTags` an the `whereIn()` clause for simplicity. In short, I had to do the `whereNotIn()` clause twice. In both the the `preload` *and* `whereHas()` clause, like so.

```js
const requestNotTags = [2, 4];

const resultQuery = Song.query()
  .select('id', 'title', 'duration', 'type')
  .preload('categories', (query) => {
    query.select('name');

    if (requestNotTags.length > 0) {
      query.whereNotIn('categories.id', requestNotTags);
    }
  })
  .whereHas('categories', (query) => {
    if (requestNotTags.length > 0) {
      query.whereNotIn('categories.id', requestNotTags);
    }
  });
```

If this is how it's intended to work, I'll close the issue.

**Comment by thetutlage** [comment]
Its hard to know what exactly you are expecting without looking at the SQL query. The job of `whereNotIn` is to just add a SQL `where not in` clause.

**Comment by D-Marc1** [comment]
Here's what I get for the output, with `requestNotTags` having the value of `[1,2]`. The first example has `whereNotIn()` only inside of `whereHas()`, which is incorrect. The second example yields a correct result, when I add it to `preload()` as well. It looks like the main difference in SQL output is that the first example is missing the `not in` part at the end.

**whereNotIn() ONLY inside whereHas()**

```
"mysql" (9.69 ms) select * from `api_tokens` where `id` = ? limit ? [ '1', 1 ]
"mysql" User (8.3 ms) select * from `users` where `id` = ? limit ? [ 1, 1 ]
"mysql" Song (6.39 ms) select count(*) as `total` from `songs` where exists (select * from `categories` inner join `category_song` on `categories`.`id` = `category_song`.`category_id` where `categories`.`id` not in (?, ?) and `songs`.`id` = `category_song`.`song_id`) [ 1, 2 ]
"mysql" Song (4.66 ms) select `id`, `title`, `duration`, `type` from `songs` where exists (select * from `categories` inner join `category_song` on `categories`.`id` = `category_song`.`category_id` where `categories`.`id` not in (?, ?) and `songs`.`id` = `category_song`.`song_id`) order by `id` desc limit ? [ 1, 2, 25 ]
"mysql" Category (17 ms) select `categories`.`name`, `categories`.`id`, `category_song`.`song_id` as `pivot_song_id`, `category_song`.`category_id` as `pivot_category_id` from `categories` inner join `category_song` on `categories`.`id` = `category_song`.`category_id` where `category_song`.`song_id` in (?) [ 1 ]
```

**whereNotIn() inside whereHas()  AND preload()**

```
"mysql" (9.56 ms) select * from `api_tokens` where `id` = ? limit ? [ '1', 1 ]
"mysql" User (4.47 ms) select * from `users` where `id` = ? limit ? [ 1, 1 ]
"mysql" Song (9.23 ms) select count(*) as `total` from `songs` where exists (select * from `categories` inner join `category_song` on `categories`.`id` = `category_song`.`category_id` where `categories`.`id` not in (?, ?) and `songs`.`id` = `category_song`.`song_id`) [ 1, 2 ]
"mysql" Song (8.58 ms) select `id`, `title`, `duration`, `type` from `songs` where exists (select * from `categories` inner join `category_song` on `categories`.`id` = `category_song`.`category_id` where `categories`.`id` not in (?, ?) and `songs`.`id` = `category_song`.`song_id`) order by `id` desc limit ? [ 1, 2, 25 ]
"mysql" Category (5.67 ms) select `categories`.`name`, `categories`.`id`, `category_song`.`song_id` as `pivot_song_id`, `category_song`.`category_id` as `pivot_category_id` from `categories` inner join `category_song` on `categories`.`id` = `category_song`.`category_id` where `categories`.`id` not in (?, ?) and `category_song`.`song_id` in (?) [ 1, 2, 1 ]
```

**Comment by thetutlage** [comment]
Queries looks fine to me. I see you mentioned earlier **"I had to do the whereNotIn() clause twice. In both the the preload and whereHas() callback, like so."**

This is true, since both methods are not related to each other. Lemme try to explain it

- **preload**: Preload method says fetch these relationships for me and you can add constraints on which rows to fetch from the related table

- **whereHas**: This method says limit the parent rows based upon the existence of relationship + extra constraint. 

Take this example:

- You want to fetch all the posts in which you have approved one or more comments
- But you want all comments for those posts (not only the one approved by you)

```ts
Post
 .query()
 .whereHas('comments', (query) => query.where('approved_by', user.id))
 .preload('comments')
```

Now image if the `where` clause of `whereHas` method propagating to `preload`, then you will loose the flexibility of fetching all the comments. 

I hope this makes sense :)

**Comment by D-Marc1** [comment]
That makes sense now that you've explained it. Yes, I clearly misunderstood how `whereHas` works. Thank you so much for taking the time to give a detailed explanation!

**Comment by D-Marc1** [comment]
@thetutlage After more trial, this still doesn't fully work. For example, this could be a record.

```json
 {
      "id": 5,
      "title": "Numb / Encore",
      "duration": 358,
      "type": "a",
      "categories": [
        {
          "name": "Rock",
          "id": 1
        },
        {
          "name": "Rap",
          "id": 2
        }
      ]
    },
}
```

Now if I do `requestNotTags` `[1]`, it will not remove the song record. Instead, it will simply remove the `category` with `id` that equals `1`.

```json
 {
      "id": 5,
      "title": "Numb / Encore",
      "duration": 358,
      "categories": [
      "type": "a",
        {
          "name": "Rap",
          "id": 2
        }
      ]
    },
}
```

Any chance you know what I'm doing wrong here? It works if there's only one category for some reason to properly remove the song though.

**Comment by D-Marc1** [comment]
Reopening this because I truly believe this actually is an issue with `whereHas` in Adonis after all, unless I'm missing something.

**Comment by D-Marc1** [comment]
Reopening this because I truly believe this actually is an issue with Adonis after all, unless I'm missing something. I would think the code in my initial comment should've worked.

**Comment by D-Marc1** [comment]
The answer is that I should've been using `whereNotIn()` inside of `whereDoesntHave()`.
