### ISSUE TITLE
[WARN] Unable to generate manifest file

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [adonisjs/core#1689]
Just created the project, tried to run the command

![image](https://user-images.githubusercontent.com/29608698/94636495-7cb79000-02ab-11eb-95b5-ca666e463ed3.png)

## Package version
"@adonisjs/ace": "^6.0.0",
"@adonisjs/auth": "^4.3.1",
"@adonisjs/core": "^5.0.0-preview-rc",
"@adonisjs/fold": "^6.0.0",

## Node.js and npm version
node v13.7.0

## Sample Code (to reproduce the issue)
npm 6.13.6

**Comment by thetutlage** [comment]
It's just a warning. You can try to run `node ace generate:manifest` as a separate command to see it succeeds or not.
