### ISSUE TITLE
Doubled slash when using Route.resource

### ISSUE THREAD

**Issue by maxxxpavlov** [adonisjs/core#1703]
I wanted to use `Route.resource` in a group with a prefix and leave resource's path blank but I got routes with a doubled slash.

## Package version
5.0.0-preview-rc-1.12

## Node.js and npm version
v12.18.3, v6.14.8

## Sample Code (to reproduce the issue)
```javascript
import Route from '@ioc:Adonis/Core/Route'

Route.group(() => {
  Route.resource('', 'test')
}).prefix('test')
```
`node ace list:routes`

`GET /test//:id  `
`GET /test//:id/edit `
`PUT,PATCH /test//:id`

**Comment by thetutlage** [comment]
How can you have a resource with no name?

**Comment by maxxxpavlov** [comment]
For example, when I want to have additional methods in resource without having to create an odd group.
```javascript
import Route from '@ioc:Adonis/Core/Route'

Route.group(() => {
  Route.resource('/', 'test')
  Route.get('reload', 'test.reload')
}).prefix('test')
```

**Comment by thetutlage** [comment]
But still `/` isn't a resource. A resource is some kind of an object/entity. A `user` is a resource, a `post` is a resource.

Using shortcuts to make up a resource name will break so many other things, for example: The route names. It should be as simple as the following example:

```ts
 Route.resource('test', 'test')
 Route.get('test/reload', 'test.reload')
```

**Comment by RomainLanz** [comment]
Closing since not actionable.
