### ISSUE TITLE
API Guard Not working

### ISSUE THREAD

**Issue by kaisian97** [adonisjs/core#1707]
Issue: **Cannot find module 'phc-argon2'**
After add phc-argon2: **pchstr must contain a $ as first char**
## Package version
{
  "name": "server",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build",
    "start": "node ace serve --watch",
    "lint": "eslint . --ext=.ts"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^2.0.0",
    "adonis-preset-ts": "^1.0.4",
    "eslint": "^7.10.0",
    "eslint-plugin-adonis": "^1.0.15",
    "pino-pretty": "^4.2.1",
    "typescript": "^4.0.3",
    "youch": "^2.1.0",
    "youch-terminal": "^1.0.1"
  },
  "dependencies": {
    "@adonisjs/ace": "^6.0.0",
    "@adonisjs/auth": "^4.3.1",
    "@adonisjs/core": "^5.0.0-preview-rc-1.12",
    "@adonisjs/fold": "^6.0.0",
    "@adonisjs/lucid": "^8.4.4",
    "luxon": "^1.25.0",
    "pg": "^8.3.3",
    "phc-argon2": "^1.0.10",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
}

## Node.js and npm version
Node v14.5.0
yarn 1.22.4 (I am using yarn)

## Sample Code (to reproduce the issue)
```
public async login ({ request, auth }: HttpContextContract) {
        const email = request.input('email')
        const password = request.input('password')
        
        const token = await auth.use('api').attempt(email, password)
        return token.toJSON()
      }
```

## BONUS (a sample repo to reproduce the issue)
https://github.com/kaisian97/adonis-test

**Comment by thetutlage** [comment]
There are many discussions around this in the discussions forum. So please search it first and do not open issues until someone from the core team validates it as a real issues. https://github.com/adonisjs/core/discussions
