### ISSUE TITLE
Easier Service Providers in order to leverage npm package functionalities faster

### ISSUE THREAD

**Issue by mendrinos** [adonisjs/core#1741]
## Why this feature is required (specific use-cases will be appreciated)?
In AdonisJS 4.1, you had this IoC binding concept named as Service Providers:
https://adonisjs.com/docs/4.1/service-providers 

Hope to see a more straightforward/automated approach to being able to leverage npm packages out of the box. 

## Have you tried any other work arounds?
Tried to add a Service Provider for:
https://www.npmjs.com/package/couchbase 

Was not that straightforward..

## Are you willing to work on it with little guidance?
Not that much skilled

**Comment by thetutlage** [comment]
You can use npm packages in AdonisJS similar to any other Nodejs codebase.

- Install package from npm
- Require the package anywhere you want. No need to wrap it inside the service provider

**Comment by thetutlage** [comment]
Closing since not actionable. I believe, writing an FAQ on the website can help in educating that using npm packages as it is in AdonisJS is perfectly fine
