### ISSUE TITLE
Adonis v5 isPrimary auto increment issue

### ISSUE THREAD

**Issue by knajjars** [adonisjs/core#1798]
## Description
When model column is defined with `isPrimary` the default behavior of auto increment the primary key is returned when an instance is created. It is stored correctly in my case I use the hook `beforeCreate` to set the primary key value as a UUID and the UUID is stored in DB, no issues here.

## Package version
adonis v5

## Node.js and npm version
node 14.5
npm 6.14.8

## Sample Code (to reproduce the issue)
```
export default class User extends BaseModel {
  @beforeCreate()
  public static async addUidHook(user: User) {
    user.uid = uuidv4()
  }

  @column({ isPrimary: true })
  public uid: string

@column()
  public name: string

  @column.dateTime({ autoCreate: true })
  public createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  public updatedAt: DateTime
}


---
const user: User = await User.create({ name: "Adonis" })
console.log(user.uid) --> 1

---
In SQL Lite
uid
66f76cb2-934f-4458-bdf3-3b09a5cc6cce
```

**Comment by thetutlage** [comment]
Here's the answer. https://github.com/adonisjs/core/discussions/1416#discussioncomment-92657

**Comment by knajjars** [comment]
> Here's the answer. [#1416 (comment)](https://github.com/adonisjs/core/discussions/1416#discussioncomment-92657)

thanks , will update docs
