### ISSUE TITLE
Property 'auth' does not exist on type 'HttpContextContract'

### ISSUE THREAD

**Issue by parkerproject** [adonisjs/core#1801]
`  public async create ({ request, auth, response }: HttpContextContract) {
 .....
  }`

auth property doesn't exist on HttpContextContract, any thoughts on this

**Comment by mlusca** [comment]
Has the Auth package been properly configured?

https://preview.adonisjs.com/guides/auth/setup

**Comment by thetutlage** [comment]
Use Github discussions and do not create unnecessary issues until confirmed

**Comment by urishabh11** [comment]
Happened for me on VSCode, I got it resolved by

Cmd + Shift + P or Ctrl + Shift + P 

TypeScript : Reload Project  Or Reload Window
