### ISSUE TITLE
After upgrading for in-memory compiler, no longer executes programmatic commands

### ISSUE THREAD

**Issue by mlusca** [adonisjs/core#1806]
after changing perform the upgrade to the in-memory compiler, by executing the following command:

`await ignitor.ace().handle(['migration:run'])`

I get the following error:

[ warn ]  Underlying HTTP server died with "0 code"

Prior to the upgrade, was running.

## Package version
 "@adonisjs/core": "^5.0.4-preview-rc-2",

## Node.js and npm version
npm 6.13.4
node 12.14.1

## Sample Code (to reproduce the issue)
```
Route.get('/', async () => {
  const ignitor = new Ignitor(process.cwd())
  await ignitor.ace().handle(['migration:run'])
})
```

**Comment by thetutlage** [comment]
Because this is not the right way to execute commands. Each command is responsible to starting and closing the process it starts. Since you are running the command in your main process, it ends up closing that main process.

You should execute the command by spawing a new shell. Using a module like `execa` is very straight forward.

```sh
import execa from 'execa'

Route.get('/', async () => {
  await execa.node('ace', ['migration:run'], {
    cwd: process.cwd(),
    stdio: 'inherit',
  })
})
```

**Comment by mlusca** [comment]
It really was that, with the execa it worked, thanks.

**Comment by mlusca** [comment]
@thetutlage Just to document it I did it like this:

```
 await execa.node('ace', ['migrate:client', this._instancia.bancoDados], {
      cwd: process.cwd(),
      stdio: 'inherit',
  })
```
In command:

```
Auth.applyTenant(this.schema, this.schema)

const ignitor = new Ignitor(process.cwd())
await ignitor.ace().handle(['migration:run'])
```

Only with execa it didn't work, because when creating a new process instance, I lose the tenant of the database, because I'm running the migration on the client, another database.
With that, after execa executes a new instance of the main process, I migrate in the same way as before and configuring the tenant.
