### ISSUE TITLE
Adonis v5 bug with tag "loggedIn"

### ISSUE THREAD

**Issue by clemclx** [adonisjs/core#1815]
The Edge tag "loggedIn" seems to be broken with the version 5 of Adonis.
Using it throws a SyntaxError "Missing catch or finally after try" when rendering template.

![image](https://user-images.githubusercontent.com/22498760/97467571-a1ebfc80-1944-11eb-941f-1334450043d0.png)

Of course, i properly added to middleware register the SilentAuth Middleware in the kernel.ts file

Let me know if more resources needed and thanks

## Package version
@adonisjs/core@^5.0.4-preview-rc
@adonisjs/auth@^5.0.2

## Node.js and npm version
Node v14.15.0
Yarn v1.22.5

## Sample code
![image](https://user-images.githubusercontent.com/22498760/97468039-22aaf880-1945-11eb-9ccd-371d4cff5f5c.png)

**Comment by nadir1122** [comment]
This git project seems to be dead.

**Comment by thetutlage** [comment]
Not really a bug. Something that is not mentioned in v5 docs shouldn't be assumed.

@nadir1122 Not sure what you mean by dead
