### ISSUE TITLE
Fake Not Working

### ISSUE THREAD

**Issue by VictorLessa** [adonisjs/core#1826]
## Prerequisites

I have a price adjustment service that has a repository as a dependency
When trying to test this service by creating a mock of the repository I am not successful, the test uses the original repository
sorry about my English

## Package version
4.1.0

## Node.js and npm version
Node 14.10.0 Npm 6.14.8

## Sample Code (to reproduce the issue)
![image](https://user-images.githubusercontent.com/33801047/97789276-e4f4dc80-1b9d-11eb-8700-a3187d2cc938.png)

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
