### ISSUE TITLE
AdonisJS requires "@adonisjs/assembler" in order to run typescript source directly

### ISSUE THREAD

**Issue by mvpxtech** [adonisjs/core#1858]
## Node.js and npm version
node v14.5.0
yarn v1.22.5

## Reproduce
1. Create a new fresh app
2. Add and install mysql
3. Deploy to Heroku

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
