### ISSUE TITLE
View.global not working in loop 

### ISSUE THREAD

**Issue by VictorLessa** [adonisjs/core#1937]
![image](https://user-images.githubusercontent.com/33801047/99737944-2a733e00-2aa8-11eb-990a-b652cca5a47c.png)

I need to render dynamic fields based on the array I retrieve from the bank, as the edge does not allow a template string I sent it to view.global to make it easier
, but apparently that render_electromechanical_meter function loads once before everything, even before the page loads itself
I write this code inside the script tag
Sorry my english

**Comment by RomainLanz** [comment]
Hey @VictorLessa! 👋 

Could you please be more descriptive about your issue?
Also, I don't get your code example, you are showing frontend code while talking about Edge.

**Comment by thetutlage** [comment]
And shouldn't be an issue at all. Use discussions
