### ISSUE TITLE
will SendGrid API key and 2FA migration will work with the same account even with base authentication also until the deadline date.

### ISSUE THREAD

**Issue by TestThej** [adonisjs/core#1948]
will SendGrid API key and 2FA migration will work with the same account even with base authentication also until the deadline date.  once i migration what are the changes nee to be done in code to send emails as SMTP after 2FA Migation.

_Originally posted by @TestThej in https://github.com/adonisjs/core/discussions/1898#discussioncomment-136025_

**Comment by thetutlage** [comment]
Not sure why this is an issue and what exactly you are trying to say.
