### ISSUE TITLE
Validation needs improvement

### ISSUE THREAD

**Issue by Salman-Kashfy** [adonisjs/core#1988]
I am using Adonis v5...the validation code looks like this

`const validator = schema.create({
        title: schema.string({trim: true},[
        ]),
        file: schema.file({
            size: '2mb',
            extnames: ['jpg', 'png', 'jpeg'],
        },[
            rules.nullable()
        ])
        });`

I really need a nullable validation rule. Also this convention has lot of code to write, laravels validation was much smaller with pipe separed rules.

**Comment by thetutlage** [comment]
Can you tell me how will you get type information with `pipe` separated rules?

**Comment by Salman-Kashfy** [comment]
> Can you tell me how will you get type information with `pipe` separated rules?

Okay i get it now :) What about the nullable part ?

**Comment by Salman-Kashfy** [comment]
Please I need to know the validation rule for nullable. ? I have found no references anywhere on nullable validation rule.
