### ISSUE TITLE
Mongo and relational database adonis js

### ISSUE THREAD

**Issue by boydwo** [adonisjs/core#2000]
Is it possible to use the mongo and a relational database at the same time?

**Comment by muco-rolle** [comment]
As I'm not used to Adonisjs but I think can use mongoose

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
