### ISSUE TITLE
V5 - Build problems with finding .env variables

### ISSUE THREAD

**Issue by briodev** [adonisjs/core#2009]
## Package version
"devDependencies": {
    "@adonisjs/assembler": "^3.0.6",
    "adonis-preset-ts": "^1.1.0",
    "pino-pretty": "^4.3.0",
    "typescript": "^4.1.2",
    "youch": "^2.1.1",
    "youch-terminal": "^1.0.1"
  },
  "dependencies": {
    "@adonisjs/core": "^5.0.4-preview-rc-2.1",
    "@adonisjs/repl": "^1.1.6",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }

## Node.js and npm version
v12.13.0
6.12.0

## Sample Code (to reproduce the issue)

npm init adonis-ts-app 'new-api-project'
npm install
node ace build --production
cd build
npm ci --production
node server.js

Will not run server - Exception: E_MISSING_ENV_VALUE: Missing environment variable "HOST"

Is there a step I'm missing to use the .env file for my variables? 

Was working in a previous version
"@adonisjs/core": "^5.0.0-preview-rc-1.12",

**Comment by hamzasgd1** [comment]
same problem here....any find the fix

**Comment by thetutlage** [comment]
Please check the existing discussions https://github.com/adonisjs/core/discussions/1874

**Comment by Anastasia-yes** [comment]
Have to copy .env file to build folder from project folder!!!
