### ISSUE TITLE
test/list-routes.spec.ts calls deprecated fold lib

### ISSUE THREAD

**Issue by bingalls** [adonisjs/core#2020]
## Package version
v5.0.4-preview-rc-2.1

## Node.js and npm version
n/a but happens on node >= 14, npm >= 6

## Sample Code (to reproduce the issue)
https://github.com/adonisjs/core/blob/v5.0.4-preview-rc-2.1/test/list-routes.spec.ts
line 12

## BONUS (a sample repo to reproduce the issue)
According to https://preview.adonisjs.com/blog/october-2020-release
the *fold* library is deprecated, but this file still calls it!

**Comment by thetutlage** [comment]
Who said that `fold` is deprecated?
