### ISSUE TITLE
Not able to use use() fucntion

### ISSUE THREAD

**Issue by hamzasgd1** [adonisjs/core#2024]
"@adonisjs/core": "^5.0.4-preview-rc-2.1",

https://github.com/reg2005/adonis5-queue#readme
I'm using this package for queue but when I write this

const Queue = use('@ioc:Adonis5/Queue');

error says use in not defined

**Comment by RomainLanz** [comment]
Hey @hamzasgd1! 👋 

AdonisJS 5 has never used the `use()` function.
The package you are looking for does not work on AdonisJS 5.

**Comment by hamzasgd1** [comment]
@RomainLanz I already managed to make it work on AdonisJS 5.
