### ISSUE TITLE
Allow for type="module" in view script() method

### ISSUE THREAD

**Issue by e-e** [adonisjs/core#2029]
## Why this feature is required (specific use-cases will be appreciated)?
Would allow for consistent templating - the current workaround is to just use a normal html `script` tag

## Have you tried any other work arounds?
See above

## Are you willing to work on it with little guidance?
Yes, I spent a few minutes trying to locate where this view global is defined, but wasn't able to find anything. I would be willing to add this feature if someone could point me in the right direction.

**Comment by e-e** [comment]
Could be as simple as `{{ script('js/script', 'module') }}`, where the second argument is the script-tag "type" value, which would default to "text/javascript"

**Comment by thetutlage** [comment]
It's a frontend related thing. Adonisjs is a backend framework and you must use frontend build tools for all this

**Comment by e-e** [comment]
@thetutlage I'm sorry, but I think you are very much misunderstanding what I am saying. What I'm asking is for the `script()` view global to allow for generating a *script tag* with the `type` attribute containing the value "module" instead of "text/javascript". See https://adonisjs.com/docs/4.1/views#_script.

 So, as in my proposed example above, `{{ script('js/script', 'module') }}` would generate:

```
<script type="module" src="/js/script.js"></script>
```

**Comment by thetutlage** [comment]
Yup, got confused thinking, you want to transpile these modules as well. 

Related to this, why not write it directly in HTML?

**Comment by e-e** [comment]
No worries. 

You're right, and as I said in the original issue, the workaround is to just use a normal html script tag, without using the helper function. But if that's the solution, why have the helper function at all and not just add all scripts using plain html 🙂 For the sake of consistency, it would be nice to have this option.

**Comment by thetutlage** [comment]
We have actually removed this helper in v5. Coz it really doesn't make sense to come up with custom primitives that doesn't do much. It was a bad choice made in v4.

So if you want, feel free to ignore these helpers

**Comment by e-e** [comment]
I see, ok that makes sense. Thanks!
