### ISSUE TITLE
NPM Install Failing When Using npx create-adonis-ts-app

### ISSUE THREAD

**Issue by thomcatmeow** [adonisjs/core#2044]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Package version
v5.1.0

## Node.js and npm version
Node: v12.19.0
NPM: 6.14.8
## Sample Code (to reproduce the issue)
```
$ npm init adonis-ts-app help                                                                                               _       _             _         _
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
> Select the project structure · web
> Enter the project name · help
> Setup eslint? (y/N) · true
> Setup prettier? (y/N) · true

RUNNING TASKS
> Scaffold project 337 ms
> Install dependencies 5.15 min
  npm install failed
> Configure installed packages

[ error ]  Unable to create project. Cleaning up
```

**Comment by thetutlage** [comment]
The provided information is not enough to help. Please adhere to issues guidelines
