### ISSUE TITLE
Problem with phc argon hash

### ISSUE THREAD

**Issue by lucaisoardi** [adonisjs/core#2070]
Hi there,

I've a problem with the hash functions. If i try to crypt the user password with method Hash.hash i give this error.

Cannot find module 'phc-argon2'

I've changed the file Argon.js in Drivers folder from

`const phc_argon2_1 = __importDefault(require("phc-argon2"));`

to

const phc_argon2_1 = __importDefault(require("@phc/argon2"));

And now work well, but when i do an update the file will be overwritten.

There is an alpha version with this fix? Thanks.

**Comment by RomainLanz** [comment]
Hey @lucaisoardi! 👋 

If it tolds you that he cannot find the module `phc-argon2` it means you need to install it.

```shell
npm i phc-argon2
```
