### ISSUE TITLE
Fresh installation error for adonis 5

### ISSUE THREAD

**Issue by abdullahsayed4131** [adonisjs/core#2132]
installing taking too much long time like 5hours.. it is struck at 2 other(prod). my npm version is 6.14.3 and node is 14
![Capture](https://user-images.githubusercontent.com/37441843/104645951-d070ac80-56d5-11eb-8a8e-0688eaeb857d.JPG)

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
