### ISSUE TITLE
I suggest just through the docs of Indicative, it's documented https://indicative.adonisjs.com/docs/syntax-guide#_limitations

### ISSUE THREAD

**Issue by smrn90** [adonisjs/core#2155]
I suggest just through the docs of Indicative, it's documented https://indicative.adonisjs.com/docs/syntax-guide#_limitations

_Originally posted by @thetutlage in https://github.com/adonisjs/core/issues/1049#issuecomment-470373759_

the page could not be found..
any help would be appreciated.

**Comment by thetutlage** [comment]
Here's the new link https://indicative-v5.adonisjs.com/docs/syntax-guide#_limitations
