### ISSUE TITLE
[V5] how to allow cors on public files ex images?

### ISSUE THREAD

**Issue by hamzasgd1** [adonisjs/core#2156]
I want to fetch image from public url from cross origin but Request blocked by CORS.
Others link are working like routes but files from public folder are not accessible due to CORS.
how to allow in adonisjs 5 

for routes I used cors.ts in config.

**Comment by moviedo** [comment]
You might want to check this post https://stackoverflow.com/questions/51017702/enable-cors-in-fetch-api

It's not an issue of your frontend js, it's the server which hosts the image file. You may need to proxy the request, (i.e. your server gets the image, you get the image from your server).

**Comment by thetutlage** [comment]
Seems like a bug to me. Will work on the fix soon
