### ISSUE TITLE
How to download file such as figma svg from a remote server location?

### ISSUE THREAD

**Issue by hkmsadek** [adonisjs/core#2164]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Package version
4.1

## Node.js and npm version
Node version : `12.3.1`
NPM version : `6.9.0`

## Sample Code (to reproduce the issue)

I am trying to download file from a remote location like this 

```
return response.attachment('http:localhost/uploads/123323.fig',
                    '123323.fig')

```

Above code send `Error not found`

How to download file from a remote location?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
