### ISSUE TITLE
Port 80 mapping fails silently

### ISSUE THREAD

**Issue by mayureshnw** [adonisjs/core#2173]
I was trying to use port 80 on my server, but it kept failing without any error.
Turns out the port was already in use. An error message would be nice when the app is not able to bind to a provided port. Right now it silently fails.

Note: The silent failure is only for port 80. If the app is not able to bind to other ports like say, "3333" it fails with an error message.`"Port in use, closing server"`

## Steps to reproduce
```
> node ace build
> node ./build/server.js
```
port mapping mentioned in .env file

## Package version
"@adonisjs/core": "^5.0.4-preview-rc-2"

## Node.js and npm version
v12.18.1

## Sample Code (to reproduce the issue)
In .env
`PORT=80`.

**Comment by thetutlage** [comment]
The error should be raised for all the ports in use. So, feel free to suggest on how we can fix this issue, as I am not aware of any specific fix.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
