### ISSUE TITLE
Use Encrypt method with multiple keys

### ISSUE THREAD

**Issue by Agilulfo1820** [adonisjs/core#2185]
## Why this feature is required (specific use-cases will be appreciated)?
I want to encrypt the private key of user's wallet but be able to access it whenever I want. Encryption seems the way.
But I want to encrypt each private key with a different APP_KEY, so that if someone steals my database and my APP_KEY at max only one user will be affected.

At the moment the encryption key is set in the Encryption config file. Is there a way to update it dynamically?

## Are you willing to work on it with little guidance?
If you show me the way I can try to make the feature myself and do a PR.

## Framwork
"adonis-version": "4.1.0",

**Comment by thetutlage** [comment]
Which version of the framework?

**Comment by Agilulfo1820** [comment]
> Which version of the framework?

"adonis-version": "4.1.0",

**Comment by thetutlage** [comment]
Looking at the [code](https://github.com/adonisjs/core/blob/5.0.13/src/Encryption/index.js#L49-L51). You can make use of the `Encryption.getInstance` method to create a new child encryption instance.

However, as of now it doesn't accept a custom app key for encryption. However, I am open to make it configurable if you can create a PR for same

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
