### ISSUE TITLE
Trying Out the Registration Process

### ISSUE THREAD

**Issue by Kaperskyguru** [adonisjs/core#2219]
Hello,

I am currently testing and trying out the AdonisJS 5 Auth system, I am at the Registration process, but when I fill out the form and submit it. 

I get an error saying ```Cannot find module 'phc-argon2'```

I guess I need to install that module individually.

**Comment by ad-on-is** [comment]
As per the documentation: https://preview.adonisjs.com/releases/core/preview-rc-1_7/#hash

npm i phc-argon2 phc-bcrypt

**Comment by thetutlage** [comment]
There are already many discussion threads on same. I recommend searching first before opening an issue. https://github.com/adonisjs/core/discussions?discussions_q=phc-argon
