### ISSUE TITLE
AdonisJS v5 problem build production

### ISSUE THREAD

**Issue by danilloalvis** [adonisjs/core#2246]
## Package version
"@adonisjs/core": "^5.0.4-preview-rc-2.1"

## Node.js and npm version
SERVER
node: v12.16.2
npm: 6.14.4

Local Machine
node: v14.8.0
npm: 6.14.7

## Problem
I am making an API using AdonisJS 5. When I finished the API I generated a build using `node ace build --production`.

I tested it on the local machine and the API worked!
But when I went up to the production server the following error appeared:
>npm run start
>
> start /usr/src/app
> node server.js
>
>Error: Cannot find module '/usr/src/app/app/Exceptions/Handler'
>Require stack:
>- /usr/src/app/node_modules/@adonisjs/fold/build/src/Ioc/index.js
>- /usr/src/app/node_modules/@adonisjs/fold/build/index.js
>- /usr/src/app/node_modules/@adonisjs/aplication/build/index.js
>- /usr/src/app/node_modules/@adonisjs/core/build/standalone.js
>- /usr/src/app/server.js
>
>1 Ioc.resolveAlias
>/usr/src/app/node_modules/@adonisjs/fold/build/src/Ioc/index.js:113
>
>2 Ioc.make
>/usr/src/app/node_modules/@adonisjs/fold/build/src/Ioc/index.js:456
>
>3 ExceptionManager.registerHandler
>/usr/src/app/node_moduLes/@adonisjs/http—server/build/src/Server/ExceptionManager/index.js:30
>
>4 Server.errorHandler
>/usr/src/app/node_modules/@adonisjs/http—server/build/src/Server/index.js:103
>
>5 HttpServer.createServer
>/usr/src/app/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:117
>
>6 HttpServer.start
>/usr/src/app/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:148

## This is my app/Exceptions/Handler.ts

>import Logger from '@ioc:Adonis/Core/Logger'
>import HttpExceptionHandler from '@ioc:Adonis/Core/HttpExceptionHandler'
>
>export default class ExceptionHandler extends HttpExceptionHandler {
>   constructor() {
>     super(Logger)
>   }
>}

## Temporary solution 
The temporary solution I found for this problem was to delete the line `"exceptionHandlerNamespace":"App/Exceptions/Handler"` from the file `.adonisrc.json`

**Comment by RomainLanz** [comment]
Hey @danilloalvis! 👋 

It seems that you are running your application in a Docker Container.
Could you please share the configuration with us so we can try to replicate your issue?

**Comment by danilloalvis** [comment]
`$ cat /etc/os-release`
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian

`$ uname -a`
Kernel: Linux 0dc7fbcc17e0 4.4.0-190-generic #220-Ubuntu SMP Fri Aug 28 23:02:15 UTC 2020 x86_64 GNU/Linux

`$ lscpu`
Architecture......................x86_64
CPU op-mode(s)..............32-bit, 64-bit
Byte Order........................Little Endian
CPU(s):.............................16
On-line CPU(s) list...........0-15
Thread(s) per core...........1
Core(s) per socket............16
Socket(s)..........................1
NUMA node(s)..................1
Vendor ID..........................GenuineIntel
CPU family........................6
Model...............................63
Model name.....................Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
Stepping..........................2
CPU MHz.........................2300.002
BogoMIPS........................4600.00
Hypervisor vendor...........Microsoft
Virtualization type...........full
L1d cache........................32K
L1i cache.........................32K
L2 cache.........................256K
L3 cache.........................25600K
NUMA node0 CPU(s)......0-15
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl xtopology pni cx16 hypervisor lahf_lm ssbd ibrs ibpb kaiser flush_l1d

**Comment by danilloalvis** [comment]
I found the problem, apparently when we run the command `node ace build --production` the folder` app/Exceptions` is being created with the letter 'e' ` app/exceptions`, I just renamed it to the correct name and it worked
