### ISSUE TITLE
Update of the @adonisjs/core package with the latest version of @adonisjs/http-server

### ISSUE THREAD

**Issue by davigs** [adonisjs/core#2255]
Hello guys, I would like to thank you for releasing the version of the http-server 5.1.0 package. 
When will we have the @adonisjs/core version updated to the latest version of http-server? 
The problem I am facing to publish my application on Google App Engine still persists because of the GIT dependency tree that continues to point to @adonisjs/http-server: "^4.0.9" in @adonisjs/core package.json.

I thank you for your help and patience too.

## Package version
5.0.4-preview-rc-2.1

## Node.js and npm version
Node.js: v14.3.0
Npm: 6.14.11

**Comment by thetutlage** [comment]
The package has a breaking change and should not be updated manually. Please wait for the entire release to take place
