### ISSUE TITLE
There is no validator documentation for adonisjs v5

### ISSUE THREAD

**Issue by MrEldin** [adonisjs/core#2282]
Version: Adonis v5

I am trying to implement a validator feature, I created a validator with the command:

`node ace make:validator User`

Validator is created, but what is the way of implementation of the newly created validator?

In Adonis v5 documentation there is no explanation for this implementation?

Help is appreciated.

**Comment by thetutlage** [comment]
https://preview.adonisjs.com/guides/http/form-submissions#using-validator-classes

Shared the link above. Also I recommend using Github discussions for questions, as we keep issues exclusively for reporting confirmed bugs or feature requests
