### ISSUE TITLE
Error: Cannot find module 'Encryption'

### ISSUE THREAD

**Issue by scube-elate** [adonisjs/core#2292]
As per the documentation, I'm trying to use the Encryption module but it seems the module is missing. 

## Package version
"@adonisjs/framework": "^5.0.9",

## Node.js and npm version
npm - 6.14.10
node - v14.15.4

## Sample Code (to reproduce the issue)
```
const Encryption = use('Encryption')
const encrypted = Encryption.encrypt('hello world')
```

Am I missing something?

**Comment by RomainLanz** [comment]
Hey @scube-elate! 👋 

Could you please delete your `node_modules` and re-install your dependency?

**Comment by scube-elate** [comment]
Hi @RomainLanz 👋

I tried it. But same result.

**Comment by RomainLanz** [comment]
Can you share your `package.json` file?

**Comment by scube-elate** [comment]
```
{
  "name": "adonis-fullstack-app",
  "version": "4.1.0",
  "adonis-version": "4.1.0",
  "description": "The fullstack application boilerplate for Adonisjs",
  "main": "index.js",
  "scripts": {
    "start": "node server.js",
    "test": "node ace test"
  },
  "keywords": [
    "adonisjs",
    "adonis-app"
  ],
  "author": "",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@adonisjs/ace": "^5.0.8",
    "@adonisjs/auth": "^3.0.7",
    "@adonisjs/bodyparser": "^2.0.5",
    "@adonisjs/cors": "^1.0.7",
    "@adonisjs/encryption": "^4.0.0",
    "@adonisjs/fold": "^4.0.9",
    "@adonisjs/framework": "^5.0.9",
    "@adonisjs/ignitor": "^2.0.8",
    "@adonisjs/lucid": "^6.1.3",
    "@adonisjs/mail": "^3.0.10",
    "@adonisjs/session": "^1.0.27",
    "@adonisjs/shield": "^1.0.8",
    "@adonisjs/validator": "^5.0.6",
    "@adonisjs/vow": "^1.0.17",
    "aws-sdk": "^2.851.0",
    "cryptr": "^6.0.2",
    "hashids": "^2.2.8",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.21",
    "mysql": "^2.18.1",
    "pluralize": "^8.0.0",
    "validatorjs": "^3.22.1"
  },
  "devDependencies": {
    "eslint": "^7.19.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.3.1",
    "jest": "^26.6.3",
    "prettier": "^2.2.1",
    "supertest": "^4.0.2"
  },
  "autoload": {
    "App": "./app"
  }
}

```

**Comment by mkhuramj** [comment]
@RomainLanz I am a Laravel developer for the last 4, 5 years, I had explored express and other JS frameworks. I was looking for a good Node JS framework for the web and I have found AdonisJS... But this one is super awesome. It is a Laravel in JS. Fantastic work.

I want to contribute to this but I have never ever contributed in any open source. Can you please guide me on how to solve this issue :-)
Seems a stupid question but I think will be good to bring new contributors to the OpenSourcec world of contributions.

**Comment by thetutlage** [comment]
@scube-elate Not sure why you installed `@adonisjs/encryption`, since this is v5 package and shouldn't be installed with v4 apps. I recommend removing this package

**Comment by scube-elate** [comment]
I thought it wouldn't be a breaking change on v5. Anyways thank you. Closing it.
