### ISSUE TITLE
[v5] `createMany` not populating `created_at` and `updated_at`

### ISSUE THREAD

**Issue by rodrigoriome** [adonisjs/core#2310]
Apparently seeding the database using `createMany` doesn't populate timestamp fields. I could show some code if really necessary, but I've just triple-checked (rolling back all migrations) using `createMany` and it just doesn't work. It only worked with a for loop using the default `<model>.create` method.

## Package version
5.0.4-preview-rc-2

## Node.js and npm version
Node v12.19.1 | NPM 6.14.8

## Expected outcome
To have timestamp fields auto-filled when using `createMany` method.

## Actual outcome
Those fields are kept null

**Comment by thetutlage** [comment]
Yes, cannot debug without looking at the code and model definition.

**Comment by rodrigoriome** [comment]
I have tried again on a fresh Adonis and it worked, so... no bugs here, sorry!
