### ISSUE TITLE
init adonis-ts-app fails on Windows10

### ISSUE THREAD

**Issue by philippdormann** [adonisjs/core#2312]
- Node.js version `14.15.0`
- npm version `7.0.2`
- OS: Windows 10 Pro Version 2004 (Build 19041.804)

## Sample Code (to reproduce the issue)
```
❯ npm init adonis-ts-app blog
    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
> Select the project structure · api
> Enter the project name · blog
> Setup eslint? (y/N) · false

RUNNING TASKS
> Scaffold project 109 ms
> Install dependencies 22 s
> Configure installed packages 2.47 ms
  Cannot invoke instructions. Missing package "@adonisjs/core"

[ error ]  Unable to create project. Cleaning up
```

## Expected outcome
a new AdonisJS app scaffolding is expected

## Actual outcome
see above

any help would be appreciated
(I know, #2044 is basically the same)

Interestingly, the error does not appear on Linux +MacOS machines, so this issue might be closed 🤷‍♂️

**Comment by thetutlage** [comment]
Can you run the same command with `--verbose` flag and share the output?

```sh
// Output maybe a little noisy
npm init adonis-ts-app blog --verbose
```

Also, it can be related to npm version 7.0.2. We have not tested the app scaffolding against npm 7. Next release will

**Comment by philippdormann** [comment]
sure thing!
```
❯ npm init adonis-ts-app blog --verbose
npm verb cli [
npm verb cli   'C:\\node\\node.exe',
npm verb cli   'C:\\...\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'init',
npm verb cli   'adonis-ts-app',
npm verb cli   'blog',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.0.2
npm info using node@v14.15.0
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\...\npm\node_modules\npm\npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:E:\projects\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\...\.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:C:\...\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 7ms
npm verb npm-session 930d83d14cf7c9ee
npm timing npm:load Completed in 76ms
npm http fetch GET 304 https://registry.npmjs.org/create-adonis-ts-app 948ms (from cache)
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 0ms
    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
> Select the project structure · api
> Enter the project name · blog
> Setup eslint? (y/N) · false

RUNNING TASKS
> Scaffold project 173 ms
> Install dependencies 37 s
> Configure installed packages 2.49 ms
  Cannot invoke instructions. Missing package "@adonisjs/core"

[ error ]  Unable to create project. Cleaning up
npm timing command:exec Completed in 53545ms
npm timing command:init Completed in 53625ms
npm verb exit 0
npm timing npm Completed in 53964ms
npm info ok
```

**Comment by schmanat** [comment]
I have the same behaviour. The only difference is, that I'm using Node Version 14.15.4 and NPM Version 6.14.10. 
If I run npm init adonis-ts-app adsd-mal --verbose I get the following  output:

```
D:\wip>npm init adonis-ts-app adsd-mal --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'init',
npm verb cli   'adonis-ts-app',
npm verb cli   'adsd-mal',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.10
npm info using node@v14.15.4
npx: installed 171 in 6.951so using node@v14.15.4
    _       _             _         _     14.15.4
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
> Select the project structure · web
> Enter the project name · adsd-mal
> Setup eslint? (y/N) · false

RUNNING TASKS
┌ Scaffold project
│  CREATE: ace.....] - : info using node@v14.15.4
│  CREATE: app\Exceptions\Handler.ts
│  CREATE: commands\index.ts
│  CREATE: env.ts
│  CREATE: providers\AppProvider.ts
│  CREATE: public\favicon.ico
│  CREATE: resources\views\errors\not-found.edge
│  CREATE: resources\views\errors\server-error.edge
│  CREATE: resources\views\welcome.edge
│  CREATE: server.ts
│  CREATE: start\kernel.ts
│  CREATE: start\routes.ts
│  CREATE: .editorconfig
│  CREATE: .gitignore
│  CREATE: .adonisrc.json
│  CREATE: tsconfig.json
└ completed (41 ms)
┌ Install dependencies
│  [ wait ]  typescript, youch, youch-terminal, pino-pretty, adonis-preset-ts, and 1 other (dev)  ..
│  [ wait ]  @adonisjs/core, @adonisjs/repl, @adonisjs/session, @adonisjs/view, proxy-addr, and 2 others (prod)
│  [ error ]  npm install faileding node@v14.15.4
│  npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/thetutlage/matchit.git
│  npm ERR!
│  npm ERR! fatal: unable to access 'https://github.com/thetutlage/matchit.git/': SSL certificate problem: unable to get local issuer certificate
│  npm ERR!
│  npm ERR! exited with error code: 128
│
│  npm ERR! A complete log of this run can be found in:
│  npm ERR!     C:\Users\mschneid\AppData\Roaming\npm-cache\_logs\2021-03-01T15_17_27_779Z-debug.log
│
└ failed (17 s)

[ error ]  Unable to create project. Cleaning up
npm verb exit [ 0, true ]
npm timing npm Completed in 205863ms
npm info ok
``` 

It seems that something went wrong with the SSL Cert of the package matchit

**Comment by McSneaky** [comment]
Do you have Git installed and in PATH?
Saw similar message without Git (can't remember if it got fixed or will be fixed with new with upcoming release)

**Comment by schmanat** [comment]
Yes GIT is installed and in PATH

**Comment by TemaSM** [comment]
Probably it's environment problem with SSL certificates on Windows machine.
Starting from Git 2.14 uses built-in Windows networking layer (Windows certificate storage mechanism), that's why if you have old, self-signed, or buggy CA certificates, Git may not work as expected.

From the Git for Windows 2.14 release notes:
>It is now possible to switch between Secure Channel and OpenSSL for Git's HTTPS transport by setting the `http.sslBackend` config variable to `"openssl"` or `"schannel"`; This is now also the method used by the installer (rather than copying `libcurl-4.dll` files around).

General solution here is to audit/recheck which CA certs old, self-signed or buggy, and remove them from Windows certificate storage.
But for **fast solution**, here's few options available:
1) try different values for Git's `http.sslBackend` by executing in terminal and `npm init ...` again after each:
 `git config --global http.sslBackend schannel`
 `git config --global http.sslBackend openssl`
 2) disable SSL verification for Git, by executing, and `npm init ...` again:
`git config --global http.sslVerify false`
_Please be advised disabling SSL verification globally might be considered a security risk and should be implemented only temporarily_
3) if nothing helped, then you should uninstall Git and install it again from scratch

**Comment by goraSi** [comment]
+1

![image](https://user-images.githubusercontent.com/12007754/109621284-0f9a7600-7b3b-11eb-97a6-6a48ffb105d7.png)

I have tried both options for setting GIT globals.

**Comment by schmanat** [comment]
After setting ```git config --global http.sslBackend schannel``` it works with npm Version 7.6.0 and Node 15.10.0 on Windowns 10 1909

**Comment by thetutlage** [comment]
As I mentioned [here](https://github.com/adonisjs/core/issues/2312#issuecomment-787394553), The installation is not tested against `npm 7.0.0`. So I recommend not using it for now. We have plans to test the next release against it

**Comment by philippdormann** [comment]
alright, thanks 🤲

maybe this could be added to the readme or installer as a info/ requirement?

**Comment by nauval123** [comment]
i use current release of the node js, and i stuck with error and it says
PS G:\belajaradonis\crud+auth> npm init adonis-ts-app tes --verbose     
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'init',
npm verb cli   'adonis-ts-app',
npm verb cli   'tes',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.7.6
npm info using node@v15.14.0
npm timing npm:load:whichnode Completed in 2ms
npm timing config:load:defaults Completed in 3ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 6ms
npm timing config:load:builtin Completed in 6ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:G:\belajaradonis\crud+auth\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\nauval achmad yusufa\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\nauval achmad yusufa\AppData\Roaming\npm\etc\npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 15ms
npm timing npm:load:configload Completed in 15ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 2ms
npm timing npm:load:cleanupLog Completed in 3ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 47ms
npm timing config:load:flatten Completed in 4ms
npm timing config:load:flatten Completed in 1ms
npm timing arborist:ctor Completed in 2ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 1ms
    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
> Select the project structure · api
> Enter the project name · tes
> Setup eslint? (y/N) · false

RUNNING TASKS
> Install dependencies 38 s

[ error ]  Unable to create project. Cleaning up
npm timing command:exec Completed in 47865ms
npm timing command:init Completed in 47985ms
npm timing npm Completed in 48411ms
npm info ok
PS G:\belajaradonis\crud+auth> git init
Initialized empty Git repository in G:/belajaradonis/crud+auth/.git/
PS G:\belajaradonis\crud+auth> git config http.sslVerify false
PS G:\belajaradonis\crud+auth> npm install

up to date, audited 1 package in 554ms

found 0 vulnerabilities
PS G:\belajaradonis\crud+auth> npx create-adonis-ts-app tes --verbose 
    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
> Select the project structure · web
> Enter the project name · tes
> Setup eslint? (y/N) · true
> Setup prettier? (y/N) · true

RUNNING TASKS
┌ Scaffold project
│  CREATE: ace
│  CREATE: app\Exceptions\Handler.ts
│  CREATE: commands\index.ts
│  CREATE: env.ts
│  CREATE: providers\AppProvider.ts
│  CREATE: public\favicon.ico
│  CREATE: resources\views\errors\not-found.edge
│  CREATE: resources\views\errors\server-error.edge
│  CREATE: resources\views\welcome.edge
│  CREATE: server.ts
│  CREATE: start\kernel.ts
│  CREATE: start\routes.ts
│  CREATE: .editorconfig
│  CREATE: .gitignore
│  CREATE: .adonisrc.json
│  CREATE: tsconfig.json
│  CREATE: .eslintrc.json, .eslintignore
│  CREATE: .prettierrc, .prettierignore
└ completed (143 ms)
┌ Install dependencies
│  [ wait ]  eslint, eslint-plugin-adonis, prettier, eslint-config-prettier, eslint-plugin-prettier, and 6 others (dev) .
│  [ wait ]  @adonisjs/core, @adonisjs/repl, @adonisjs/session, @adonisjs/view, proxy-addr, and 2 others (prod) ...
│  CREATE: package.json
└ completed (44 s)
┌ Configure installed packages
│  CREATE: config/app.ts
│  CREATE: config/static.ts
│  UPDATE: .adonisrc.json
│  CREATE: .env,.env.example
│  SKIP:   env.ts
│  CREATE: config\bodyparser.ts
│  CREATE: config\cors.ts
│  CREATE: config\hash.ts
│  CREATE: contracts\events.ts
│  CREATE: contracts\hash.ts
│  CREATE: contracts\env.ts
│  UPDATE: tsconfig.json
│  UPDATE: .adonisrc.json
│  UPDATE: .adonisrc.json 
│  [ error ]  Cannot invoke instructions. Missing package "@adonisjs/repl"
│      at Instructions.getPackagePath (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@adonisjs\sink\src\Tasks\Instructions\index.js:89:23)
│      at new Instructions (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@adonisjs\sink\src\Tasks\Instructions\index.js:48:33)
│      at task (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\create-adonis-ts-app\build\Tasks\ConfigurePackages\index.js:30:19)
│      at processTicksAndRejections (node:internal/process/task_queues:94:5)
│      at async Object.callback (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\create-adonis-ts-app\build\index.js:92:17)
│      at async TaskManager.runTask (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@poppinss\cliui\build\src\Task\Manager.js:99:13)
│      at async Object.complete (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@poppinss\cliui\build\src\Task\Manager.js:82:13)
│      at async Object.callback (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\create-adonis-ts-app\build\index.js:94:13)
│      at async TaskManager.runTask (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@poppinss\cliui\build\src\Task\Manager.js:99:13)
│      at async Object.complete (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@poppinss\cliui\build\src\Task\Manager.js:82:13)
│  [ error ]  Cannot invoke instructions. Missing package "@adonisjs/repl"
│      at Instructions.getPackagePath (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@adonisjs\sink\src\Tasks\Instructions\index.js:89:23)
│      at new Instructions (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@adonisjs\sink\src\Tasks\Instructions\index.js:48:33)
│      at task (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\create-adonis-ts-app\build\Tasks\ConfigurePackages\index.js:30:19)
│      at processTicksAndRejections (node:internal/process/task_queues:94:5)
│      at async Object.callback (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\create-adonis-ts-app\build\index.js:92:17)
│      at async TaskManager.runTask (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@poppinss\cliui\build\src\Task\Manager.js:99:13)
│      at async Object.complete (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@poppinss\cliui\build\src\Task\Manager.js:82:13)
│      at async Object.callback (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\create-adonis-ts-app\build\index.js:94:13)
│      at async TaskManager.runTask (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@poppinss\cliui\build\src\Task\Manager.js:99:13)
│      at async Object.complete (C:\Users\nauval achmad yusufa\AppData\Local\npm-cache\_npx\bb1111725132cbe5\node_modules\@poppinss\cliui\build\src\Task\Manager.js:82:13)
└ failed (230 ms)

[ error ]  Unable to create project. Cleaning up

**Comment by marcopestrin** [comment]
I have the same problem... node 14.5. Tried NPM and Yarn as well

**Comment by jeystaats** [comment]
> Same problem on MacOS. Node v14.17.4 - npm 7.24.2
> 
> ```js
> CUSTOMIZE PROJECT
> ❯ Select the project structure · api
> ❯ Enter the project name · hello-world
> ❯ Setup eslint? (y/N) · true
> ❯ Setup prettier? (y/N) · true
> 
> RUNNING TASKS
> ❯ Scaffold project 46 ms
> ❯ Install dependencies 1.56 s
>   npm install failed
> ❯ Configure installed packages
> 
> [ error ]  Unable to create project. Cleaning up
> ```
> 
> **I downgraded the npm package to 6.14.15 and it worked.**

I upgraded to a higher version. But the main issue seem to be something related to the node version if you have this issue.
