### ISSUE TITLE
[v5] socketio - This expression is not callable.   Type 'typeof import("/tmp/build_aa0e696b_/node_modules/socket.io/dist/index")' has no call signatures.

### ISSUE THREAD

**Issue by UtkuDalmaz** [adonisjs/core#2330]
Hi

I am a newbie on adonisjs. 
I followed everything here in https://preview.adonisjs.com/blog/socketio-with-adonisjs-v5

In Services/Ws.ts file I got

```
import socketIo from 'socket.io'
import Server from '@ioc:Adonis/Core/Server'

class Ws {
  public isReady = false
  public io: socketIo.Server

  public start (callback: (socket: socketIo.Socket) => void) {
    this.io = socketIo(Server.instance!, {
        cors: {
        origin: true,
        methods: ["GET", "POST", "PUT", "DELETE"],
        credentials: true
      }
    })
    this.io.on('connection', function() {
        console.log('check 2', callback);
      });
    this.isReady = true
  }
}

/**
 * This makes our service a singleton
 */
export default new Ws() 
```

I am having 

app/Services/Ws.ts:9:15 - error TS2349: This expression is not callable.
  Type 'typeof import("/tmp/build_aa0e696b_/node_modules/socket.io/dist/index")' has no call signatures.
9     this.io = socketIo(Server.instance!, {

When I deploy to heroku and also in vscode 

How can I fix this?

**Comment by UtkuDalmaz** [comment]
@thetutlage I can't get socketio work whatever I do. Can you please help me with that? Should I wait for the big release?

**Comment by RomainLanz** [comment]
Hey @UtkuDalmaz! 👋 

You probably installed `socket.io@3`, you need to install the version `2`. 
Nevertheless, this is not an issue with the framework.

**Comment by nlucis** [comment]
having the same issue on v 4.5.3 but with Koa + Typescript. Otherwise same exact setup as the configuration in the documentation using Express.
