### ISSUE TITLE
logger is not loaded into the application before running commands

### ISSUE THREAD

**Issue by targos** [adonisjs/core#2335]
## Package version
5.0.5-canary-rc-2

## Node.js and npm version
node 15.11.0
npm 7.6.0

## Sample Code (to reproduce the issue)
Contents of `commands/Test.ts`:

```ts
import { promisify } from 'util';

import { BaseCommand } from '@adonisjs/core/build/standalone';

const wait = promisify(setTimeout);

export default class Test extends BaseCommand {
  public static commandName = 'test';
  public static description = '';
  public static settings = {
    loadApp: true,
  };

  public async run() {
    setImmediate(() => {
      throw new Error('boom');
    });
    await wait(5000);
    this.logger.info('Hello world!');
  }
}
```

Reproduce with:

```console
$ node ace generate:manifest
$ node ace test
/Users/targos/git/project/node_modules/@adonisjs/core/build/src/Ignitor/SignalsListener/index.js:50
            this.application.logger.fatal(error, '"uncaughtException" detected. Process will shutdown');
                                    ^

TypeError: Cannot read property 'fatal' of undefined
    at process.<anonymous> (/Users/targos/git/project/node_modules/@adonisjs/core/build/src/Ignitor/SignalsListener/index.js:50:37)
    at Object.onceWrapper (node:events:485:26)
    at process.emit (node:events:378:20)
    at process.emit (/Users/targos/git/project/node_modules/source-map-support/source-map-support.js:495:21)
    at process._fatalException (node:internal/process/execution:163:25)
```

## Expected outcome
Log of the actual error (boom)

## Actual outcome
Internal error inside the uncaught exception handler, because `application.logger` doesn't exist.
https://github.com/adonisjs/core/blob/c5fbac40ef8a1c8df91a644373d633ad8daf6cf4/src/Ignitor/SignalsListener/index.ts#L48-L57

Note that the issue is a bit different without the `await wait(5000)`. In that case, the process ends without any visible error.

The same thing happens without `loadApp: true` in the settings.

**Comment by thetutlage** [comment]
Tried the same code with following package.json

```json
{
  "devDependencies": {
    "@adonisjs/assembler": "^4.0.1",
    "adonis-preset-ts": "^1.1.0",
    "eslint": "^7.17.0",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-adonis": "^1.0.15",
    "eslint-plugin-prettier": "^3.3.1",
    "pino-pretty": "^4.3.0",
    "prettier": "^2.2.1",
    "typescript": "^4.1.3",
    "youch": "^2.1.1",
    "youch-terminal": "^1.0.1"
  },
  "dependencies": {
    "@adonisjs/auth": "^6.0.1",
    "@adonisjs/core": "^5.0.5-canary-rc-2",
    "@adonisjs/lucid": "^11.0.1",
    "@adonisjs/mail": "^6.0.0",
    "@adonisjs/redis": "^6.0.3",
    "@adonisjs/repl": "^2.0.1",
    "@adonisjs/session": "^5.0.0",
    "@adonisjs/shield": "^5.0.0",
    "@adonisjs/view": "^4.0.0",
    "luxon": "^1.25.0",
    "pg": "^8.5.1",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
}
```

and got the following error

<img width="1070" alt="Screenshot 2021-03-04 at 7 47 19 PM" src="https://user-images.githubusercontent.com/1706381/109977069-70d06e00-7d22-11eb-952d-0618abe392b0.png">

**Comment by targos** [comment]
Damn, I don't know what's different in my setup. I have less adonisjs packages but the ones we have in common are at the same version.

**Comment by thetutlage** [comment]
Were you trying to customize something when you faced this error? Maybe the best option is to create a new app and try to reproduce with just one command

**Comment by targos** [comment]
I faced this error first while running the `invoke` command of one of my providers (a template file was missing from the npm tarball)

**Comment by targos** [comment]
Well, I deleted the package-lock, reinstalled the latest versions of subpackages and now it's working 🤷🏻

**Comment by thetutlage** [comment]
😎
