### ISSUE TITLE
Automatically resolving promises + autoloading all models to the controller

### ISSUE THREAD

**Issue by guledali** [adonisjs/core#2348]
I want to start out to say this great web framework in the fullstack-javascript ecosystem. Having played around with it today I think there are are small improvements that can be made that takes the overall dx to the next level.

Currently this is how the controller looks like
![Screenshot 2021-03-07 at 15 05 1](https://user-images.githubusercontent.com/20647282/110242762-c9d51780-7f57-11eb-9b82-092d9a6ebd7d.png).

They are two things that I don't like, for example having to explicitly import "post" model into "Posts" controller, I should have access to that model in the controller. Where else would have been using that model in?

A solution would be to have access to _"all models"_ in the controllers, so it does not matter if your are in the UsersController you should have access to a Postmodel if it exists or any other models that exists that's number 1.

Second, I dislike having to use `async` and `await`. The framework should be smart enough to resolve the promises for you, like it's the small details like such that are making the difference and reduces LOC.

This is the type of code that I like to see
![Screenshot 2021-03-07 at 15 03 1](https://user-images.githubusercontent.com/20647282/110243056-140ac880-7f59-11eb-959d-9bab311f2be5.png)

Even typing `"public"` keyword is too much too type here, everything should be public unless I explicitly specify it to be  a private method. 

<img width="771" alt="Screenshot 2021-03-07 at 15 31 39" src="https://user-images.githubusercontent.com/20647282/110243352-4832b900-7f5a-11eb-98bb-8078787f6b33.png">

The framework should make smarter assumptions here.

**Comment by thetutlage** [comment]
@guledali Thanks for the suggestions. Do you have any ideas around how to approch this or if you want to maybe develop a separate package to add this functionality

**Comment by guledali** [comment]
For example in the view you have the 

```javascript
     return view.render('tasks.index', { tasks })
```

`templatePath` and the `state` The state could potentially be a promise here, maybe wrap it in try and catch block. This is just some pseudo-code here


```javascript
try {
  await Promise.resolve(state));
} catch (error) {
  throw new Error(error)
}
```

**Comment by thetutlage** [comment]
Pseudo code will not help. I suggest doing some initial research and then come back with a proper proposal.

Closing the issue for now
