### ISSUE TITLE
REPL error: TypeError: Cannot set property 'history' of undefined

### ISSUE THREAD

**Issue by daanmlab** [adonisjs/core#2366]
`TypeError: Cannot set property 'history' of undefined

1 Repl._readHistoryFile
  .../.nvm/versions/node/v15.5.0/lib/node_modules/@adonisjs/cli/src/Commands/Repl/index.js:62

2 Repl.handle
  .../.nvm/versions/node/v15.5.0/lib/node_modules/@adonisjs/cli/src/Commands/Repl/index.js:109

3 anonymous
  .../back-end/node_modules/@adonisjs/ace/src/Command/index.js:565

4 Function.exec
  .../back-end/node_modules/@adonisjs/ace/src/Command/index.js:563

5 Function.commanderAction
  .../back-end/node_modules/@adonisjs/ace/src/Command/index.js:540

6 Command.listener
  .../back-end/node_modules/commander/index.js:315

7 Command.parseArgs
  .../back-end/node_modules/commander/index.js:651

8 Command.parse
  .../back-end/node_modules/commander/index.js:474

9 Kernel.invoke
  .../back-end/node_modules/@adonisjs/ace/src/Kernel/index.js:329

10 Ignitor._invokeAce
  .../back-end/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:532

11 Ignitor.fireAce
  .../back-end/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:847`

I'm working on an API I used the CLI to create it.
First time trying to start REPL.

System details:
OS: macos big sur 11.2.3
Shell: zsh

**Comment by RomainLanz** [comment]
Hey @daanmlab! 👋 

Could you be a bit more descriptive, there's no way for us to help you with the amount of information you shared.

**Comment by daanmlab** [comment]
> Hey @daanmlab! 👋
> 
> Could you be a bit more descriptive, there's no way for us to help you with the amount of information you shared.

Added some details. Sorry for being vague first time reporting an issue

**Comment by McSneaky** [comment]
> Added some details. Sorry for being vague first time reporting an issue

Can you share some code?

Most likely you have something like this:
```js
const user = await User.find(10)
user.history = 'foobar' // throws "Cannot set property 'history' of undefined" if user with ID 10 does not exist
```

**Comment by daanmlab** [comment]
just the be clear the code itself runs without any errors I only get an error when I try `adonis repl`

**Comment by daanmlab** [comment]
> > Added some details. Sorry for being vague first time reporting an issue
> 
> Can you share some code?
> 
> Most likely you have something like this:
> 
> ```js
> const user = await User.find(10)
> user.history = 'foobar' // throws "Cannot set property 'history' of undefined" if user with ID 10 does not exist
> ```

just the be clear the code itself runs without any errors I only get an error when I try `adonis repl`

**Comment by daanmlab** [comment]
could it be because of the big sur update @RomainLanz

**Comment by RomainLanz** [comment]
No, it's because the `rli.history` has been deprecated and removed.

Please, downgrade your Node version for now if you want to use Adonis 4.
Closing since we already have an issue on same https://github.com/adonisjs/adonis-cli/issues/190

**Comment by daanmlab** [comment]
okay thanks for letting me know

**Comment by poldfcb** [comment]
a momentary fix is that you can comment the next two lines, and the repl will be ok. (ofcs you'll not be able to get the history of your repl)
comment the line 109 y 110
![imagen](https://user-images.githubusercontent.com/39310780/124832712-b1dfc580-df42-11eb-962d-904b138eacbf.png)
