### ISSUE TITLE
VIM Edge Syntax Highlighting

### ISSUE THREAD

**Issue by oscarmorrison** [adonisjs/core#2399]
- [x] Do you have the complete context of the feature and how it should be implemented?
- [x] Do you have a clear understanding of the final outcome?
- [ ] Will you be available to work on the feature?
- [x] Can you write the necessary documentation for the feature?

## Why this feature is required (specific use-cases will be appreciated)?
For uses of VIM

Can you please build a VIM syntax plugin for .edge. Thanks!

**Comment by jmmendivil** [comment]
https://github.com/watzon/vim-edge-template

**Comment by oscarmorrison** [comment]
Closed by https://github.com/adonisjs/docs/pull/421#issuecomment-803598365
