### ISSUE TITLE
Config AdonisJS on RunCloud Native Nginx Custom Config

### ISSUE THREAD

**Issue by jacow** [adonisjs/core#2404]
Is there a documentation or link reference to setup adonisjs on native nginx web server ? Now i'm using runcloud control panel, and it's quite confusing how to make it works. Is there any of you can help me ?

Thank you

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
