### ISSUE TITLE
@poppinss/utils seems to be broken with node 12

### ISSUE THREAD

**Issue by ad-on-is** [adonisjs/core#2410]
Could it be that @poppinss/utils 3.0.5 doesn't work with node 12 anymore?

Due to a new setup, I have node 12 installed, while previously working on node 15. 
I have 2 adonisjs projects, one is older with `@poppinss/utils 2.5.10` and newer one with `@poppinss/utils 3.0.5`

Running `node ace` with poppins 2.5.10 wokrs as expected

However, running `node ace` with poppins 3.0.5 gives me the following error:

```
/home/user/Node/myproject/node_modules/@poppinss/utils/build/src/Helpers/string.js:241
        return `${values[0]}${options?.pairSeparator || ' and '}${values[1]}`;


                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/Node/myproject/node_modules/@poppinss/utils/build/src/Helpers/index.js:56:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

I also tried to rule out that it has something to do with my project itself, and wanted to create a new adonis v5 project with `npm init adonis-ts-app adonis5testsetup` and this produces the following error

```
CUSTOMIZE PROJECT
❯ Select the project structure · api
❯ Enter the project name · adonis5testsetup
❯ Setup eslint? (y/N) · true
❯ Setup prettier? (y/N) · true

RUNNING TASKS
❯ Scaffold project 41 ms
❯ Install dependencies 17 s
❯ Configure installed packages 14 ms
  Unexpected token '.'

[ error ]  Unable to create project. Cleaning up
```

UPDATE: just installed `fnm` to try different versions, and it seems to be broken with node 13 too.

**Comment by thetutlage** [comment]
Yup, most recent version targets Node 14.5.4 and above

**Comment by dcenatiempo** [comment]
AWS Elastic Beanstalk only supports Node 12...

**Comment by thetutlage** [comment]
Can you please share the `package.json` and `package-lock.json` files. The `5.0.4-preview-rc-2.1 ` shouldn't be using the latest version of `@poppinss/utils`.

**Comment by dcenatiempo** [comment]
@thetutlage You are correct.

I was just stating that I believe `5.0.4-preview-rc-2.1` is the last Node 12 compatible version for those in the future who may be having this same issue.

I believe Node 14 is required for `v5.0.5-canary-rc-1` and up.

**Comment by thetutlage** [comment]
Yes, with the latest releases, we are targeting Node.js LTS version and up.  I am checking here https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.nodejs and it looks like Node 14 is supported by AWS Elastic Beanstalk (maybe I am looking at the wrong thing)

**Comment by mehmetcavus** [comment]
@thetutlage I get the same error using node v12.21.0 with the package.json below. It was working fine until I re-install node modules. I stucked here, not able to run project: `node ace serve --watch`. 

Also: upgrading to node v14.x is not an option at the moment because of reactjs and storybook requirements.

```
{
  "name": "api",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build --production",
    "start": "node server.js",
    "dev": "node ace serve --watch >> _logs/app.log",
    "lint": "eslint . --ext=.ts",
    "format": "prettier --write .",
    "start_scheduler": "node start/scheduler",
    "predev": "mkdir -p _logs"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^3.1.1",
    "adonis-preset-ts": "^1.1.0",
    "eslint": "^7.20.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-adonis": "^1.2.1",
    "eslint-plugin-prettier": "^3.3.1",
    "pino-pretty": "^4.5.0",
    "prettier": "^2.2.1",
    "youch": "^2.1.1",
    "youch-terminal": "^1.0.1"
  },
  "dependencies": {
    "@adonisjs/application": "^3.0.0",
    "@adonisjs/auth": "^5.1.1",
    "@adonisjs/core": "^5.0.4-preview-rc-2.1",
    "@adonisjs/lucid": "^10.0.0",
    "@adonisjs/repl": "^1.1.6",
    "adonis5-scheduler": "^1.0.1",
    "camelcase": "^6.2.0",
    "influx": "^5.7.0",
    "ldapjs": "^2.2.3",
    "lodash": "^4.17.21",
    "luxon": "^1.26.0",
    "neo4j-driver": "^4.2.2",
    "p-map": "^4.0.0",
    "pg": "^8.5.1",
    "phc-argon2": "^1.1.0",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "typescript": "~4.1",
    "uuid": "^8.3.2"
  }
}
```

**Comment by vookio** [comment]
@thetutlage I get the same error using node v12.21.0 with the package.json below. It was working fine until I re-install node modules. I stucked here, not able to run project: `node ace serve --watch`. 

Also: upgrading to node v14.x is not an option at the moment because of reactjs and storybook requirements.

```
{
  "name": "api",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build --production",
    "start": "node server.js",
    "dev": "node ace serve --watch >> _logs/app.log",
    "lint": "eslint . --ext=.ts",
    "format": "prettier --write .",
    "start_scheduler": "node start/scheduler",
    "predev": "mkdir -p _logs"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^3.1.1",
    "adonis-preset-ts": "^1.1.0",
    "eslint": "^7.20.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-adonis": "^1.2.1",
    "eslint-plugin-prettier": "^3.3.1",
    "pino-pretty": "^4.5.0",
    "prettier": "^2.2.1",
    "youch": "^2.1.1",
    "youch-terminal": "^1.0.1"
  },
  "dependencies": {
    "@adonisjs/application": "^3.0.0",
    "@adonisjs/auth": "^5.1.1",
    "@adonisjs/core": "^5.0.4-preview-rc-2.1",
    "@adonisjs/lucid": "^10.0.0",
    "@adonisjs/repl": "^1.1.6",
    "adonis5-scheduler": "^1.0.1",
    "camelcase": "^6.2.0",
    "influx": "^5.7.0",
    "ldapjs": "^2.2.3",
    "lodash": "^4.17.21",
    "luxon": "^1.26.0",
    "neo4j-driver": "^4.2.2",
    "p-map": "^4.0.0",
    "pg": "^8.5.1",
    "phc-argon2": "^1.1.0",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "typescript": "~4.1",
    "uuid": "^8.3.2"
  }
}
```

**Comment by thetutlage** [comment]
Have already mentioned. Please upgrade the Node version. React should move to atleast the LTS of Node, which is 14.15.x.

Or you can run different version for the React and different for AdonisJS. There are tools like Nvm and Volta, which allows this

**Comment by vookio** [comment]
> Can you please share the `package.json` and `package-lock.json` files. The `5.0.4-preview-rc-2.1 ` shouldn't be using the latest version of `@poppinss/utils`.

I was trying to make it work again because of this response since I am using `5.0.4-preview-rc-2.1` as well. Thanks.

**Comment by shiva2021** [comment]
Hi @thetutlage , I am currently running into this issue during the deployment stage when the cloud foundry server tries to start the Adonis 5 application. Here's the error:


![image](https://user-images.githubusercontent.com/46091211/125939749-74e2a581-ec2c-49ae-90ba-01e911449ad3.png)


My node version 14.17.3 and npm is 6.14.13. I am really confused where I went wrong. Here's my package.json

![image](https://user-images.githubusercontent.com/46091211/125940304-d3d66cd9-c0c8-4261-b135-0d38f7690319.png)

**Comment by RomainLanz** [comment]
@shiva2021, your server is running a very old version of Node.js, please upgrade.

**Comment by shiva2021** [comment]
Hi @RomainLanz , thanks for your response. 
So, just to be clear, are you talking about the node.js version that docker picks up to create the image? The docker is creating an image with the latest node.js version now after I made some configuration changes and I am getting the same error. Here's the screenshot:

![image](https://user-images.githubusercontent.com/46091211/125955417-99896a36-3154-4ffa-a627-c1391c5ee2eb.png)

**Comment by RomainLanz** [comment]
Yes, the error message appears because the version of Node.js you are using (the service that runs your code) does not know about the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

It was added in Node.js 14. So it seems your application is running under a lower version of Node.js despite the container having version 16.5.0. 🤔

**Comment by shiva2021** [comment]
> Yes, the error message appears because the version of Node.js you are using (the service that runs your code) does not know about the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).
> 
> It was added in Node.js 14. So it seems your application is running under a lower version of Node.js despite the container having version 16.5.0. 🤔

This really helps. Let me check with the team that is responsible for managing this. Will get back to you soon. Thanks again

**Comment by aslampatel** [comment]
I have used the latest node js and latest code but got the same error when deployed in the server.

**Comment by shiva2021** [comment]
Specify the engine in package.json file. That fixed this issue for me

```
{
  "engines": {
    "node": "< latest version preferably 14 as per docs>"
  }
}
```

Hope this helps.

**Comment by aslampatel** [comment]
> 

i am using  latest node js v17 in both local and server but same thing happen

**Comment by shiva2021** [comment]
Please try using NodeJs LTS version i.e. 16.13.1
