### ISSUE TITLE
Creating a new Adonis API Server resolves to a BUG

### ISSUE THREAD

**Issue by Kaperskyguru** [adonisjs/core#2421]
## Package version
Adonisjs ^5.0.4-preview-rc

## Node.js and npm version
Node 14.15.0 and npm 7.6.1

## Sample Code (to reproduce the issue)
yarn create adonis-ts-app ticketing-system-adonisjs 

## Expected outcome
After creating and running the Dev server, I expected everything to work as normal.

## Actual outcome
I got an error during running the dev server with `node ace serve --watch` saying:
```IocLookupException: E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Core/BodyParserMiddleware" namespace from the IoC Container```

## BONUS (a sample repo to reproduce the issue)
https://github.com/Kaperskyguru/ticketing-system-adonisjs

**Comment by guemidiborhane** [comment]
+1

**Comment by thetutlage** [comment]
I recommend create the app again, it should be good.

**Comment by Kaperskyguru** [comment]
OK.. Fixed now. Though I haven’t tested the Web Application server only API Server now.

**Comment by thetutlage** [comment]
Should be good for both. Was a intermediate issue as we are releasing new packages for the main release

**Comment by guemidiborhane** [comment]
Working. Thanks for the quick response
