### ISSUE TITLE
Testing Adonisjs on Postman throws an error.

### ISSUE THREAD

**Issue by Kaperskyguru** [adonisjs/core#2430]
## Package version
"@adonisjs/core": "~5.0.4-preview-rc"

## Node.js and npm version
Node v14.15.0 and npm 7.6.1

## Sample Code (to reproduce the issue)
https://github.com/Kaperskyguru/ticketing-system-adonisjs

## Expected outcome
To work normally

## Actual outcome
[1616837103931] ERROR: Cannot find module 'phc-argon2'

## BONUS (a sample repo to reproduce the issue)
https://github.com/Kaperskyguru/ticketing-system-adonisjs
The hack to this issue to run `phc install phc-argon2`

**Comment by RomainLanz** [comment]
Hey @Kaperskyguru! 👋 

The error is clear, you need to install `phc-argon2`.

```bash
npm install phc-argon2
```
