### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined (leven)

### ISSUE THREAD

**Issue by e-e** [adonisjs/core#2445]
This happened after downgrading to adonis/core version ~5.0.4-preview-rc-2.1 due to the BodyParser IoC error.

## Package version
package.json:
```json
{
  "name": "app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build --production",
    "start": "node server.js",
    "dev": "node ace serve --watch",
    "lint": "eslint . --ext=.ts",
    "format": "prettier --write .",
    "test": "NODE_ENV=testing node -r @adonisjs/assembler/build/register japaFile.ts"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^3.0.6",
    "@types/jsdom": "^16.2.9",
    "@types/supertest": "^2.0.10",
    "adonis-preset-ts": "^2.1.0",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-adonis": "^1.3.0",
    "eslint-plugin-prettier": "^3.3.1",
    "execa": "^5.0.0",
    "get-port": "^5.1.1",
    "japa": "^3.1.1",
    "jsdom": "^16.5.1",
    "pino-pretty": "^4.7.1",
    "prettier": "^2.2.1",
    "sqlite3": "^5.0.2",
    "supertest": "^6.1.3",
    "typescript": "^4.1.5",
    "youch": "^2.2.0",
    "youch-terminal": "^1.1.0"
  },
  "dependencies": {
    "@adonisjs/auth": "^5.1.1",
    "@adonisjs/core": "~5.0.4-preview-rc-2.1",
    "@adonisjs/lucid": "^10.0.0",
    "@adonisjs/redis": "^5.0.9",
    "@adonisjs/repl": "^1.1.6",
    "@adonisjs/session": "^4.0.6",
    "@adonisjs/shield": "^4.0.3",
    "@adonisjs/view": "^3.1.0",
    "firebase": "^8.3.1",
    "firebase-admin": "^9.5.0",
    "luxon": "^1.26.0",
    "pg": "^8.5.1",
    "phc-bcrypt": "^1.0.6",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
}
```

## Node.js and npm version
Node: v14.8.0
npm: 6.14.7

## Sample Code (to reproduce the issue)
`node ace migration:run`

## Expected outcome
Migrations should be run

## Actual outcome
```
TypeError: Cannot read property 'length' of undefined


1 leven
  /app/node_modules/leven/index.js:14

2 anonymous
  /app/node_modules/@adonisjs/ace/build/src/Kernel/index.js:298

3 Kernel.getSuggestions
  /app/node_modules/@adonisjs/ace/build/src/Kernel/index.js:297

4 Kernel.execMain
  /app/node_modules/@adonisjs/ace/build/src/Kernel/index.js:169

5 Kernel.handle
  /app/node_modules/@adonisjs/ace/build/src/Kernel/index.js:477

6 App.handle
  /app/node_modules/@adonisjs/core/build/src/Ignitor/Ace/App/index.js:286

7 Ace.handle
  /app/node_modules/@adonisjs/core/build/src/Ignitor/Ace/index.js:33
```

**Comment by e-e** [comment]
Also happens when running `node ace` without any commands, which used to generate the same output as `node ace --help`

**Comment by e-e** [comment]
@thetutlage @RomainLanz sorry for the direct ping, but any ideas? is there something wrong with my `package.json` versions? is there an update to when the v5 stable, non-preview version will be released?

**Comment by thetutlage** [comment]
Already  mentioned in Discussions that one should not blindly update all the dependencies unless there is a documented release. Please do not create new issues and check existing discussions. It creates unnecessary work for us

**Comment by e-e** [comment]
I did not "blindly" update packages. I changed my node version, which introduced the error as explained in [this discussion](https://github.com/adonisjs/core/discussions/2424). Notice how [I posted a question that went unanswered](https://github.com/adonisjs/core/discussions/2424#discussioncomment-567205). I also posted multiple times in Discord, also unanswered.

**Comment by mcordoba** [comment]
I had the same problem and I fixed it with this:

- Delete ace-manifest.json from the root folder
- Now, node ace will work but you will have some commands missing. If you execute, node ace make:command Test the ace manifest will be recreated.
- Now you can execute node ace and you will have all your commands available.
