### ISSUE TITLE
Feature Request: Automatic Routing

### ISSUE THREAD

**Issue by D-Marc1** [adonisjs/core#2450]
Please consider answering the following questions before opening the issue:

- [ ] Do you have the complete context of the feature and how it should be implemented?
Just a rough idea. I really enjoyed the automatic routing in Nuxt and thought it would be great to have for Adonis. It could follow some sort of pattern as well.
- [x] Do you have a clear understanding of the final outcome?
Yes, automatic routing.
- [ ] Will you be available to work on the feature?
I'd consider it, without guarantees, as it's dependent on how much free time I have.
- [ ] Can you write the necessary documentation for the feature?

## Why this feature is required (specific use-cases will be appreciated)?

It would save a lot of time to have to do tons of boilerplate code.

## Have you tried any other work arounds?

No.

**Comment by thetutlage** [comment]
No sure what exactly the proposal is. It has to be drafted into an RFC, before we can consider it
