### ISSUE TITLE
Version 4.1 documentation is now missing

### ISSUE THREAD

**Issue by rosnaib11** [adonisjs/core#2550]
Where is the version 4.1 documentation for old version?

**Comment by RomainLanz** [comment]
Hey @rosnaib11! 👋 

It is written in the first paragraph of the [release post](https://docs.adonisjs.com/releases/out-of-preview).
➡️ https://legacy.adonisjs.com/

**Comment by rosnaib11** [comment]
> Hey @rosnaib11! 👋
> 
> It is written in the first paragraph of the [release post](https://docs.adonisjs.com/releases/out-of-preview).
> ➡️ https://legacy.adonisjs.com/

Oh thanks
