### ISSUE TITLE
Property 'auth' does not exist on type 'HttpContextContract'.

### ISSUE THREAD

**Issue by shunnmugam** [adonisjs/core#2555]
I'm using adonis 5.0
 
 Not able to include auth object in controller, got following error in contracts/auth.ts
 
 Invalid module name in augmentation, module '@ioc:Adonis/Addons/Auth' cannot be found.

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
