### ISSUE TITLE
Cannot call adonis env on ace custom command

### ISSUE THREAD

**Issue by hengkydev** [adonisjs/core#2560]
i want to replicate my current project from adonis v4 to v5 
when i try to get my `.env` value from my custom  `ace command`
i got :  
`E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Core/Env" namespace from the IoC Container` 
but its running well on `node ace repl'`

## Package version
`@adonisjs/core": "^5.1.6`

## Node.js and npm version
- **nodejs** : 14.15.1
- **npm** : 6.14.8

## Sample Code (to reproduce the issue)

```ts
import Env from '@ioc:Adonis/Core/Env'
import { BaseCommand } from '@adonisjs/core/build/standalone'

export default class Test extends BaseCommand {

  public static commandName = 'test'
  public static description = ''

  public static settings = {
    loadApp: false,
    stayAlive: false,
  }

  public async run () {
    this.logger.info(Env.get('NODE_ENV'))
  }
}
```

## Expected outcome

showing my .env value "development" like adonis v4

## Actual outcome

`E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Core/Env" namespace from the IoC Container`

**Comment by hengkydev** [comment]
trying to resolve this by adding 
`require('dotenv').config()`

in `ace` file

```js
require('dotenv').config()
require('reflect-metadata')
require('source-map-support').install({ handleUncaughtExceptions: false })

const { Ignitor } = require('@adonisjs/core/build/standalone')
new Ignitor(__dirname)
  .ace()
  .handle(process.argv.slice(2))
```

**Comment by jaysson** [comment]
I am unable to import it even inline.
```ts
public async run() {
  const { default: Env } = await import('@ioc:Adonis/Core/Env')
}
```
throws
```sh
IocLookupException: E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Core/Env" namespace from the IoC Container

```

**Comment by benwoodward** [comment]
> I am unable to import it even inline.
> 
> ```ts
> public async run() {
>   const { default: Env } = await import('@ioc:Adonis/Core/Env')
> }
> ```
> 
> throws
> 
> ```shell
> IocLookupException: E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Core/Env" namespace from the IoC Container
> ```

did you find a solution to this?

**Comment by benwoodward** [comment]
> I am unable to import it even inline.
> 
> ```ts
> public async run() {
>   const { default: Env } = await import('@ioc:Adonis/Core/Env')
> }
> ```
> 
> throws
> 
> ```shell
> IocLookupException: E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Core/Env" namespace from the IoC Container
> ```

you need to set `loadApp: true` so the modules are available to import
