### ISSUE TITLE
Gives us back the Docs for for Version 4.x 

### ISSUE THREAD

**Issue by simonjcarr** [adonisjs/core#2569]
Version 4 docs are no longer available. All links including those on https://adonisjs.com/docs/4.1/ take you to the V5 home page. The documentation link from that page takes you to V5 Docs. 

If this is intentional, it is a really bad move, as it kicks dirt in the face of those who have supported Adonis up to this point and still have 4.x systems in production.

**Comment by simonjcarr** [comment]
Just found the V4.x docs in GitHub, it should be made more clear on the new Web Site where to find these, as all links on google that are relevant to V4.x now take you to the V5 home page. It's very confusing

**Comment by simonjcarr** [comment]
So is having Twitter now a pre requisite to using Adonis?

**Comment by thetutlage** [comment]
Its weird that people who doesn't care to read the release blog post tells what others should do

**Comment by thetutlage** [comment]
There is no pre requisite. You are free not even use Adonis at all. There is no need to loose patience and build a habit of reading

**Comment by simonjcarr** [comment]
Would it not make sense to put a message on the page that you have forwarded all traffic to where to find docs for the link they just clicked on
