### ISSUE TITLE
In Installation: When trying to choose web directory structure arrow keys are not working in Git Bash CLI

### ISSUE THREAD

**Issue by danish505** [adonisjs/core#2574]
The Github issues in AdonisJS are reserved for reporting confirmed bugs. If you open an issue that **does not conform to the requirements**, it will be closed immediately.

For usage questions, please use the following resources:

- Read the [docs](https://preview.adonisjs.com/guides/quick-start)
- Ask your question on [Discord](https://discord.gg/vDcEjq6?)
- Ask your question in [Github discussions forum](https://github.com/adonisjs/core/discussions)
- Try searching existing discussion threads or issues.

*Delete the above section and the instructions in the sections below before submitting*

## Package version
npm 6.14.11
## Node.js and npm version
14.16.0

## Sample Code (to reproduce the issue)
npm init adonis-ts-app@latest hello-world

## Expected outcome
should select directory structure

## Actual outcome
Arrow keys not working

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
