### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by mahdi2k1** [adonisjs/core#2576]
sudo npm init adonis-ts-app blog --verbose

npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'init',
npm verb cli   'adonis-ts-app',
npm verb cli   'blog',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.11.2
npm info using node@v16.1.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 0ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/home/mahdi/.npmrc Completed in 0ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:/root/.npmrc Completed in 0ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 5ms
npm timing npm:load:configload Completed in 5ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 1ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 13ms
npm timing config:load:flatten Completed in 2ms
npm http fetch GET 304 https://registry.npmjs.org/create-adonis-ts-app 5579ms (from cache)
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 0ms
sh: 1: create-adonis-ts-app: Permission denied
npm timing command:init Completed in 5762ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:365:28)
npm verb stack     at maybeClose (node:internal/child_process:1067:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb cwd /home/mahdi
npm verb Linux 5.8.0-50-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "init" "adonis-ts-app" "blog" "--verbose"
npm verb node v16.1.0
npm verb npm  v7.11.2
npm ERR! code 127
npm ERR! path /home/mahdi
npm ERR! command failed
npm ERR! command sh -c create-adonis-ts-app "blog"
npm verb exit 127
npm timing npm Completed in 6009ms
npm verb code 127

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-08T09_00_54_861Z-debug.log

**Comment by RomainLanz** [comment]
Hey @mahdi2k1! 👋 

You should never use `sudo` with an `npm` command.
You must have installed `Node.js` and `npm` [in a wrong way](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally), nothing related to AdonisJS.

**Comment by mahdi2k1** [comment]
When to use js?
