### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by swapnilnandgave** [adonisjs/core#2601]
Adonis is awesome and I am always excited to work on this. I wanted to understand one thing from you to api versioning. Is there any standard way to maintain api versioning

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
