### ISSUE TITLE
How to validate an integer number in validation class?

### ISSUE THREAD

**Issue by linhchelsea** [adonisjs/core#2612]
I read the validation types and rules document but I can not find the exactly solution?

Thank you so much

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
