### ISSUE TITLE
Adonis v5 docker don't live reload

### ISSUE THREAD

**Issue by GabrielGomesBarbosa** [adonisjs/core#2622]
I created a new project api using the comand `npm init adonis-ts-app@latest <my-project-name>` and i tryng to dockerize it using docker compose, i created a container for it, but the live reload don't working, i always need to create a new container to see the difference.

I need help to understand what's going wrong, i'm using docker toolbox in my windows 10, bellow is my docker informations:

Docker version: `Docker version 19.03.1, build 74b1e89e8a`
Docker compose version:  `docker-compose version 1.24.1, build 4667896b`

**Dockerfile**

```
FROM node:14.17-alpine

WORKDIR /usr/app

COPY . .

RUN npm install

EXPOSE 3333

# Run with npm
# CMD ["npm", "run", "dev"]

# Run with node ace
CMD ["node", "ace", "serve", "--watch"]
```

**docker-compose.yml**

```
version: "3"

services:
  app:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
```

**.dockerignore**

```
node_modules
```

I just need create a new project, i dind't edit any files, just tried use docker on that, bellow my project information:

**package.json**

```
{
  "name": "adonisdocker",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build --production",
    "start": "node server.js",
    "dev": "node ace serve --watch",
    "lint": "eslint . --ext=.ts"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^5.2.0",
    "adonis-preset-ts": "^2.1.0",
    "eslint": "^7.26.0",
    "eslint-plugin-adonis": "^1.3.1",
    "pino-pretty": "^4.8.0",
    "typescript": "^4.2.4",
    "youch": "^2.2.2",
    "youch-terminal": "^1.1.1"
  },
  "dependencies": {
    "@adonisjs/core": "^5.1.6",
    "@adonisjs/repl": "^3.1.2",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
}
```

After i have created the `Dockerfile`, `.dockerignore` and `docker-compose.yml` on my root folder, i just run:

`docker-compose up`

See bellow the result:

```
Creating network "adonisdocker_default" with the default driver
Building app
Step 1/6 : FROM node:14.17-alpine
 ---> 8e69714aa82b
Step 2/6 : WORKDIR /usr/app
 ---> Running in c1ce30fbde57
Removing intermediate container c1ce30fbde57
 ---> 29a375a59756 
Step 3/6 : COPY . .
 ---> 7791f5e2ddc4
Step 4/6 : RUN npm install
 ---> Running in 9ccc3342a435
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 606 packages from 371 contributors and audited 608 packages in 15.89s

62 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Removing intermediate container 9ccc3342a435
 ---> ecff8edf9c63
Step 5/6 : EXPOSE 3333
 ---> Running in f3e1deccf63d
Removing intermediate container f3e1deccf63d
 ---> 14d678efe9f0
Step 6/6 : CMD ["npm", "run", "dev"]
 ---> Running in 81d052af4150
Removing intermediate container 81d052af4150
 ---> d704b84d3f1e
Successfully built d704b84d3f1e
Successfully tagged adonisdocker_app:latest
WARNING: Image for service app was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating adonisdocker_app_1 ... done
Attaching to adonisdocker_app_1
app_1  | 
app_1  | > adonisdocker@1.0.0 dev /usr/app
app_1  | > node ace serve --watch
app_1  |
app_1  | [ info ]  building project...
app_1  | [ info ]  starting http server...
app_1  | [1621109520442] INFO (adonisdocker/28 on 2771bc004cf5): started server on 0.0.0.0:3333
app_1  | [ info ]  watching file system for changes
```

When i open in the browser its works fine

![image](https://user-images.githubusercontent.com/37483241/118376870-fe410180-b5a0-11eb-97c9-b37edd39d91b.png)

But when i edit the `routes.ts` file the console output on VSCode don't change, and consequently the application don't update too.

**Important:** I create a project of type api

**Comment by RomainLanz** [comment]
Hey @GabrielGomesBarbosa! 👋 

It is because you are running inside your Docker Container, and you are editing the file inside the host.
It is not reflected in your Container.

This is not related to AdonisJS. It is an issue with your Docker setup.
I would recommend creating a thread inside [GitHub Discussions ](https://github.com/adonisjs/core/discussions) to have an answer.

**Comment by SG-TEAM** [comment]
Same issue, config is fine
In docker mode must be set pooling mode of chokidar package

Just set this variable before run `node ace serve --watch`
CHOKIDAR_USEPOLLING=1

and another variable for min CPU usage
CHOKIDAR_INTERVAL=2000

**Comment by gustavonikov** [comment]
@RomainLanz Same issue here, you said that doesnt reflects the updates made inside the local project on docker container, right? I tested and here the updates made in both cases reflects (modifying local reflects on container and vice versa). And even if I modify directly inside docker container, still doesnt do nothing. Can you help me? :) My setup is similar to what is in the issue.

**Comment by bartosjiri** [comment]
@gustavonikov Here's my config with working hot-reloading:

#### ./api/Dockerfile
```
FROM node:14.17.0-alpine AS base

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
ENV HOST=0.0.0.0
ENV PORT=3000

FROM base AS dev
ENV CHOKIDAR_USEPOLLING=true
ENV NODE_ENV=development
CMD ["node", "ace", "serve", "--watch"]
```

#### ./docker-compose(.dev).yml
```yml
version: "3.7"
// ..
services:
  // ...
  api:
    // ...
    build: 
      context: "./api"
      target: dev
    restart: unless-stopped
    volumes: 
      - "./api/:/usr/src/app/"
      - "/usr/src/app/node_modules"
      - "/usr/src/app/build"
    expose:
      - 3000
```

*(Adonis source code is located in the `./api` folder, as defined in the docker-compose's build context)*

**Comment by gustavonikov** [comment]
@bartosjiri Hey, man, gonna take a look to see if works, thank you :)

**Comment by gustavonikov** [comment]
@bartosjiri Dude, it worked, I only add to the docker-compose file the `restart: unless-stopped` and the `ENV CHOKIDAR_USEPOLLING=true` to Dockerfile :D, thanks a lot!

**Comment by eduardylopes** [comment]
@bartosjiri Thaks dude, it worked! Careful with environment variable "CHOKIDAR_USEPOLLING=true" make sure that is in use by the container/image. To inspect and verify if env variable is really there use de command "docker inspect <containerId>" and find env.

adonis,docker,docker-compose,hot-reload,reflect,vscode,reload,watch,save.

**Comment by Michael-Purtill** [comment]
I ran into this issue and it turned out the cause was due to the fact that I wasn't mapping port 24678 in my compose file.

so, ensure you map 24678:24678 in your compose file, for example:

ports:
      - 3333:3333
      - 24678:24678
