### ISSUE TITLE
Adonisjs last update (v5) model create command Not working

### ISSUE THREAD

**Issue by mdjamilaj** [adonisjs/core#2640]
Adonisjs v5

Create a controller command work fine.
`
node ace make:controller Posts`
But Create a new model Command not working

`node ace:make model Post`
Run the make model command show error

_**Cannot find module 'C:\Users\abir2\Desktop\crm-backend\ace:make'**_

adonisjs v5 How to create a model using command?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by RomainLanz** [comment]
There is nothing to fix when you make a typo typing a command.

**Comment by andu99** [comment]
I create a new porject, `node ace make:controller Posts`, it's ok, `node ace:make model Post`, 
it return :
`
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'D:\adonisjs\two\ace:make'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
`
I delete the node_modules，`npm install` again, `node ace:make model Post` , it throw the above wrong msg.

**Comment by RomainLanz** [comment]
Because you have a typo in your command....
As state in the documentation, we expect you to have common knowledge of Node.js before starting to use AdonisJS.

You must know that `node ace` will execute the file `ace` with Node. I don't know what you expect with `node ace:make`.

**Comment by curious-monggo** [comment]
oh oh
It was this one: https://docs.adonisjs.com/guides/database/introduction
So we made it optional, pretty cool! (lightweight and unopinionated db setup)

Now they're back hohoho. Was panicking there for a good 10mins
![image](https://user-images.githubusercontent.com/25073775/137489273-371796f8-5b45-4fb0-9993-873a01c92db4.png)

Now... This got me thinking,. Maybe I should start uploading adonisjs content to YT

Many thanks, @RomainLanz!
