### ISSUE TITLE
no exported member named 'validate'

### ISSUE THREAD

**Issue by swapnilnandgave** [adonisjs/core#2689]
## Package version
App version: 1.0.0 
Framework version: 5.1.6
Assembler version: 5.1.1 

## Node.js and npm version
v14.15.4 and 6.14.10

## Sample Code (to reproduce the issue)
`import { schema, rules, validate } from '@ioc:Adonis/Core/Validator'`

I am getting below error message
`'"@ioc:Adonis/Core/Validator"' has no exported member named 'validate'. Did you mean 'ValidateFn'?`

![Screenshot 2021-05-28 at 9 35 20 AM](https://user-images.githubusercontent.com/1922846/119928019-52cc7f80-bf98-11eb-9147-55f2f177abb7.png)

**Comment by yugalkishoregoyal** [comment]
@swapnilnandgave 
It seems to be a typo in the docs.
You can get the `validator` object instead of `validate` and use it as `validator.validate()`, everything should work fine.

**Comment by thetutlage** [comment]
Fixed docs

**Comment by swapnilnandgave** [comment]
How can we identify whether validator failed or succeed. Currently it is promise returning type and it looks no validation.fails() method in it? Is there any available method to identify whether validator.validate failed or succeed
