### ISSUE TITLE
Need Independent Auth Object

### ISSUE THREAD

**Issue by yugalkishoregoyal** [adonisjs/core#2690]
Hi Team,
We need to access the Auth object, not only from the HttpContext (_ctx) object but as a separately exported object that can be used in any controller or Model Method. 

Ex: If I want to add a user_id field in every post created by a specific user, I should use the Auth Object and use the same in the beforeSave hook in the Model. Currently, I need to do the same in the controller, and that's not a very clean code.

## Why this feature is required (specific use-cases will be appreciated)?
To write the clean and organized code.

## Have you tried any other work arounds?
No workarounds seem to work.

## Are you willing to work on it with little guidance?
Yes

**Comment by thetutlage** [comment]
Do you have a proposal on how to implement it?

**Comment by yugalkishoregoyal** [comment]
If any way we can make the auth object global for the current request lifecycle. I believe the `Bouncer` module already have the access to the logged-in user out of the actual controller method. 
<img width="669" alt="Screenshot 2021-05-28 at 1 15 48 PM" src="https://user-images.githubusercontent.com/12165538/119948864-e7de7100-bfb6-11eb-8557-a8e94ef9fc97.png">

**Comment by thetutlage** [comment]
Bouncer has access to the auth object from the `ctx` itself. There is no global per-request object. I suggest you to open an issue with a concrete proposal (if you think this is possible), otherwise you are just delegating the research on us.
