### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by babakfp** [adonisjs/core#2699]
Hello
If you just try to search Adonis repo in Github, you are not going to be able to find it. Github primarily looks for the repo name. This repo name is "core" so that why you can't find it from the Github search. I was able to find the repo URL from the [site](https://adonisjs.com/).
I hope you'll be able to create this framework as you want and ill be able to enjoy it😁. As you said, there is no something like Laravel for the NodeJS so, I'm waiting for greater results♥.

**Comment by RomainLanz** [comment]
Hey @babakfp! 👋 

If you search `adonisjs` in the search bar you will find the organization, which is more than enough to find the repository you want to search for.

We do not plan renaming this repository.

**Comment by babakfp** [comment]
Hello
This is what I'm talking about:
https://user-images.githubusercontent.com/44144724/120073350-c16b1500-c04c-11eb-9496-201dc437493f.mp4
I'm not saying that it's hard for me to find the repo, I'm saying that it's hard for other people to find it. I don't think that there is any value in keeping the current name but, there is a value in changing it to "Adonis" or "AdonisJS".
@RomainLanz

**Comment by thetutlage** [comment]
Search with adonisjs

**Comment by thetutlage** [comment]
Also I don't think anyone who knows the name Adonisjs at first place will not know about the website.

Plus I'll prefer if someone first ask us why we named something one or the other way vs just giving us a suggestion to change the repo name overnight

**Comment by babakfp** [comment]
> Search with adonisjs

Yes, now I can find the Adonis account but it isn't the point.

> Also I don't think anyone who knows the name Adonisjs at first place will not know about the website.

The user can look for the _website_ or the _repo_ but it isn't the point. let's say you see a shirt ad on Twitter and the ad says "Go to example.com and search for the product by name and you will be able to find it", isn't it better if it just gave you the product URL instead?

**The point is that the user finds what he's looking for easily and fast.**

If my approach wasn't right, feel free to correct it🌺.
@thetutlage

**Comment by RomainLanz** [comment]
No need to keep arguing. The name of this repository will not change.
