### ISSUE TITLE
 Error csrfField is not a function 

### ISSUE THREAD

**Issue by helderam** [adonisjs/core#2707]
## Package version
5.0.0

## Node.js and npm version
npm -v
7.7.6
node -v
v15.14.0

## Sample Code (to reproduce the issue)
@layout('layouts/master')

@set('title', 'Central E-Commerce')

@section('body')
  
  <div class="container" style="min-height: 760px;">
    <div class="row justify-content-center mt-5">
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card shadow">
          <div class="card-title text-center border-bottom">
            <h2 class="p-3">Login</h2>
          </div>
          <div class="card-body">
            <form action="{{ route('UsersController.store') }}">
              {{ csrfField() }}

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
