### ISSUE TITLE
import model using parameter

### ISSUE THREAD

**Issue by devCchan** [adonisjs/core#2708]
## Prerequisites

I want to import model using parameter inside function

ex : this.model = 'User'

- in adonis 4 we can import dynamic model using parameter like this:
```js
//code is working
 async test({ request }: HttpContextContract) {
      const data = await use(`App/Models/${this.model}`)
 }
```

- in adonis 5 :    
```js
//code is working
 async test({ request }: HttpContextContract) {
   const { default: data } = await import(`App/Models/User`)
 }
```

```js
//code not working
 async test({ request }: HttpContextContract) {
   const { default: data } = await import(`App/Models/${this.model}`)
 }
```
**error : "Cannot find module 'App/Models/User'\nRequire stack:\n-"** 

my question : how to load dynamic model based on parameter in adonis 5 ?
```js
await import(`App/Models/${this.model}`)
```

## Package version
   Framework version: 5.1.6  

## Node.js and npm version
v14.16.1

**Comment by thetutlage** [comment]
This shouldn't be reported as an issue. Please use discussion threads for asking questions.
