### ISSUE TITLE
502 bad gateway nginx on some devices

### ISSUE THREAD

**Issue by tehceen** [adonisjs/core#2724]
hello i am getting 502 bad gateway when i make api request from mobile app but its working fine on postman. what could be the problem kindly help.

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by tehceen** [comment]
![image_2021_06_02T07_11_28_973Z](https://user-images.githubusercontent.com/43634528/120477065-c3becd80-c3c4-11eb-897b-4b00e4b1e323.png)
kinldy check this  image. i am using nginx on my server. sometime it works sometime fails although its work fine all time ok on the post man.

**Comment by RomainLanz** [comment]
This is not related to Adonis, this is probably an issue with your Nginx configuration or your Flutter code.

**Comment by tehceen** [comment]
sir if you could help me about this issue or nginx will be great.
