### ISSUE TITLE
Getting error as "TypeError: this.container.singleton is not a function" while starting server

### ISSUE THREAD

**Issue by ms1sistemas** [adonisjs/core#2729]
### **Package version**

@adonisjs/core": "5.1.8"

### **Node.js and npm version**

npm v6.14.13 and node v14.17.0 - Mac OS

### **Sample Code (to reproduce the issue)**

node ace serve --watch

### **Package.json:**
{
  "name": "",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build --production",
    "start": "ENV_SILENT=true node server.js",
    "dev": "node ace serve --watch"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^5.3.0",
    "adonis-preset-ts": "^2.1.0",
    "pino-pretty": "^5.0.2",
    "typescript": "^4.2.4",
    "youch": "^2.2.2",
    "youch-terminal": "^1.1.1"
  },
  "dependencies": {
    "@adonisjs/auth": "^8.0.5",
    "@adonisjs/core": "^5.1.8",
    "@adonisjs/lucid": "^10.0.0",
    "@adonisjs/mail": "^7.2.0",
    "@adonisjs/repl": "^3.1.3",
    "@adonisjs/session": "^6.0.5",
    "@adonisjs/view": "^6.0.3",
    "@mailchimp/mailchimp_marketing": "^3.0.41",
    "adonis5-sentry": "^1.1.0",
    "axios": "^0.21.1",
    "crypto-random-string": "^3.3.1",
    "form-data": "^4.0.0",
    "hasha": "^5.2.2",
    "jsonwebtoken": "^8.5.1",
    "luxon": "^1.26.0",
    "pg": "^8.5.1",
    "phc-argon2": "^1.1.0",
    "proxy-addr": "^2.0.7",
    "qs": "^6.10.1",
    "random": "^3.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "uuid": "^8.3.2"
  }
}

### **BONUS (a sample repo to reproduce the issue)**

TypeError: this.container.singleton is not a function

1 SentryProvider.register
  /Users/ms1sistemas/Documents/webcte_back/node_modules/adonis5-sentry/build/providers/SentryProvider.js:28

2 anonymous
  /Users/ms1sistemas/Documents/webcte_back/node_modules/@adonisjs/fold/build/src/Registrar/index.js:103

3 Registrar.register
  /Users/ms1sistemas/Documents/webcte_back/node_modules/@adonisjs/fold/build/src/Registrar/index.js:101

4 anonymous
  /Users/ms1sistemas/Documents/webcte_back/node_modules/@adonisjs/application/build/src/Application.js:530

5 Application.registerProviders
  /Users/ms1sistemas/Documents/webcte_back/node_modules/@adonisjs/application/build/src/Application.js:524

6 HttpServer.wire
  /Users/ms1sistemas/Documents/webcte_back/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:52

7 HttpServer.start
  /Users/ms1sistemas/Documents/webcte_back/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:146

[ warn ]  Underlying HTTP server died with "0 code"
[ info ]  watching file system for changes

**Comment by thetutlage** [comment]
The issue is with the adonis sentry package. Please report it with them and ask them to follow the upgrade guide to update the provider. 

https://docs.adonisjs.com/releases/out-of-preview#application-bootstrap-process

**Comment by ms1sistemas** [comment]
Tank you so much
