### ISSUE TITLE
Cannot read property 'has' of undefined  - flashMessages

### ISSUE THREAD

**Issue by holoyan** [adonisjs/core#2775]
## Package version
"@adonisjs/core": "^5.1.6"

## Node.js and npm version
node -v
v14.17.0

npm -v
6.14.13

## Code Sample

In the route.ts file I have

`
Route.get('/', async (ctx) => {
  return ctx.view.render('welcome')
})
`

and in the welcome.edge

`
@if(flashMessages.has('errors.username'))
    <p> {{ flashMessages.get('errors.username') }} </p>
@end
`

`
"message":"Cannot read property 'has' of undefined","stack":"Error: Cannot read property 'has' of undefined\n    at anonymous (/home/<USER>/projects/hello-world/resources/views/welcome.edge:34:0)\n    at Template.reThrow (/home/<USER>/projects/hello-world/node_modules/edge.js/build/src/Template/index.js:178:15)\n    at template (eval at wrapToFunction (/home/<USER>/projects/hello-world/node_modules/edge.js/build/src/Template/index.js:64:20), <anonymous>:87:10)\n    at Template.renderCompiled (/home/<USER>/projects/hello-world/node_modules/edge.js/build/src/Template/index.js:84:57)\n    at Template.render (/home/<USER>/projects/hello-world/node_modules/edge.js/build/src/Template/index.js:139:21)\n    at EdgeRenderer.render (/home/<USER>/projects/hello-world/node_modules/edge.js/build/src/Renderer/index.js:37:103)\n    at Object.handler (/home/<USER>/projects/hello-world/start/routes.ts:25:19)\n    at Object.PreCompiler.runRouteHandler [as fn] (/home/<USER>/projects/hello-world/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:44:50)\n    at Runnable.invoke (/home/<USER>/projects/hello-world/node_modules/co-compose/build/src/Runnable.js:55:48)\n    at BodyParserMiddleware.handle (/home/<USER>/projects/hello-world/node_modules/@adonisjs/bodyparser/build/src/BodyParser/index.js:103:20)\n    at Injector.callAsync (/home/<USER>/projects/hello-world/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)","code":"E_RUNTIME_EXCEPTION"}
`

what I'm doing wrong?

Thank you!

**Comment by thetutlage** [comment]
Please share the complete package.json file?

**Comment by holoyan** [comment]
```
{
  "name": "hello-world",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build --production",
    "start": "node server.js",
    "dev": "node ace serve --watch"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^5.2.0",
    "adonis-preset-ts": "^2.1.0",
    "pino-pretty": "^4.8.0",
    "typescript": "^4.2.4",
    "youch": "^2.2.2",
    "youch-terminal": "^1.1.1"
  },
  "dependencies": {
    "@adonisjs/core": "^5.1.6",
    "@adonisjs/lucid": "^15.0.0",
    "@adonisjs/repl": "^3.1.2",
    "@adonisjs/view": "^6.0.1",
    "@types/socket.io": "^3.0.2",
    "edge.js": "^5.2.0",
    "luxon": "^1.27.0",
    "mysql": "^2.18.1",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "socket.io": "^4.1.1",
    "source-map-support": "^0.5.19"
  }
}


```

**Comment by thetutlage** [comment]
Its because the `@adonisjs/session` package is not installed. Docs here https://docs.adonisjs.com/guides/session

I recommend using the [discussions forum](https://github.com/adonisjs/core/discussions) in the future to clarify your doubts. We keep the issue tracker just for the confirmed issues or feature requests. 🙂

**Comment by holoyan** [comment]
@thetutlage Thank you

**Comment by hassan005004** [comment]
> Its because the `@adonisjs/session` package is not installed. Docs here https://docs.adonisjs.com/guides/session
> 
> I recommend using the [discussions forum](https://github.com/adonisjs/core/discussions) in the future to clarify your doubts. We keep the issue tracker just for the confirmed issues or feature requests. 🙂

i have installed but still eror

**Comment by RomainLanz** [comment]
You also have to configure it (second tab on the installation process).

```sh
node ace configure @adonisjs/session
```
