### ISSUE TITLE
Adonisjs 5 Password Hashing Error

### ISSUE THREAD

**Issue by dev-techguy** [adonisjs/core#2780]
❯ error     database/seeders/User
  Cannot find module 'phc-argon2'
Require stack:
- /home/techguy/WebstormProjects/shiftechafrica.com/node_modules/@adonisjs/hash/build/src/Drivers/Argon.js
- /home/techguy/WebstormProjects/shiftechafrica.com/node_modules/@adonisjs/hash/build/src/Hash/index.js
- /home/techguy/WebstormProjects/shiftechafrica.com/node_modules/@adonisjs/hash/build/standalone.js
- /home/techguy/WebstormProjects/shiftechafrica.com/node_modules/@adonisjs/core/build/standalone.js
- /home/techguy/WebstormProjects/shiftechafrica.com/ace

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
