### ISSUE TITLE
AdonisJS Production Build Error

### ISSUE THREAD

**Issue by dev-techguy** [adonisjs/core#2803]
![image](https://user-images.githubusercontent.com/36882600/122347461-b96b0a80-cf52-11eb-8b06-d49c4cdd5aa9.png)
`"use strict";
var __importDefault = (this && this.__importDefault) || function(mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const Env_1 = __importDefault(global[Symbol.for('ioc.use')]("Adonis/Core/Env"));
exports.default = Env_1.default.rules({
    HOST: Env_1.default.schema.string({ format: 'host' }),
    PORT: Env_1.default.schema.number(),
    APP_KEY: Env_1.default.schema.string(),
    APP_NAME: Env_1.default.schema.string(),
    NODE_ENV: Env_1.default.schema.enum(['development', 'production', 'testing']),
});
//# sourceMappingURL=env.js.map
`

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by dev-techguy** [comment]
@thetutlage Ok but having an issue with build seems I may need some guidelines on this.

**Comment by RodolfoSilva** [comment]
@dev-techguy you need to set the HOST env.
Check the error message
![image](https://user-images.githubusercontent.com/1703020/122687361-70ce7e00-d1ec-11eb-9df9-2a9ad7bbab92.png)
