### ISSUE TITLE
Unable to Seed Selected file

### ISSUE THREAD

**Issue by venki0004** [adonisjs/core#2808]
## Package version
Adonis V5
## Node.js and npm version
 Node.js = 14.15 and Npm = 6.0.0 to 

## Sample Code (to reproduce the issue)
I was unable seed selected file by following command
```
node ace db:seed --files "./database/seeders/Templates.ts"
```
this throwing following error

![image](https://user-images.githubusercontent.com/74340982/122523017-33bf8b80-d034-11eb-8aec-fe8a578b4c25.png)

## BONUS (a sample repo to reproduce the issue)
codebase structure
![image](https://user-images.githubusercontent.com/74340982/122523101-4b970f80-d034-11eb-924a-e771cc668efe.png)

**Comment by thetutlage** [comment]
Hello. You posted the issue in the wrong repo. Please post issues in the relevant repos only. Which is `adonisjs/lucid` in this case. ( Respect our time )

You are passing the wrong file path to the `--files` flag. The file name is `Template.ts` and you are passing `Templates.ts`. So it's always better to double check.
