### ISSUE TITLE
Route validator can work on V5 ?

### ISSUE THREAD

**Issue by venki0004** [adonisjs/core#2816]
## Package version
V5

## Node.js and npm version
Nodejs 14.15,npm 6.4

## Sample Code (to reproduce the issue)
I want to Validate request in Router Level
like Route.resource('templates','TemplateController').validator('templateRequest');

but its throws error 
Property 'validator' does not exist on type 'RouteResourceContract'.ts

**Comment by thetutlage** [comment]
I don't the docs anywhere mentions that `Route.resource().validator` is a method
