### ISSUE TITLE
ruleFn rule is not registered. Use validator.rule to add the rule.

### ISSUE THREAD

**Issue by swapnilnandgave** [adonisjs/core#2824]
## Package version
node ace --version             
App version: 1.0.0
Framework version: 5.1.8
Assembler version: 5.3.2    

## Node.js and npm version
node -v
v14.15.4
npm -v
6.14.10

## Sample Code (to reproduce the issue)
`const validationSchema = schema.create({
            data: schema.array([rules.minLength(1)])
                    .members(schema.object().members({
                        question: schema.string({trim: true}, [rules.required]),
                        answers: schema.array([rules.minLength(1)]).members(schema.string({trim: true})
                    )})
                ),
        });`

## Getting below error message
`"message": "\"ruleFn\" rule is not registered. Use \"validator.rule\" to add the rule.",
    "stack": "Error: \"ruleFn\" rule is not registered. Use \"validator.rule\" to add the rule.\n    at compileRule`

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by swapnilnandgave** [comment]
It is not required. It is solved by making rules.required as method like below
rules.required()
