### ISSUE TITLE
cannot create same route resource under different prefix

### ISSUE THREAD

**Issue by tsulatsitamim** [adonisjs/core#2895]
## Package version
^5.1.8

## Node.js and npm version
node 14.16.0, npm 6.14.11

## Sample Code (to reproduce the issue)
```
Route.group(() => {
  Route.resource('/questions', 'Survey/Health/HealthSurveyQuestionController').apiOnly()
}).prefix('/health-surveys')

Route.group(() => {
  Route.resource('/questions', 'Survey/Mental/MentalSurveyQuestionController').apiOnly()
}).prefix('/mental-surveys')
```

## Error
`RouterException: E_DUPLICATE_ROUTE_NAME: Duplicate route name "questions.index"`

**Comment by thetutlage** [comment]
It is the duplicate name issue. Covered in the docs here https://docs.adonisjs.com/guides/routing#naming-routes

**Comment by tsulatsitamim** [comment]
thank you
