### ISSUE TITLE
Error sending email via Amazon SES

### ISSUE THREAD

**Issue by jeancarlosdanese** [adonisjs/core#2914]
Hello!

First of all thanks for the great work with Adonis.

## Send mail with Amazon SES

My mailer configuration for Amazon SES was returning the following error:

**message**: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

## The documentation guides the configuration of the files:

-- env.ts
SES_ACCESS_KEY: Env.schema.string(),
SES_ACCESS_SECRET: Env.schema.string(),
SES_REGION: Env.schema.string(),

-- .env
SES_ACCESS_KEY=
SES_ACCESS_SECRET=
SES_REGION=

## Fixed changing the file variables as follows:

-- env.ts
**SES_KEY**: Env.schema.string(),
**SES_SECRET**: Env.schema.string(),
SES_REGION: Env.schema.string(),

-- .env
**SES_KEY**=
**SES_SECRET**=
SES_REGION=

Hope this helps...

**Comment by thetutlage** [comment]
I am not sure what exactly your issue is and why you decided to change the environment variables. Also it seems more like a question than a bug. So I recommend using the [discussions forum](https://github.com/adonisjs/core/discussions)
