### ISSUE TITLE
not working new installation with webpack

### ISSUE THREAD

**Issue by SerjoA** [adonisjs/core#2928]
hi, first of all thank you very much
i love the framework

today i installed both api and web editions, web doesnt work, i have tried everything i know but still , api works

[ info ]  starting http server...
(node:64369) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/serjoagronov/Desktop/trainings/nodejs/simple-crm-new/server.ts:13
import 'reflect-metadata'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[ encore ] Running webpack-dev-server ...
[ warn ]  Underlying HTTP server died with "1 code"
[ info ]  watching file system for changes
[ encore ] [webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.client has an unknown property 'host'. These properties are valid:
   object { logging?, overlay?, progress?, webSocketTransport?, webSocketURL? }
[ warn ]  Underlying encore dev server died with "2 code"

**Comment by Egorka** [comment]
Same error without webpack:

[ info ]  building project...
[ info ]  starting http server...
(node:1622) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/var/node/pica/server.ts:13
import 'reflect-metadata'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
[ warn ]  Underlying HTTP server died with "1 code"
[ info ]  watching file system for changes

**Comment by thetutlage** [comment]
Can't help with the provided information. please share a project repo with the minimal amount of code required to reproduce the issue.

**Comment by SerjoA** [comment]
Immideatly after creating new project

**Comment by sajaddp** [comment]
@thetutlage 
Same issue!
I just follow steps on https://docs.adonisjs.com/guides/installation

```
node: v16.4.0
npm: 7.20.0
```

**Comment by Egorka** [comment]
I's blank just generated project.

node: v14.17.3
npm: 6.14.13

**Comment by SerjoA** [comment]
its a tsconfig.json error from what i see, i replaced it with old adonis project iam using and it works

**Comment by sajaddp** [comment]
@SerjoA 
Is the problem solved for you?
How was it fixed?

**Comment by SerjoA** [comment]
not solved, iam still on it, i have other adonis projects on laptop that are working so iam trying to figure out whats wrong

**Comment by teamsoo** [comment]
Same issue here
### ENV
```
Node 16.5.0
npm 7.19.1
```

### FRESH HELLO WORLD PROJECT
`npm init adonis-ts-app@latest hello-world`

### FIRST RUN
`node ace serve --watch`

### RESULT
```
[ info ]  building project...
[ info ]  starting http server...
(node:35289) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/xxx/Workspace/xxx/adonis/hello-world/server.ts:13
import 'reflect-metadata'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
[ encore ] Running webpack-dev-server ...
[ warn ]  Underlying HTTP server died with "1 code"
[ info ]  watching file system for changes
[ encore ] [webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.client has an unknown property 'host'. These properties are valid:
   object { logging?, overlay?, progress?, webSocketTransport?, webSocketURL? }
[ warn ]  Underlying encore dev server died with "2 code"
```

**Comment by thetutlage** [comment]
Can you push your project to a repo and share it with me? I am not able to reproduce this specific issue.

**Comment by SerjoA** [comment]
its a blank project, i just did :
npm init adonis-ts-app@latest simple-crm

and chose web

**Comment by SerjoA** [comment]
what i noticed now is when i install it with eslint and prettifier the issue goes away

**Comment by thetutlage** [comment]
I did. That is why I am asking "I am not able to reproduce this specific issue."

**Comment by SerjoA** [comment]
you got my comment about prettifier and eslint?

**Comment by sajaddp** [comment]
I used ` npm init adonis-ts-app hello-world ` instead of ` npm init adonis-ts-app@latest hello-world `  and problem solved!

**Comment by SerjoA** [comment]
will try also, thnx

**Comment by Egorka** [comment]
Thanks, without @latest everything works as expected.

**Comment by SerjoA** [comment]
for me webpack encore still doesnt work even without the @latest

[ encore ] [webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.client has an unknown property 'host'. These properties are valid:
   object { logging?, overlay?, progress?, webSocketTransport?, webSocketURL? }
[ warn ]  Underlying encore dev server died with "2 code"

**Comment by SerjoA** [comment]
atm i fixed it by adding to webpack.config.js file:

Encore.configureDevServerOptions

inside this function i added :

options.static.push({
    directory: join(__dirname, './resources/views'),
    watch: true,
  })

// this one
  options.client = {};

and it worked

**Comment by SerjoA** [comment]
@thetutlage you/i can close the issue, but i think its best to pin it with answers we wrote here
