### ISSUE TITLE
Cors issues with Adonisjs/ally

### ISSUE THREAD

**Issue by ArthurDanjou** [adonisjs/core#2939]
## Package version
5.1.10

## Node.js and npm version
Nodejs: 16.4.0
NPM: 7.20.0
Yarn: 1.22.10

## Sample Code (to reproduce the issue)
https://github.com/ArthurDanjou/artapi/tree/dev

## Explanation
I want to create my own guestbook for my website. I added @adonisjs/ally package in its latest version (4.1.0) with the Google, Github, Discord and Twitter drivers. Everything is configured correctly, I can identify myself with my social networks from my API directly. However, when I access the same route from my Nuxt application, I have a CORS error telling me that there is no "Access-Control-Allow-Origin" header yet I have correctly configured the configuration file on the adonisjs side, and axios on the nuxt side.

Can you help me to solve my problem ?

**Comment by thetutlage** [comment]
How are you able to identify that the issue is with `@adonisjs/ally`?

**Comment by ArthurDanjou** [comment]
I have a Cors issue only with the routes where I use ally package. I don't have this error on other routes

**Comment by thetutlage** [comment]
The ally routes are not meant to be called from frontend. Also with the shared information, I cannot provide any help.

Please use discussions forum to ask for help and make sure to share proper code samples
