### ISSUE TITLE
Columns disappeared after update

### ISSUE THREAD

**Issue by yurycooliq** [adonisjs/core#2944]
## Prerequisites

Hi there! I updated the dependencies today and ran into a strange bug. Gone some columns from the model. I suspect this is due to Pino, which is in the dependencies of some Adonis packages. A message appeared in the console that hadn't been there before:
`(node:6056) [PINODEP004] Warning: bindings.serializers is deprecated, use options.serializers option instead`
Googling this warning took me to the Pino repository, which says the same in the [api.md](https://github.com/pinojs/pino/blob/master/docs/api.md#bindingsserializers-object---deprecated):
`bindings.serializers (Object) - DEPRECATED
Use options.serializers instead.`
I tried everything, updated Node and even rolled back to the version when everything worked for sure, but the problem did not resolve and the warning still appears in the console.

## Package version
v5.1.7

## Node.js and npm version
Node v16.4.1
NPM v7.14.0

## Sample Code (to reproduce the issue)
This columns are disappeared:
`
  @column()
  public status: string

  @column()
  public averagePrice: number

  @column()
  public position: number

  @column()
  public emergencyClosed?: boolean

  @column()
  public closedBy?: number

  @column.dateTime()
  public closedAt: DateTime
`
I don't see any relationship, half of the columns are gone, half are left. All of a different type. When accessing these values, it returns undefined, although the database contains these values.

**Comment by yurycooliq** [comment]
A more detailed investigation showed that the model is cropped if I transfer it immediately after saving. For example this code (which worked fine before)
```
    ...
    await trade.save()
    tradeEvents.emit('new_trade', trade, portfolio, auth.user)
    ...
```
will transfer the cropped model.

If I change to this
```
    ...
    await trade.save()
    tradeEvents.emit('new_trade', await Trade.find(trade.id), portfolio, auth.user)
    ...
```
all data is transferred. Why is this happening and why did it work normally before?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
