### ISSUE TITLE
Adonis 4.1 Server timeout issue

### ISSUE THREAD

**Issue by infinitywars** [adonisjs/core#2948]
Hi ,

I have a app in which frontend is sending api request and I am not getting response from the server because of timeout issue. The timeout is set to 1 second as default . I need to increase the timeout to 2 to 3 minutes. Is there any way to increase timeout for adonis server?

While debugging, the api request from browser is coming to the adonis server and the response is also getting logged in the console. But, the response is not received by the browser due to default server timeout of 1 minute. So, to increase the timeout, we have done the following. But couldn't fix this

Node.js and npm version
"adonis-version": "4.1.0",
"@adonisjs/vow": "^1.0.17",

Sample Code (to reproduce the issue)

I have enabled Server.getInstance().timeout = 0; in vowfile.js and still the timeout happens in 1 minute.

```
module.exports = (cli, runner) => {
runner.before(async () => {

const DBname = Env.get('DB_DATABASE');
if (!(DBname.includes('test') || DBname.includes('postgres'))) {
throw new Error(Use test DB instead of ${DBname});
}


const Server = use('Adonis/Src/Server').listen(process.env.HOST, process.env.PORT);
Server.getInstance().timeout = 0;


await ace.call('migration:refresh', {}, { silent: true });
await ace.call('seed', {}, { silent: true });
});

runner.after(async () => {
use('Adonis/Src/Server').getInstance().close();
});
};
```
Other methods
I also tried solution to issue #877 and #434 and no luck.

This is what I tried in server.js

```
const { Ignitor } = require('@adonisjs/ignitor')

new Ignitor(require('@adonisjs/fold'))
    .appRoot(__dirname)
    .fireHttpServer()  
    .then(() => {
        use('Adonis/Src/Server').getInstance().timeout = 0;
        use('Logger').info(`Server timeout: ${use('Adonis/Src/Server').getInstance().timeout}`);
    })  
    .catch(console.error)
```

**Comment by thetutlage** [comment]
The client making the request also timeout requests. So make sure your frontend Ajax library is not timing out the requests.

Also, vowfile has nothing to do with it, since that is used for testing

**Comment by infinitywars** [comment]
Hi,
  
Thanks for the response. It doesn't seems to be a frontend issue because, I am getting timeout error when I use Postman but in the code I'm getting the request and response is also getting logged in the console/logger. Kindly find the attached screenshot.
  
  
  ![Capture](https://user-images.githubusercontent.com/42686533/126648763-05be750d-73c8-449c-88e9-6790154d27a5.PNG)
  
  
Is there anyway in adonis to increase the timeout to more than 2-3 minutes?

**Comment by sathishkumar16** [comment]
Hi @thetutlage 

I'm also facing the same timeout issue in adonis. Could you please let me know how to increase the server timeout in adonis 4.1 version.

**Comment by sathishkumar16** [comment]
Hi @thetutlage 

I'm also facing the same timeout issue in adonis. Could you please let me know how to increase the server timeout in adonis 4.1 version.

**Comment by thetutlage** [comment]
You just need to follow the Nodejs documentation around `timeout` https://nodejs.org/api/http.html#http_server_timeout.

AdonisJS is using the standard Node.js HTTP server under the hood and you can access it as follows.

```ts
new Ignitor(require('@adonisjs/fold'))
    .appRoot(__dirname)
    .fireHttpServer()  
    .then(() => {
        use('Adonis/Src/Server').getInstance().timeout = 0;
    })  
    .catch(console.error)
```

Also, when I said that **clients also have timeout**, I meant all HTTP clients have timeout as well including postman. https://learning.postman.com/docs/getting-started/settings/. You just need to figure out where the timeout is happening and then change it.

Also, follow the Node.js docs to understand how to disable or tweak the timeout
