### ISSUE TITLE
can adonis pass data from middleware to router ? 

### ISSUE THREAD

**Issue by ibalaji777** [adonisjs/core#2966]
i want to pass data from middleware to router based some xy logic . can i do in adonis?

**Comment by RomainLanz** [comment]
Duplicates of https://github.com/adonisjs/core/discussions/2965

**Comment by ibalaji777** [comment]
> Duplicates of #2965
i updated question , could you tell it is possible in adonis?

**Comment by ibalaji777** [comment]
> Duplicates of #2965
This  question is not invalid type 

You can attach what you want into the request context

Ref https://docs.adonisjs.com/guides/request#informing-typescript-about-the-method

declare module '@ioc:Adonis/Core/Request' {
  interface RequestContract {
    myData: any
  }
}
Routes

Route.get('hello', (ctx: HttpContextContract) => {
  const data = ctx.request.myData
  ctx.response.send(data)
}).middleware((ctx, next) => {
  ctx.request.myData = 'Hello World'
  return next()
})
