### ISSUE TITLE
Allow database migrations from code

### ISSUE THREAD

**Issue by 852Kerfunkle** [adonisjs/core#2968]
Hello, I'm developing an Electron app using AdonisJs and I'm in the situations where I need to run database migrations to upgrade the apps database.

Thank you.

## Why this feature is required (specific use-cases will be appreciated)?
In situations where the node or npm executables are not necessarily available, it's difficult to run database migrations.

## Have you tried any other work arounds?
There were a couple things I tried, to run the ace tasks from code, that sort of worked, but once the migration finished, it would always terminate the entire electron application (I assume there's a process.exit(0) happening somewhere?).

For now I'm looking into ways to achieve this with child-process, nevertheless, please consider this request.

## Are you willing to work on it with little guidance?
I'm not very familiar with the inner workings of Adonis at the moment. Would definitely require some guidance

**Comment by thetutlage** [comment]
Please read the docs. https://docs.adonisjs.com/guides/database/migrations#running-migrations-programmatically

Also, in future open issues in the correct repo

**Comment by 852Kerfunkle** [comment]
> Please read the docs. https://docs.adonisjs.com/guides/database/migrations#running-migrations-programmatically

Wait, how did I miss that? Thanks!

**Comment by biloo-dev** [comment]
hi **852Kerfunkle**  How I built Electron with AdonisJs
I could not find the solution, please, can you help me!
