### ISSUE TITLE
Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.

### ISSUE THREAD

**Issue by Mitch-i** [adonisjs/core#2983]
I download "docs.adonisjs.com" and update all packages to latest and get error

[ encore ] [webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.client has an unknown property 'host'. These properties are valid:
   object { logging?, overlay?, progress?, webSocketTransport?, webSocketURL? }
[ warn ]  Underlying encore dev server died with "2 code"

{
  "name": "docs.adonisjs.com",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "encore production && node ace build:static",
    "start": "node server.js",
    "dev": "node ace serve --watch",
    "lint": "eslint . --ext=.ts",
    "format": "prettier --write ."
  },
  "devDependencies": {
    "@adonisjs/assembler": "^5.3.5",
    "@hotwired/turbo": "^7.0.0-rc.1",
    "@symfony/webpack-encore": "^1.5.0",
    "adonis-preset-ts": "^2.1.0",
    "alpine-hotwire-turbo-adapter": "^0.1.1",
    "alpinejs": "^3.2.2",
    "eslint": "^7.31.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-adonis": "^1.3.3",
    "eslint-plugin-prettier": "^3.4.0",
    "fs-extra": "^10.0.0",
    "lazysizes": "^5.3.2",
    "normalize.css": "^8.0.1",
    "pino-pretty": "^5.1.2",
    "prettier": "2.3.2",
    "quicklink": "^2.2.0",
    "typescript": "^4.3.5",
    "youch": "^2.2.2",
    "youch-terminal": "^1.1.1"
  },
  "dependencies": {
    "@adonisjs/core": "^5.1.11",
    "@adonisjs/lucid": "15.0.3",
    "@adonisjs/repl": "^3.1.5",
    "@adonisjs/view": "^6.0.8",
    "@dimerapp/content": "^2.0.4",
    "@dimerapp/edge": "^2.0.1",
    "@docsearch/css": "^1.0.0-alpha.28",
    "@docsearch/js": "^1.0.0-alpha.28",
    "docsearch.js": "^2.6.3",
    "proxy-addr": "^2.0.7",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  },
  "volta": {
    "node": "16.1.0"
  }
}

Error disappear if I remove webpack.config.js, but get other of course.

Console log output (ncore.configureDevServerOptions((options) => {
console.log(options);)
 ..}
 
 
{
  static: {
    directory: '/home/michael/Downloads/docs.adonisjs.com-develop/public'
  },
  headers: { 'Access-Control-Allow-Origin': '*' },
  compress: true,
  historyApiFallback: true,
  liveReload: false,
  client: { host: 'localhost' },   <---------------------------------- that is
  port: 8080
}
________

And what to import to work

ReferenceError: use is not defined

**Comment by thetutlage** [comment]
Please open issue in the correct repo
