### ISSUE TITLE
How to use a controller function

### ISSUE THREAD

**Issue by RamonSouzaaa** [adonisjs/core#2992]
### Discussed in https://github.com/adonisjs/core/discussions/2991

<div type='discussions-op-text'>

<sup>Originally posted by **RamonSouzaaa** August  3, 2021</sup>
Hello

I'm using adonisjs and I need to call a function from my controller directly in the view.</div>

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
