### ISSUE TITLE
Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by sufian07** [adonisjs/core#2993]
## Prerequisites

Tried to install adonis 5 by `yarn create adonis-ts-app hello-world` then got the error:

CUSTOMIZE PROJECT
❯ Select the project structure · api
❯ Enter the project name · hello-world
❯ Setup eslint? (y/N) · false

RUNNING TASKS
❯ Scaffold project
❯ Scaffold project 20 ms
❯ Install dependencies 44 s
❯ Configure installed packages 1.44 ms
  Package subpath './package.json' is not defined by "exports" in /home/sufian/projects/hello-world/node_modules/@adonisjs/core/package.json

[ error ]  Unable to create project. Cleaning up
Done in 48.84s.
 

## Package version
5.1.11

## Node.js and npm version
v14.0.0

**Comment by RomainLanz** [comment]
Hey @sufian07! 👋 

You are using an outdated version of Node.js, please upgrade.
