### ISSUE TITLE
.adonisrc.json rebuild

### ISSUE THREAD

**Issue by hugoaboud** [adonisjs/core#3002]
I just started using AdonisJS and a small thing felt strange on commit.

I'm not sure this is a `docs` feature request (since I haven't found it on the docs) or a discussion for the `core`:

As I commited, the `.adonisrc.json` wasn't uploaded since it starts with a `.`. I wasn't paying enough attention and lost this file while cloning the project to test the build instructions.
When trying to run, I get the following error:
```
(node:13540) UnhandledPromiseRejectionWarning: Error: AdonisJS expects ".adonisrc.json" file to exist in the application root
```
I couldn't find a way to rebuild it, other than copying from another project and manually modifying it.

My `core` question is: why does it start with a `.`?
My `docs` feature request is: instructions on how to rebuild it.

**Comment by thetutlage** [comment]
File starting with `.` are not ignored by the default. It has something to do with your `.gitignore` file. The files starting with a dot is a convention used by many tools including eslint, prettier and even git itself.

Also, I recommend using discussions to ask questions
