### ISSUE TITLE
Allow array of listeners in Event.on

### ISSUE THREAD

**Issue by arthur-er** [adonisjs/core#3038]
## Why this feature is required (specific use-cases will be appreciated)
On event driven applications it gets cumbersome repeating the Event.on for every listener specially when namespacing comes in. For example:

```typescript
Event.on('event', 'ListenerA.handler').namespace('Namespace')
Event.on('event', 'ListenerB.handler').namespace('Namespace')
Event.on('event', 'ListenerC.handler').namespace('Namespace')
Event.on('event', 'ListenerD.handler').namespace('Namespace')

// The following approach would be cleaner
Event.on('event', [
  'ListenerA.handler',
  'ListenerB.handler',
  'ListenerC.handler',
  'ListenerD.handler',
]).namespace('Namespace')
```

## Have you tried any other work arounds?
No

## Are you willing to work on it with little guidance?
Yes

**Comment by RomainLanz** [comment]
Hey @arthur-er! 👋 

1. In what order those should be called?
2. Why not creating a "Master Listener" that call those instead of defining multiple listeners?

**Comment by arthur-er** [comment]
Hello @RomainLanz!

1. I think they should be called in the order they are defined, albeit the listeners should be able to handle the event independent of the order.
  2. In my opinion it is more declarative to have the listeners called directly from the event

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by thetutlage** [comment]
Please ignore the last comment. The response was mistaken with some other issue

**Comment by arthur-er** [comment]
Solved by using a simple helper function:

```typescript
import Application from '@ioc:Adonis/Core/Application'

const resolver = Application.container.getResolver(undefined, 'eventListeners', 'App/Listeners')

const groupListeners =
  (...listeners: string[]) =>
  (...data: any[]) =>
    listeners.forEach((listener) => resolver.call(listener, undefined, data))

export default groupListeners

// Used like this
import Event from '@ioc:Adonis/Core/Event'

Event.on('test:event', groupListeners('TestA.handle', 'TestB.handle'))
```
