### ISSUE TITLE
How to get the app url?

### ISSUE THREAD

**Issue by myckhel** [adonisjs/core#3049]
Please someone rescue me.
i have searched the entire world of internet and could not find anything useful.

How do i get the app url in adonisJs 5 so that it gives me something like `http://127.0.0.1:3333`.

**Comment by arthur-er** [comment]
You should ask for help in the discussions tab.

But, to get it running in localhost set HOST envar to 0.0.0.0

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
