### ISSUE TITLE
ER_INVALID_DEFAULT: Invalid default value for 'updated_at'

### ISSUE THREAD

**Issue by freshcode-io** [adonisjs/core#3082]
hi there.. 

1) I have this code by default when i add migration:
table.timestamp('created_at', { useTz: true})
table.timestamp('updated_at', { useTz: true})
and resulted in this error "ER_INVALID_DEFAULT: Invalid default value for 'updated_at'".

2) when I change the order of the code:
table.timestamp('updated_at', { useTz: true})
table.timestamp('created_at', { useTz: true})
then it resulted in this error "ER_INVALID_DEFAULT: Invalid default value for 'created_at'". 

3) but if I remove one of them, the migration runs successful
table.timestamp('updated_at', { useTz: true}) < - - - - either remove this line.
table.timestamp('created_at', { useTz: true}) <- - - -- or remove this line.

4) I cannot change the code into  table.timestamp() or table.timestamp(true, true) since the first needed argument is a string.

5) I tried this code too :
table.timestamp('created_at')
table.timestamp('updated_at')
but still resulted in this error too "ER_INVALID_DEFAULT: Invalid default value for 'updated_at'".

## Package version
5.3.5

## Node.js and npm version
14.17.1 && 6.14.13

## MySQL version : 
![Untitled](https://user-images.githubusercontent.com/89387047/130432182-d71d820a-a028-4bee-96f4-b86699bb9db9.png)

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
