### ISSUE TITLE
Ace module is apparently missing in my adonis project

### ISSUE THREAD

**Issue by Sigolirous** [adonisjs/core#3102]
## Package version
```
"devDependencies": {
    "@adonisjs/assembler": "^5.0.0",
    "adonis-preset-ts": "^2.1.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-adonis": "^1.3.3",
    "eslint-plugin-prettier": "^3.4.1",
    "pino-pretty": "^6.0.0",
    "prettier": "^2.3.2",
    "typescript": "~4.2",
    "youch": "^2.2.2",
    "youch-terminal": "^1.1.1"
  },
  "dependencies": {
    "@adonisjs/core": "^5.1.0",
    "@adonisjs/lucid": "^15.0.3",
    "@adonisjs/repl": "^3.0.0",
    "luxon": "^2.0.2",
    "mysql": "^2.18.1",
    "proxy-addr": "^2.0.7",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
```

## Node.js and npm version
Node -> v14.17.5
npm -> 6.14.14

## BONUS (a sample repo to reproduce the issue)
[Repo where i'm geting the issue](https://github.com/Sigolirous/desafioPrecato.git)
The source code is in the Backend folder

## Issue explained
So, I was doing a simple REST API to apply myself for a company and, when I ended the routes configurations I run into this message:
```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/home/augusto-sigolo/Augusto/Desafio Precato/ace'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Apparently, ace module is missing but I don't think that I deleted something in adonis core, and, from my point of view, this problem came out of the blue.

I would be very happy if someone could help me. The application date limit is 08/29 and I really need this job.

Anyways, thanks for seeing this. Hope you have a great life.

**Comment by thetutlage** [comment]
You are missing the `ace` file in the project root. Just copy it from here https://github.com/adonisjs-community/create-adonis-ts-app/blob/develop/templates/web/ace and create the file.

Also, please use the discussions forum for asking questions. We use issues tracker, just for confirmed issues
