### ISSUE TITLE
 Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by marmundo** [adonisjs/core#3109]
## Package version
latest

## Node.js and npm version
14.4.0

## Sample Code (to reproduce the issue)
 npm init adonis-ts-app@latest taskist

## BONUS (a sample repo to reproduce the issue)

I'm trying to create a new project but I'm getting this error.

CUSTOMIZE PROJECT
❯ Select the project structure · web
❯ Enter the project name · taskist
❯ Setup eslint? (y/N) · true
❯ Setup prettier? (y/N) · true
❯ Configure webpack encore for compiling frontend assets? (y/N) · false

RUNNING TASKS
❯ Scaffold project 66 ms
❯ Install dependencies 25 s
❯ Configure installed packages 2.89 ms
  Package subpath './package.json' is not defined by "exports" in 
/Users/marcelo/Documents/desenvolvimento/adonisjs/taskist/node_modules/@adonisjs
/core/package.json

[ error ]  Unable to create project. Cleaning up

**Comment by marmundo** [comment]
I think it needs to add .package.json to exports section. I don't know how to test the solution after try it. If somebody knows how to instruct me how to check if this solution works after npm init.

**Comment by RomainLanz** [comment]
Hey @marmundo! 👋 

Please, update your Node.js version, it is out of date.

**Comment by marmundo** [comment]
Thanks @RomainLanz . Is there a way to update node behind the scenes in case of node is outdated?

**Comment by thetutlage** [comment]
That is more of a node version management related question. I will close this issue for now.

Also, I recommend using the https://github.com/adonisjs/core/discussions in future for asking questions
