### ISSUE TITLE
Error: Server returned nothing (no headers, no data) with docker

### ISSUE THREAD

**Issue by taisso** [adonisjs/core#3130]
I signed up for Adonis V5. I'm using the docker to run it, but whenever I try to access some route it shows this warning and the api doesn't even respond. without using the docker it, it works perfectly.

DockerFile
![Captura de tela de 2021-09-02 14-36-31](https://user-images.githubusercontent.com/54849874/131890894-c956df19-75fc-4a41-9677-3375940b9edb.png)

docker-compose.yaml
![Captura de tela de 2021-09-02 09-13-57](https://user-images.githubusercontent.com/54849874/131876462-60a50372-e718-45bb-96af-d02d74a3d5cf.png)

Entrypoint
![Captura de tela de 2021-09-02 09-14-24](https://user-images.githubusercontent.com/54849874/131876662-12bea8f0-21c2-4c92-bc1a-63c9a3b3fd3d.png)

## Package version
![Captura de tela de 2021-09-02 12-43-02](https://user-images.githubusercontent.com/54849874/131875498-7df074df-9ecf-4caf-bd5a-c71203fd3767.png)

## Node.js and npm version
Node -> v14.17.4
Npm -> v7.20.5
Yarn -> v1.22.5
## Sample Code (to reproduce the issue)
![Captura de tela de 2021-09-02 09-19-51](https://user-images.githubusercontent.com/54849874/131875881-39315336-6532-4ba9-bc66-ec6cd738cff9.png)

![Captura de tela de 2021-09-02 09-23-09](https://user-images.githubusercontent.com/54849874/131875912-bb771065-8dfe-44c1-a30c-d1b749353b18.png)

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
