### ISSUE TITLE
can not install adonisjs cli on ubuntu 20

### ISSUE THREAD

**Issue by shawon122334** [adonisjs/core#3151]

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by shawon122334** [comment]
i am really sorry this wont happen again
