### ISSUE TITLE
I need a help

### ISSUE THREAD

**Issue by jorgebg2016** [adonisjs/core#3165]
Is there any default event when the server application is started or finished? i'd wanna define a Cron task that starts when the application starts, runs everyday at middle night, and closes when the application closes.  I've tested CronJobs in controllers' routes, and it works fine. but I don't wanna have to call the backend to start it. How can I do this?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
