### ISSUE TITLE
Misleading comment in templates/config/hash.txt: argon is the default hash

### ISSUE THREAD

**Issue by yann-yinn** [adonisjs/core#3169]
It seems there a mistake here: https://github.com/adonisjs/core/blob/develop/templates/config/hash.txt#L26

The default value for hashing is argon, but the comment says this is bcrypt.

I can do a PR if this is an error.

**Comment by thetutlage** [comment]
Yup. It is an issue with the comment. feel free to send a pr to fix the comment
