### ISSUE TITLE
Built-in support for polymorphism in lucid

### ISSUE THREAD

**Issue by CodeArtisT75** [adonisjs/core#3175]
## Why this feature is required (specific use-cases will be appreciated)?
many databases use polymorphism in their design for better storage. you may see examples in many apps. but for a simple example consider we have two models (with table names).

- User (users table)
- Post (posts table)

every user and post can be reported. one solution is to design separated tables (and models) for reporting user and reporting posts:

- UserReport (user_report table)
- PostReport (post_report table)

but a better way (in many applications) is to use one model for the report and use polymorphism in the database level:

- User
- Post
- Report

this design is better for indexing, storing, and etc on reports in the above example. for example, we can index all reports in a more efficient way.

there are many ORM and frameworks that use this type of relations. for example, you can see it in Laravel Eloquent:
[https://laravel.com/docs/8.x/eloquent-relationships#polymorphic-relationships](https://laravel.com/docs/8.x/eloquent-relationships#polymorphic-relationships)

or bookshelf.js in node.js environment:
[https://bookshelfjs.org/tutorial-polymorphic.html](https://bookshelfjs.org/tutorial-polymorphic.html)

also, there is an outdated package for adonis.js V4 but it is dead now for V5 :)
[https://github.com/enniel/adonis-lucid-polymorphic](https://github.com/enniel/adonis-lucid-polymorphic)

an example for the syntax maybe look likes:

```ts
// User Model
export default class User extends BaseModel {
  @column()
  public id: string;

  @column()
  public name: string;

  // other properties

  @morphMany(() => Report)
  public reports;
}

// Post Model
export default class Post extends BaseModel {
  @column()
  public id: string;

  @column()
  public title: string;

  // other properties

  @morphMany(() => Report)
  public reports;
}

// Report Model
export default class Report extends BaseModel {
  @column()
  public id: string;

  @column()
  public morphableId: string;

  @column()
  public morphableType: string;

  @morphMany(() => [User, Post])
  public reports;
}
```

and finally, thanks for the Awesome Adonis.js ❤

## Have you tried any other work arounds?
yes, but my code became so messy and there is no other 3rd party package or any guide on the internet.

## Are you willing to work on it with little guidance?
I really want to help but I'm not an expert in coding (specially in TypeScript). So my answer is no.

**Comment by lustan3216** [comment]
@thetutlage  is there any change to support this?  or any alternative way to do it?
