### ISSUE TITLE
Route.makeSignedUrl not working inside command

### ISSUE THREAD

**Issue by fchenhau** [adonisjs/core#3212]
## Prerequisites
1. adonis make command
2. inside the command run(), generate route using Route.makeSignedUrl()
3. When run command, it returns error message `RouterException: E_CANNOT_FIND_ROUTE: Cannot find route for "test" identifier` where "test" is the route name

## Package version
"@adonisjs/auth": "^8.0.9",
"@adonisjs/core": "^5.3.4",
"@adonisjs/lucid": "^16.0.2",
"@adonisjs/repl": "^3.1.6",

## Node.js and npm version
Node => v16.6.0
npm => 7.19.1

## Sample Code (to reproduce the issue)
routes.ts
```
Route.get('/', async () => {
  return 'Hello World'
}).as('test')
```

commands/testCommand.ts
```
public async run() {
    const { default: Route } = await import('@ioc:Adonis/Core/Route')
    Route.makeSignedUrl(
         'test',
         {},
        {
          expiresIn: '5m',
        }
    )
}
```

**Comment by thetutlage** [comment]
Answered here https://github.com/adonisjs/http-server/issues/47
