### ISSUE TITLE
Queue system 

### ISSUE THREAD

**Issue by LemarinelNet** [adonisjs/core#3244]
Continuing #123 , I think we should work seriously on queues.

I'm switching from Laravel, and I used queued jobs a lot.

I've started to seek around for adonis-ready wrappers, but haven't found many things : 
Adonis-Kue was a good candidate, but kue is not maintained anymore
Bull seems to be a nice (huge) candidate also, with a wrapper ready for Adonis 5, but it seems to only supports Redis. I was searching for something that could work with the same DB as the app (not all app queues needs such a big system as Redis for small queues....)

Another possible "messaging system" to think about could also be Amazon SQS : if Adonis wants to go the Serverless way (which I think is a good idea...), having SQS might be a great argument in favor of Adonis ?

I might be able to help if needed.

**Comment by thetutlage** [comment]
Currently in the short term ( next few months ) I have no plans to myself work on a queue system with multi-driver support. I will continue to recommend Bull, as that is the only good solution we have in the Node world.

I will close this issue for now, as there is no immediate action I can take.

Thanks for sharing your ideas :)
