### ISSUE TITLE
Deploying always loops back to this issue: E_INVALID_FLAG: Unknown flag "production"

### ISSUE THREAD

**Issue by mckayze** [adonisjs/core#3257]
## Package version
"5.3.0"

## Node.js and npm version
14.17.0 - 8.0.0

## Sample Code (to reproduce the issue)
This issue isn't code specific it seems as though its just with deployment.

## Problem
When deploying i get the following logs which i initially thought was connected to digitalocean but when i used another service and got the same issue i figured out it may be an adonis problem.

```
[2021-10-17 22:54:49] > node ace build --production
[2021-10-17 22:54:49] 
[2021-10-17 22:54:50] [ error ]  E_INVALID_FLAG: Unknown flag "production"
[2021-10-17 22:54:50] ERROR: failed to build: exit status 1
[2021-10-17 22:54:50] building: exit status 1
[2021-10-17 22:54:56] 
[2021-10-17 22:54:56] For documentation on the buildpacks used to build your app, please see:
[2021-10-17 22:54:56]    Node.js: https://do.co/apps-buildpack-node
[2021-10-17 22:54:56] 
[2021-10-17 22:54:56]  ! Build failed (145)
```

I've switched from initially using Yarn which this issue happened with to using NPM and i still get the same error message. It sometimes happens on re-builds and not on the initial build. There doesn't seem to be any pattern (that i can recognise at least) to when it happens.

The issue seems to be that the build function isn't found `node ace build` when i replace `npm run build` with `node ace build` it says that build is not found. And logging out a `node ace` during the build process doesn't show the build command at all while locally it does.

I tried to get a solution on discord and someone mentioned that running `npm i` twice worked for them, i tried this but it didn't work with both yarn and npm.

**Comment by thetutlage** [comment]
Can you please share how do you upload your project to the production server and how do you install dependencies there?

**Comment by mckayze** [comment]
Hey thanks for replying,

I upload my project to gitlab first, then i choose the branch from DO's apps services. 
To install  / build dependencies we run `npm run build`
Afterwards we run `npm run start:production` which runs this command `node build/server.js` (this works locally for reference)

**Comment by thetutlage** [comment]
I still don't have clarity to the complete process. But anyways, this is happening because the `@adonisjs/assembler` is not installed on your deployment server.

The package is a development dependency and it seems like your server is installing only production dependencies. This happens when `NODE_ENV` is set to production or either you are using `--production` flag with the npm install command.

Also, this is not an issue. So I will recommend discussing it on the Discussions forum. The issues tracker is for tracking verified bugs only.
