### ISSUE TITLE
5 high severity vulnerabilities

### ISSUE THREAD

**Issue by FrenchNicko** [adonisjs/core#3333]
## Package version
Adonisjs 5
"@adonisjs/auth": "^8.0.10",
"@adonisjs/core": "^5.4.0",
"@adonisjs/lucid": "^16.3.2",
"@adonisjs/repl": "^3.1.7",

## Node.js and npm version
Node.js: v17.0.1
Npm: 8.1.0

## Sample Code (to reproduce the issue)
- Install Adonisjs as an API.
- Install the @adonisjs/lucid and @adonisjs/auth packages

The warning below occurs after installing @adonisjs/auth: 

5 high severity vulnerabilities

Here is the report:

```
# npm audit report

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
No fix available
node_modules/fast-glob/node_modules/glob-parent
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/fast-glob
    globby  8.0.0 - 9.2.0
    Depends on vulnerable versions of fast-glob
    node_modules/globby
      cpy  >=7.0.0
      Depends on vulnerable versions of globby
      node_modules/cpy
        @adonisjs/assembler  *
        Depends on vulnerable versions of cpy
        node_modules/@adonisjs/assembler

5 high severity vulnerabilities
```

**Comment by RomainLanz** [comment]
There's nothing to be done here and those are irrelevant to any production code.

**Comment by David-Baron** [comment]
Same think today november 5 22, 
whith fresh install adonis web
on install lucid (only):
```
npm i @adonisjs/lucid
added 19 packages, and audited 717 packages in 18s
66 packages are looking for funding
  run `npm fund` for details
5 high severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
```

**Comment by RomainLanz** [comment]
Same answer.
