### ISSUE TITLE
Miidlware error returning \"id\" into :7 - ora-00904: \"id\": invalid identifier"

### ISSUE THREAD

**Issue by luckybuy** [adonisjs/core#3354]
## Node.js and npm version
14.7.3

## Sample Code (to reproduce the issue)
const token = await auth.use('api').generate(user)

## BONUS (a sample repo to reproduce the issue)
I found the reason in this file at row 116:
C:\project\adonis\node_modules\@adonisjs\auth\build\src\TokenProviders\Database\index.js
116: const [persistedToken] = await client.table(this.config.table).insert(payload).returning('id');
For oracledb alway return column name in upper case. But in your code you hardcode column in lower case. Lower case for mysql db ok. But for oracledb must be uppper case.
So please dont hardcode returning('id'). The read function also meet the same error when you check if (!tokenRow || !tokenRow.token) tokenRow.token for mysql is ok. But for oracledb must be: tokenRow.TOKEN
Maybe you do like this:
 async write(token) {
            const client = this.getQueryClient();
            /**
             * Payload to save to the database
             */
            if (client.connectionName == 'oracle') {
                            const payload = {
                                [this.foreignKey]: token.userId,
                                NAME: token.name,
                                TOKEN: token.tokenHash,
                                TYPE: token.type,
                                EXPIRES_AT: '', //token.expiresAt ? token.expiresAt.toFormat(client.dialect.dateTimeFormat) : null,
                                CREATED_AT: luxon_1.DateTime.local().toFormat(client.dialect.dateTimeFormat),
                                ...token.meta,
                            };
                            const [persistedToken] = await client.table(this.config.table).insert(payload).returning('id');
                            return String(persistedToken);
                        } else {
                            const payload = {
                                [this.foreignKey]: token.userId,
                                name: token.name,
                                token: token.tokenHash,
                                type: token.type,
                                expires_at: '', //token.expiresAt ? token.expiresAt.toFormat(client.dialect.dateTimeFormat) : null,
                                created_at: luxon_1.DateTime.local().toFormat(client.dialect.dateTimeFormat),
                                ...token.meta,
                            };
                            const [persistedToken] = await client.table(this.config.table).insert(payload).returning('id');
                            return String(persistedToken);
                        }
}

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by luckybuy** [comment]
@thetutlage 
I am very sorry when heard you said that i make waste of your time.
1. Make sure that you are only reporting bugs or submitting feature requests on Github.
>>> I am sure this is bug
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.
>>> I am sure this is bug. Not feature requests.
Before post this bug i already search to check any bug similar my bug. I cannot found any bug report similar my bug so i make this bug report.
When i report bug i follow your template and i write the issue clearly. As you see i debugging to right the line of code it make issue and copy that code to here. 
I dont know you read my bug report carefully? I think you never test you framework adonisjs 5.0 with oracle database with middleware using api.
Please say in what i was wrong when i make this bug report?
Anyway thank you so much for adonis 4.0. I use it for long time with nuxtjs+vuejs for frontend. It very cool!

**Comment by thetutlage** [comment]
I don't read any issues which are not formatted properly. So if you need help you need to put efforrs to format your coodeblocks and also provide enough information that can be used to reproduce the issue.

Also, this is not customer support that I will try every possible way to find information. Instead you have to make sure that your issues are easy to reproduce

**Comment by luckybuy** [comment]
Thanks for your reply quickly.
I never think you are customer support. Because i dont pay you anything.
I think i must have the duty report bug to help you fix bug to improve the framework.
I follow report bug template: 
Package version
Node.js and npm version
14.7.3

Sample Code (to reproduce the issue)
const token = await auth.use('api').generate(user)

BONUS (a sample repo to reproduce the issue)
......
I am sorry. It still make you cannot understand my bug report.
