### ISSUE TITLE
Please add a method Arr::get    

### ISSUE THREAD

**Issue by aogg** [adonisjs/core#3363]
laravel data_get
laravel Arr::get

https://laravel.com/api/8.x/Illuminate/Support/Arr.html#method_get

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
