### ISSUE TITLE
Add support for Malloy language

### ISSUE THREAD

**Issue by ansarizafar** [adonisjs/core#3364]
Malloy postgresdb support is coming next month but Malloy only allow querying database, writes are not supported. It would be great If somehow we can use Malloy with Adonisjs

https://github.com/looker-open-source/malloy

**Comment by RomainLanz** [comment]
Hey @ansarizafar! 👋🏻 

Nothing stops you from installing Malloy and using it inside your application.
Closing since this is not an issue with the framework itself, and it is not a feature we want to integrate at the core of Adonis.
