### ISSUE TITLE
Route param matcher for uuid() is case sensitive

### ISSUE THREAD

**Issue by nogamenofun98** [adonisjs/core#3385]
## Why this feature is required (specific use-cases will be appreciated)?
Route.matchers.uuid() is checking the route parameter with case-sensitive, but the uuid should be also valid even though the alphabet in the uuid string is lower case. I saw the .uuid() return a "/^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/" string

**Comment by thetutlage** [comment]
Waiting for some to create a PR for this https://github.com/adonisjs/http-server/issues/50
