### ISSUE TITLE
Problom with aggregation [V5]

### ISSUE THREAD

**Issue by pk4all** [adonisjs/core#3397]
### Discussed in https://github.com/adonisjs/core/discussions/3387

<div type='discussions-op-text'>

<sup>Originally posted by **pk4all** December  3, 2021</sup>
"sum" Not working with "withAggregate" with this query

My query is
```
q.withAggregate('operations',otq=>{
                            otq
                            .pojo<{totalOprationTime:number}>()
                            .sum('time_in_mintues * occurance').as('totalOprationTime')
                          })
```
Please help me. @thetutlage @McSneaky @RomainLanz 
Thanks;</div>

**Comment by thetutlage** [comment]
"Not working" does not explain anything. Please create proper threads with the expectations, the actual outcome and any errors that you have received.

You wouldn't even have to create an issue, if you have provided all the information within the discussion thread.
