### ISSUE TITLE
If database is down, validator should response status code 50x

### ISSUE THREAD

**Issue by ivyxjc** [adonisjs/core#3400]
## Package version

5.4.1

## Node.js and npm version

{
  npm: '8.1.3',
  node: '16.11.1',
}

## Sample Code (to reproduce the issue)

```typescript
  public async register({ request, response }: HttpContextContract) {
    const creatUserSchema = schema.create({
      email: schema.string({ trim: true }, [
        rules.email(),
        rules.unique({
          table: 'users',
          column: 'email',
        }),
      ]),
      password: schema.string({ trim: true }),
    })
    const payload = await request.validate({ schema: creatUserSchema })
    payload.email = payload.email.toLowerCase()
    const user = await User.create(payload)
    if (user.$isPersisted) {
      response.status(201).send(user)
    } else {
      response.status(502)
    }
  }

```
If database is down, it will return the following response and print fatal log.

```json
code： 422
{
    "errors": [
        {
            "rule": "unique",
            "field": "email",
            "message": "unique validation failure"
        }
    ]
}
```

I think that it may should response http status 50x.

**Comment by thetutlage** [comment]
Leaking the database errors to the end user is not a great idea. However, the validator does report these errors using the framework logger at `fatal` level. So please check the logs on the terminal or the log reporting service (if you are using any)

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
