### ISSUE TITLE
edge: dot "." based path seperators are depricated, We recommend using "/" instead Deprecation\Warning

### ISSUE THREAD

**Issue by mistidinzy** [adonisjs/core#3412]
### Discussed in https://github.com/adonisjs/core/discussions/2021

<div type='discussions-op-text'>

<sup>Originally posted by **theashywolf** December  8, 2020</sup>
![image](https://user-images.githubusercontent.com/31142505/101454162-dc997980-3973-11eb-8876-1c90da8de822.png)

---

(Using image from someone else's discussion.)
When watching a presentation on Adonis today, noticed that there is a typo here.
"Seperators" should be _separators_.

**Comment by thetutlage** [comment]
Is this an issue to fix the spelling?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
