### ISSUE TITLE
Validate many files

### ISSUE THREAD

**Issue by kouraf** [adonisjs/core#3419]
## Why this feature is required ?
Uploading many files

## Have you tried any other workarounds?
Doing the validation manually like checking the extensions, the size ...etc 

## Are you willing to work on it with little guidance?
Yes, gladly !

**Comment by thetutlage** [comment]
Use schema.array https://docs.adonisjs.com/reference/validator/schema/array

Please use the discussion forum to ask questions. The issues tracker is for reporting verified bugs
