### ISSUE TITLE
Setting DRIVE_DISK=s3 as default driver in .env throws an error

### ISSUE THREAD

**Issue by ad-on-is** [adonisjs/core#3432]
### This does not work
```bash
DRIVE_DISK=s3
```

```js
await Drive.getSignedUrl('/path/file.txt')
```

Thrown error: `E_INVALID_ENV_VALUE: Value for environment variable "DRIVE_DISK" must be one of "local", instead received "s3"`

Although the **documentation** says the following:

> disk
The disk property represents the default disk to use for file system operations. Usually, you will define the disk as an environment variable to use different disks for local development and production.

### This works

```bash
DRIVE_DISK=local
```

```js
const s3 = Drive.use('s3')
await s3.getSignedUrl('/path/file.txt')
```

## Question
Is this intentional behavior, or did I miss something? `config/drive.ts` and `contracts/drive.ts` are setup propperly.

**Comment by thetutlage** [comment]
The error comes from the environment variables validator. You can learn more about it here https://docs.adonisjs.com/guides/environment-variables#validating-environment-variables

Make sure that your validation enum allows `s3`

```ts
DRIVE_DISK : Env.schema.enum(['local', 's3'])
```
