### ISSUE TITLE
Missing body input when using schema.array() with schema.object() as it's member

### ISSUE THREAD

**Issue by nogamenofun98** [adonisjs/core#3435]
## Package version
@adonisjs/core@5.4.1

## Node.js and npm version
node: 17.1.0
npm: 8.1.2

## Sample Code (to reproduce the issue)
```
this.schema = schema.create({
	name: schema.string({ trim: true, escape: true }, [rules.exists({ table: 'platforms', column: 'name', where: { deleted_at: null } })]),
	images: schema.array().members(
		schema.object().members({
			is_banner: schema.boolean(),
			image: schema.file({
				size: '10mb',
				extnames: ['jpg', 'jpeg', 'png', 'heif', 'bmp', 'tiff', 'webp'],
			}),
		})
	),
})
```
![image](https://user-images.githubusercontent.com/9070825/146871340-7e6e36ef-d8bd-484b-8fb9-81aadfec79f4.png)

When using postman to call this api, i saw the ctx.request.all() and ctx.request.allFiles() both contain the data I pass into it. 
```
let all = ctx.request.all()
let allFiles = ctx.request.allFiles()
const data = {
	...ctx.request.all(),
	...ctx.request.allFiles(),
	params: ctx.params,
}
```
![image](https://user-images.githubusercontent.com/9070825/146871572-64ff87c5-e5ec-4f7f-98e0-3e35ccb706ea.png)
but after merge, the "is_banner" field will be override by the "image" field. 

The merging code I write is to demo the adonis core code: 
![image](https://user-images.githubusercontent.com/9070825/146871730-ed983140-abb5-4a28-8ddb-bc254a99a4ce.png)
which perform the same as I tested, maybe need to have a nested loop when merging object so the array wont lost it data.

**Comment by nogamenofun98** [comment]
https://www.geeksforgeeks.org/lodash-_-merge-method/#:~:text=Example%202%3A%20%C2%A0,Javascript

maybe something like the Example 2 in this website.

**Comment by thetutlage** [comment]
Yeah, that may need a deep merge. What you can do instead is to define a custom data property within the validator.

```ts
import lodashMerge from "lodash.merge"


public data = lodashMerge({}, this.ctx.all(), this.ctx.allFiles())
```

Since deep merge can have performance implications. I will prefer not doing it within the framework codebase. Also, the deep merge depth may need to be configured and that is another config value to manage.

So, the best way to self provide the data for the validation.

**Comment by nogamenofun98** [comment]
ok noted, thx for the explaination. :D

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by Joan1590** [comment]
Thank you!!
