### ISSUE TITLE
"for loop" in edge template

### ISSUE THREAD

**Issue by faizananwerali** [adonisjs/core#3436]
This issue has already been raised here [https://github.com/adonisjs/core/issues/789](https://github.com/adonisjs/core/issues/789), but it was close because the issue was resolved.

Here is the thing, the accepted answer shared the link, which is now dead.

https://edge.adonisjs.com/docs/iteration

![image](https://user-images.githubusercontent.com/12691366/146960650-dd3d50f8-bbe1-4496-af8e-03257e5706ee.png)

What worse is that the [official documentation](https://docs.adonisjs.com/guides/views/loops) also don't mention anything about for loop. It only shows examples of foreach loop.

![image](https://user-images.githubusercontent.com/12691366/146961107-251690da-e8e3-44ad-9507-c0356f26b184.png)

**Comment by thetutlage** [comment]
<img width="714" alt="CleanShot 2021-12-22 at 07 01 58@2x" src="https://user-images.githubusercontent.com/1706381/147019713-65336408-ec8a-43e5-998d-28e02a53016b.png">

Search for `each` loop. And please do not open unnecessary issues. There is no guarantee that your terms will match documentation terms as well. Try to search with broader terms or just navigate the docs normally

**Comment by faizananwerali** [comment]
I know there is documentation for the 'Each' loop, but this doesn't work like 'for loop'.

for (I=0; I <= 10; I++) { }

How would you use this in 'Each Loop'?

It's a necessary question.

**Comment by faizananwerali** [comment]
For anyone come here and disappointed by the developer answer.

I found a solution with totally different approach.

Create a Preload file. (select http only)
[https://docs.adonisjs.com/guides/adonisrc-file#preloads](https://docs.adonisjs.com/guides/adonisrc-file#preloads)

    node ace make:prldfile view

.adonisrc.json

    {
      "preloads": [
        "./start/routes",
        "./start/kernel",
        {
          "file": "./start/view",
          "optional": false,
          "environment": [
            "web"
          ]
        }
      ],
    }

install underscore.js
[https://underscorejs.org/](https://underscorejs.org/)

    npm install underscore

import underscore library as global in start/view.ts
[https://docs.adonisjs.com/guides/views/data-flow#globals](https://docs.adonisjs.com/guides/views/data-flow#globals)

    import View from '@ioc:Adonis/Core/View'
    import _ from 'underscore'
    
    View.global('_', _)

Now you can use it in view using @each tag.
[https://docs.adonisjs.com/guides/views/data-flow#usage](https://docs.adonisjs.com/guides/views/data-flow#usage)
[https://docs.adonisjs.com/guides/views/loops](https://docs.adonisjs.com/guides/views/loops)

    @each(num in _.range(5, 15))
      <li> {{ num }} </li>
    @end

    @each((num, index) in _.range(5, 15))
      <li> {{ index }} {{ num }} </li>
    @end

**Comment by thetutlage** [comment]
If you read the issue opening guidelines, you can see that you should use the discussions forum to ask questions and not report them as bugs until it is verified.

Deal with a comment with iron fist is not really going to help. At the end of the day you do not pay me to answer your every question.
