### ISSUE TITLE
microservices

### ISSUE THREAD

**Issue by DanaCoding** [adonisjs/core#3449]
## Why this feature is required (specific use-cases will be appreciated)?

I compared multiple node.js server frameworks. I feel that Adonis is very friendly to developers, and the document structure is also great. Just look at the document structure to know how to implement the server-side project.
But there seems to be a lack of support for microservices. If it is possible, will this feature be considered? If not, why?

**Comment by fenibofubara** [comment]
I am seriously waiting for a micro service support on Adonis Js @thetutlage please this request be considered so we dont have to start looking else where. Woukd also love to be notified immediately its available. Thanks @thetutlage

**Comment by thetutlage** [comment]
Hello 👋

Assuming you are into building micro-services, how does your workflow looks like right now when creating micro services?

**Comment by fenibofubara** [comment]
I am about building my first micro service and I want to use Adonis
framework for it

**Comment by thetutlage** [comment]
> I am about building my first micro service and I want to use Adonis

Great! I suggest to start working on your app and then maybe have a feature request which is more specific. "micro-services" itself is a broader concept, So I don't know what exactly you want from me

**Comment by fenibofubara** [comment]
Owk. I understand micro service is a broad concept. Maybe what I just need
is a simple screen cast of how it can be implemented even if it's in the
most basic level, just as we have resources on micro service using
'express'. I would really appreciate if something can come up

**Comment by RomainLanz** [comment]
Closing since not actionable.
