### ISSUE TITLE
Localized urls for multilanguage website (same as mcamara / laravel-localization)

### ISSUE THREAD

**Issue by ElyesaErgezenPXL** [adonisjs/core#3460]
Is there a way or a package that we can use for localized urls in AdonisJS v4.1 just like in Laravel?

Example of prefixing language:
instead of
```javascript
Route.get('/', 'IndexController.index') -> Dutch
Route.get('/en', 'IndexController.index') -> English
Route.get('/fr', 'IndexController.index') -> French
```
this
```javascript
Route.group(() => {
    Route.get('/', 'IndexController.index')
}).prefix(LANG-PREFIX)
```
Laravel
```php
Route::group(['prefix' => LaravelLocalization::setLocale()], function(){
    Route::get('/', 'IndexController@index');
});
```

Example of translated url:
```javascript
Route.get('/artikelen', 'IndexController.index') -> Dutch
Route.get('/en/articles', 'IndexController.index') -> English
Route.get('/fr/des-articles', 'IndexController.index') -> French
```

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
