### ISSUE TITLE
VS code theme

### ISSUE THREAD

**Issue by PabloMelo11** [adonisjs/core#3469]
What VS-code theme was used for post-documentation?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by PabloMelo11** [comment]
I didn't know exactly where to ask a question :)

Thanks
