### ISSUE TITLE
one user create one api token 

### ISSUE THREAD

**Issue by prashant19914** [adonisjs/core#3509]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

## Consider an RFC

Please create an [RFC](https://github.com/adonisjs/rfcs) instead, if

- Feature introduces a breaking change
- Demands lots of time and changes in the current code base.

*Delete the above section and the instructions in the sections below before submitting*

## Why this feature is required (specific use-cases will be appreciated)?
delete old api token when user create new token

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
