### ISSUE TITLE
Preserve files on "build" folder

### ISSUE THREAD

**Issue by yuridamata** [adonisjs/core#3521]
When a run the build command, the entire "build" folder is cleared. I my case, i use the the "Public" folder to save some uploaded images from my users. My suggestion is to create a way to choose some folders/files to be preserved on build.

I solved my problem by moving my uploads folder to another place and creating a Symlink to it, but would be nice to have an official solution to it.

Obs: Sorry for bad English, not a native speaker.

**Comment by thetutlage** [comment]
I think creating the symlink is the best way to manage user uploaded files. I myself do it all the time and also it allows me to run multiple copies of my code (horizontally scaled) and all writing on this one central user uploads directory.

Also, for now I will not change the way build is generated :)

**Comment by w3bsite** [comment]
I'm sorry to bring this up, can you kindly show me how to use this method for using public folder with symlink I'm having a hardtime with bulding for production for this reason.
