### ISSUE TITLE
Response from validator can't be used to create new record (without additional stuff)

### ISSUE THREAD

**Issue by n4an** [adonisjs/core#3540]
## Package version
5

## Node.js and npm version
16

## Sample Code (to reproduce the issue)
I have CreateUserValidator

  public schema = schema.create({
    birth_day: schema.date({ format: 'yyyy-MM-dd HH:mm:ss' },
    []),
  })

Model

export default class User extends BaseModel {
    @column({ isPrimary: true })
    public id: number

    @column()
    public birthDay: DateTime
}

And can't save use, error ER_WRONG_VALUE_COUNT_ON_ROW

  const userDetails = await request.validate(CreateUser)
  const user: User = new User()
  user.birthDay = userDetails.birth_day
  user.save()
 
request.input('birth_day')?
with user.birthDay = request.input('birth_day') work

**Comment by thetutlage** [comment]
The code blocks are badly formatted. Please format them properly and create the issue in the correct repo.

The more you respect our time, the easier it will be for us to help you

**Comment by n4an** [comment]
@thetutlage I think the problem was that I not write  @column.dateTime() but only   @column()

And in migration added  { useTz: true } (table.timestamp('birth_day', { useTz: true })) was table.timestamp('birth_day').

```
  @column.dateTime()
  public birthDay: DateTime
```
