### ISSUE TITLE
string.prettyMs() has no option to show x digits after dot and to work with dot and comma (17,77 and 17.77)

### ISSUE THREAD

**Issue by n4an** [adonisjs/core#3541]
string.prettyMs() has no option to show x digits after dot and to work with dot and comma (17,77 and 17.77)

**Comment by thetutlage** [comment]
The feedback is same as https://github.com/adonisjs/core/issues/3542

**Comment by n4an** [comment]
@thetutlage 
method string.prettyMs() not accept string '0,777777777' for example

Event.on('db:query', (data) => {
  if (Application.inProduction) {

    let duration = data.duration ? parseFloat(data.duration.join('.')) : 0    //  parseFloat
    duration = string.prettyMs(duration, { long: true }),    // and show 0.7777777777 ms and not 0.78 ms

    Logger.info(i18n.formatMessage('event.query.executed', duration))
  } else {
    Database.prettyPrint(data)
  }
})
