### ISSUE TITLE
string.prettyMs(duration, { long: true }) add separator between value and unit and not full unit name. separator do nothing

### ISSUE THREAD

**Issue by n4an** [adonisjs/core#3542]
string.prettyMs(duration, { long: true }) add separator between value and unit and not full unit name

separator option not work

**Comment by thetutlage** [comment]
I see you have created multiple issues for the same thing. Also, you have not followed the issue creation template.

- Please create a single issue. 
- Properly define the issue you are facing. 
- Do share code samples. 
- Share the actual and expected outcome both.

**Comment by n4an** [comment]
@thetutlage 

string.pretyMs(0.99999, { long: true }) return 0.99999 ms but need to be 0.99999 milliseconds 

string.prettyMs(0.99999, { separator: ' ' }) return 0.99999ms but need to be 0.99999 ms
