### ISSUE TITLE
toSentence an options for all separators

### ISSUE THREAD

**Issue by n4an** [adonisjs/core#3543]
You can also define the following options to customize the separators.

separator: The value between two words except the last one.
pairSeparator: The value between the first and the last word. Used, only when there are two words.
lastSeparator: The value between the second last and the last word. Used, only when there are more than two words.

and
universalSeparator - optional and set the same for separator,  pairSeparator and lastSeparator

And if that make a sentence it can have and a option for final char, for example: , . ? ! : ;

Now is need to use template literals or  concatenation

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by n4an** [comment]
@thetutlage 
if is need the same separator is need to pass all 3 options?
now is need to use template literals or concatenation to add dot at end of sentence
