### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by babakfp** [adonisjs/core#3614]
Hi
There are 2 problems:
1- I shouldn't receive the node_modules folder and files when I create an adonis project
2- I shouldn't receive the `package-lock.json` file when I create the app with `pnpm`

The second problem will be fixed automatically if Adonis only ships the source files instead of installing them.

**Comment by thetutlage** [comment]
Can you share what exactly the problem you have? And please share more context around what you expect when using `pnpm`. Please do not assume that I know and use `pnpm`.

**Comment by babakfp** [comment]
Right

I installed Adonis via this command:

```
pnpm create adonis-ts-app hello-world
```
and this is the result:

![Screenshot 2022-03-07 021701](https://user-images.githubusercontent.com/44144724/157012454-ff77fc39-13de-40d8-adab-d55e6c8775e0.png)

There are 2 items that I highlighted.

- `node_modules` folder
- `package-lock.json` file


## About `package-lock.json`

Only *NPM* uses the `package-lock.json` file. `package-lock.json` file gets created when you install your project deps via *NPM*.  If I'm not mistaken, *Yarn* uses `yarn.lock` and *PNPM* uses `pnpm-lock.yaml`. For the users that use PNPM or Yarn, the `package-lock.json` file is just a piece of junk. So, if the user installs Adonis via Yarn or PNPM, they shouldn't receive the `package-lock.json` file. 

## About `node_modules` folder

Adonis installation takes a while because it creates the source files and it installs the deps. It's better if Adonis only creates the source files. In this way, the installation will happen in a matter of seconds. Later users can easily install the deps.

**Comment by TiBianMod** [comment]
I'm also using `pnpm` and I always remove the `node_modules` and `package-lock.json` and then run pnpm install. So yes is a little annoying !!!

**Or** you can make configurable the task `installDependencies` and let the user choose if he wants to install the dependencies or not.

**Or** you can make configurable which package manager (npm, yarn or pnpm) will be used.

**Comment by thetutlage** [comment]
Okay make sense. I don't use `pnpm`, so may not be the best person to implement. How about someone creating a PR for it?

**Comment by RomainLanz** [comment]
It is already implemented, so I believe it is more a bug than a new feature to have.

I don't understand why the CLI uses `npm` to install when it is ran with `pnpm`.

https://github.com/adonisjs-community/create-adonis-ts-app/commit/1e25f6f84abaa237ba48c65027b7bb1d6b6c1de7

**Comment by thetutlage** [comment]
@RomainLanz Can you check why and fix it?

**Comment by babakfp** [comment]
Cool

What about not installing the deps automatically? As an example, you can install [this app](https://kit.svelte.dev/docs/introduction#getting-started) to see how convenient it is to receive the files in a matter of seconds.

**Comment by babakfp** [comment]
Currently, you receive the files in a matter of seconds too.
I don't really know.
I like to see the installation process end as soon as possible but I also remember the times that I installed SvelteKit (it doesn't install the deps automatically like Adonis) and when I run `pnpm dev`, It showed me an error because I forgot that I should install the deps first!.
Adding a new option also has its cons because of how beginners going to interact with it and also it's an extra step for everyone, each time that they install Adonis. It's also going to need some code to add this new option...

😂😅 let's don't do anything then

**Comment by TiBianMod** [comment]
How about having a extra option when you creating a new adonis-app?


CUSTOMIZE PROJECT
❯ Select the project structure · web
❯ Enter the project name · adonisjs
❯ Setup eslint? (y/N) · false
❯ Configure webpack encore for compiling frontend assets? (y/N) · false
❯ Install Dependencies? (y/N) · false (default to true)

**Comment by Julien-R44** [comment]
I don't really understand the point of not installing the dependencies directly. What's the difference? Once the installation is finished you should make a cd my-app && npm install, so what's the point of doing that ?

Anyway, if we have to implement this feature, I would prefer to add a new prompted choice rather than a flag. 
I can look at it today

**Comment by Julien-R44** [comment]
About PNPM not being used :
https://github.com/pnpm/pnpm/issues/3505

We rely on npm_execpath to determine the package manager used and pnpm init / create / dlx / exec does not seem to set it.

A workaround : 
```
npm_execpath=pnpm pnpm init adonis-ts-app hello-world
```
I'll see if I can't find a better solution, otherwise I'll add this in the documentation
Another solution would be to use a --pnpm flag. Any preferences ? @RomainLanz @thetutlage

**Comment by thetutlage** [comment]
@RomainLanz knows better than me about package managers. So I will let him decide how to proceed with it

**Comment by RomainLanz** [comment]
We can probably do a different check than `npm_execpath` to know if `pnpm` is in used.

**Comment by thetutlage** [comment]
Closing the issue for now. Anyone who uses pnpm actively should send a PR.
