### ISSUE TITLE
Install Adonis in current working directory

### ISSUE THREAD

**Issue by babakfp** [adonisjs/core#3617]
Hi

I want to be able to [install Adonis](https://docs.adonisjs.com/guides/installation#creating-a-new-project) in the current working directory.

## Example

When I want to [install SvelteKit](https://kit.svelte.dev/docs/introduction#getting-started), I can add the source files to the current working directory by not passing the project name like this:

```
# Instead of this:
npm init svelte@next my-app-name

# I can do this:
npm init svelte@next
````

![Screenshot 2022-03-08 033336](https://user-images.githubusercontent.com/44144724/157230558-44e3f119-6c65-4ce7-ad29-35aa27c691cd.png)

(Here, you can use the entered value as the project name too)

## Alternative

1. Inter the command `npm init adonis-ts-app@latest hello-world`
2. Close the current working directory `ctrl`+`k` `f`
3. Open the app directory `ctrl`+`k` `ctrl`+`o`

**Comment by galaczi** [comment]
How about `npm init adonis-ts-app@latest .`?

**Comment by babakfp** [comment]
> How about npm init adonis-ts-app@latest .?

Oh, this works👏. I didn't know about it until now (thanks). However, when I tried [SvelteKit](https://kit.svelte.dev/docs/introduction#getting-started), subconsciously I know that this `npm init svelte@next` is gonna do what I want(it's gonna create the project in the current working directory). So, I vote for this `npm init adonis-ts-app@latest` over this `npm init adonis-ts-app@latest .`

**Comment by RomainLanz** [comment]
Hey! 👋🏻 

I can't entirely agree here; if I do not specify any directory (`.` being a valid directory), I expect the CLI not to run and tell me it needs a directory.

I don't want the CLI to use the current directory to install my application magically.

**Comment by babakfp** [comment]
> I expect the CLI not to run and tell me it needs a directory.

But you are already inside a directory. And what you are doing with `npm init svelte@next` is installing the app in that current directory. You can think about it like you are using a function that has an argument with a default value.

If it's not gonna implemented, at least add `npm init adonis-ts-app@latest .` to docs because it's not common knowledge.

**Comment by thetutlage** [comment]
These kind of debates are usually subjective. So there is no right or wrong :) 

But I do agree, it can be mentioned within the docs. Feel free to open a PR for the same.
