### ISSUE TITLE
No node16 support?

### ISSUE THREAD

**Issue by niumowangorz** [adonisjs/core#3621]
`npm init adonis-ts-app@latest web-demo `  report an error

**Comment by RomainLanz** [comment]
Hey @niumowangorz! 👋🏻 

What is the error?
It is working fine with all latest releases of Node.js.

**Comment by niumowangorz** [comment]
Thank you for your reply.
I succeeded on Node14, but kept reporting this error on Node16.

```
28 verbose stack SyntaxError: Unexpected token '.'
28 verbose stack     at Object.compileFunction (node:vm:352:18)
28 verbose stack     at wrapSafe (node:internal/modules/cjs/loader:1032:15)
28 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1067:27)
28 verbose stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
28 verbose stack     at Module.load (node:internal/modules/cjs/loader:981:32)
28 verbose stack     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
28 verbose stack     at Module.require (node:internal/modules/cjs/loader:1005:19)
28 verbose stack     at require (node:internal/modules/cjs/helpers:102:18)
28 verbose stack     at Object.<anonymous> (C:\Users\1\AppData\Roaming\nvm\v16.14.0\node_modules\npm\lib\commands\init.js:7:17)
28 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1103:14)
30 verbose Windows_NT 10.0.19041
31 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init" "adonis-ts-app@latest" "hello-world"
32 verbose node v16.14.0
33 verbose npm  v8.3.1
34 error Unexpected token '.'
```

**Comment by RomainLanz** [comment]
I have no issue running the CLI with the same version as you do.

- When does this error happen, during the package installation, directly after using the command?
- What is the entire output of the command?

**Comment by leandro-angelo** [comment]
estou com o mesmo problema,

após rodar o comando 
npm i @adonisjs/auth

da esse erro

`
  TypeError 

 commandInstance.exec is not a function

 at Kernel.execMain D:/Leandro/web/zbin/zbin/node_modules/@adonisjs/core/node_modules/@adonisjs/ace/build/src/Kernel/index.js:201
  196|           */
  197|          await this.hooks.execute('before', 'run', commandInstance);
  198|          /**
  199|           * Execute command
  200|           */
> 201|          return commandInstance.exec();
  202|      }
  203|      /**
  204|       * Handles exiting the process
  205|       */
  206|      async exitProcess(error) {

   1  Kernel.handle
     D:/Leandro/web/zbin/zbin/node_modules/@adonisjs/core/node_modules/@adonisjs/ace/build/src/Kernel/index.js:528

   2  App.handle
     D:/Leandro/web/zbin/zbin/node_modules/@adonisjs/core/build/src/Ignitor/Ace/App/index.js:226

   3  Ace.handle
     D:/Leandro/web/zbin/zbin/node_modules/@adonisjs/core/build/src/Ignitor/Ace/index.js:33`

**Comment by RomainLanz** [comment]
> estou com o mesmo problema,
> 
> após rodar o comando npm i @adonisjs/auth
> 
> da esse erro
> 
> ` TypeError
> 
> commandInstance.exec is not a function
> 
> at Kernel.execMain D:/Leandro/web/zbin/zbin/node_modules/@adonisjs/core/node_modules/@adonisjs/ace/build/src/Kernel/index.js:201 196| _/ 197| await this.hooks.execute('before', 'run', commandInstance); 198| /_* 199| * Execute command 200| */
> 
> > 201|          return commandInstance.exec();
> > 202|      }
> > 203|      /**
> > 204|       * Handles exiting the process
> > 205|       */
> > 206|      async exitProcess(error) {
> 
> 1 Kernel.handle D:/Leandro/web/zbin/zbin/node_modules/@adonisjs/core/node_modules/@adonisjs/ace/build/src/Kernel/index.js:528
> 
> 2 App.handle D:/Leandro/web/zbin/zbin/node_modules/@adonisjs/core/build/src/Ignitor/Ace/App/index.js:226
> 
> 3 Ace.handle D:/Leandro/web/zbin/zbin/node_modules/@adonisjs/core/build/src/Ignitor/Ace/index.js:33`

You probably have an outdated version of Adonis (or Ace) or updated to V5 packages without updating your code.
Not related to this issue at all.

Also, do not expect people to speak your language. Please, speak in English.

**Comment by thetutlage** [comment]
Closing since not actionable
