### ISSUE TITLE
Force trailing slash

### ISSUE THREAD

**Issue by galaczi** [adonisjs/core#3624]
### Discussed in https://github.com/adonisjs/core/discussions/3600

<div type='discussions-op-text'>

<sup>Originally posted by **galaczi** February 28, 2022</sup>
Is there a way to force trailing slash for URLs? E.g. `/post` is not equal to `/post/` although Adonis handles them as the same.

I have this named route:
```
Route.get('/signup/', 'AuthController.signupShow').as('auth.signup.show')
```
Notice the slash at the end of the url. If I use `{{route('auth.signup.show')}}` I will get `/signup` without the slash.

Edit: in another example there is a trailing slash for some reason:

```
Route.group(() => {
    Route.get('/:page?/', 'PostsController.index')
      .as('index')
      .where('page', Route.matchers.number())
  })
    .prefix('/posts')
    .as('posts')
})
```
In this case `{{route('posts.index')}}` gives me `/posts/` with a slash, even if I remove the slash after `/:page?` parameter.</div>

**Comment by thetutlage** [comment]
Not something I want to focus on right now (given the time and work I already have). If you want to add support for this. I highly recommend starting with the RFC process and then opening a PR if the RFC is accepted.

Will close the issue for now :)
