### ISSUE TITLE
Transpile and bundle adonis5 for deploying on an iis-node server running node v12

### ISSUE THREAD

**Issue by ilterugur** [adonisjs/core#3647]
Hello. We are using a shared hosting that uses the Plesk panel with IIS-Node. I know Adonisjs requires NodeJS v14 or more but the newest version that we can use on this server is v12. As I know, this is the same on almost any web hosting provider and you need a VPS in order to run apps that use a newer NodeJS version.

I've tried to configure esbuild to achieve this. Here is my configuration file:

```
const glob = require("tiny-glob");
const esbuild = require("esbuild");

const nativeNodeModulesPlugin = {
  name: "native-node-modules",
  setup (build) {
    // If a ".node" file is imported within a module in the "file" namespace, resolve
    // it to an absolute path and put it into the "node-file" virtual namespace.
    build.onResolve({ filter: /\.node$/, namespace: "file" }, args => ({
      path: require.resolve(args.path, { paths: [args.resolveDir] }),
      namespace: "node-file"
    }));

    // Files in the "node-file" virtual namespace call "require()" on the
    // path from esbuild of the ".node" file in the output directory.
    build.onLoad({ filter: /.*/, namespace: "node-file" }, args => ({
      contents: `
        import path from ${JSON.stringify(args.path)}
        try { module.exports = require(path) }
        catch {}
      `
    }));

    // If a ".node" file is imported within a module in the "node-file" namespace, put
    // it in the "file" namespace where esbuild's default loading behavior will handle
    // it. It is already an absolute path since we resolved it to one above.
    build.onResolve({ filter: /\.node$/, namespace: "node-file" }, args => ({
      path: args.path,
      namespace: "file"
    }));

    // Tell esbuild's default loading behavior to use the "file" loader for
    // these ".node" files.
    let opts = build.initialOptions;
    opts.loader = opts.loader || {};
    opts.loader[".node"] = "file";
  }
};

(async function() {
  const directoriesGlobString = "./{app,config,contracts,providers,resources,start}/**/*.{js,json}";
  const globOptions = {
    flush: true,
    filesOnly: true
  };

  const directoriesGlobFiles = await glob(directoriesGlobString, globOptions);

  const allGlobFiles = [...directoriesGlobFiles];

  esbuild.build({
    entryPoints: ["server.js", "env.js", ...allGlobFiles],
    bundle: true,
    minify: true,
    platform: "node",
    target: "node12.22",
    outdir: "./dist",
    external: ["./processChild", "esbuild"],
    plugins: [nativeNodeModulesPlugin]
  }).catch(() => process.exit(1));
})();
```

With this configuration, I bundle the app on top of "build" folder which is generated by default production build process. But it says

```Error: Cannot find module '@adonisjs/core'```

I can't run npm install on the dist folder which is created by esbuild because it downloads modules that doesn't work on Node v12 like @poppinss/utils.

What should I do next?

**Comment by TemaSM** [comment]
Nodejs v12 is about to end of life, according to [Long Term Support (LTS) schedule](https://nodejs.org/en/about/releases/):
![image](https://user-images.githubusercontent.com/5501615/160320290-8f1fe996-2736-4d5e-b9ea-bc1dcb9144cf.png)

So, it's better to move forward with our present and future - Nodejs 14/16, than trying to adapt something for old thing, which soon will go away from ours life. If your hosting-provider will be using Node v12 after it's EOL, just create a ticket for their support with link to LTS schedule page. They should update Nodejs or add its newer version. If they not, then just stop using this sh*tty hosting-provider.

It's fundamental approach, which most developers support, I think.

**Comment by RomainLanz** [comment]
Node 12 is not supported by Adonis.

Please, upgrade your server dependency, you are out of date.
