### ISSUE TITLE
Upgrade ioredis 5.0.2 in redis module

### ISSUE THREAD

**Issue by sumanadak** [adonisjs/core#3652]
Dear,

How can I upgrade to ioredis 5.0.2 version as there is a bug fix(https://github.com/luin/ioredis/issues/1536) in typescript  for hmset command which is required for my adonisjs application .

Please help me on this.

Thanks
Suman

**Comment by RomainLanz** [comment]
Closing.

https://github.com/adonisjs/core/discussions/3653

**Comment by sumanadak** [comment]
Hello,

Is this irreverent question ??

Thanks
Suman

**Comment by thetutlage** [comment]
Nope. You are already discussing it in one place. https://github.com/adonisjs/core/discussions/3653.

Having multiple discussions will not help. Maybe you can create a PR in the correct repo?

**Comment by sumanadak** [comment]
Dear,

No one has replied so far. Hence I posted here. Anybody would like to help on this ?

Thanks
Suman
