### ISSUE TITLE
net::ERR_ABORTED 404 (Not Found) bug in loading static files

### ISSUE THREAD

**Issue by Lsantos-art** [adonisjs/core#3660]
I created a template using the new version of adonis. When I'm in the root route of the project "/dashboard" everything works perfectly, however when navigating to "/dashboard/config" for example, the files in the public folder are simply not loaded and the following message appears in the console: "E_ROUTE_NOT_FOUND: Cannot GET :/dashboard/plugins/icheck-bootstrap/icheck-bootstrap.min.css"

In the old version of adonis we had 'Adonis/Middleware/Static' that managed these unregistered routes, but in this new version I didn't find anything about it.

## Package version
5.6.2

## Node.js and npm version
v16.14.2

## Sample Code (to reproduce the issue)
Route.get('dashboard', async ({ view }) => {
  return view.render('home')
}).as('users.dashboard').middleware('auth')

Route.get('dashboard/config', async ({ view }) => {
  return view.render('admin/configuration')
}).middleware('auth').as('admin.configuration')

**Comment by RomainLanz** [comment]
Hey @Lsantos-art! 👋🏻 

How have you defined your assets?

**Comment by Lsantos-art** [comment]
@RomainLanz Hello. I tried in every way including the old global helpdesk that no longer work like style() or script().  But in the documentation it says that just pass the path that adonis will map the public folder.  I did it this way

​  <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

**Comment by Lsantos-art** [comment]
@RomainLanz 
I'll use an example from the new framework documentation. If I put my style in "public/style.css" it will work correctly in the "/" route for example. But if I navigate to "/admin" the style will stop working and the error "Failed to load resource: the server responded with a status of 404 (Not Found)" will appear.

From what I've seen, the assets in the public folder are loaded in " http://localhost:3333/", and when you navigate to "http://localhost:3333/admin" for example, the error is thrown because the asset routes are not there.

**Comment by RomainLanz** [comment]
> @RomainLanz Hello. I tried in every way including the old global helpdesk that no longer work like style() or script(). But in the documentation it says that just pass the path that adonis will map the public folder. I did it this way
> 
> ​  <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

You should use a leading `/` to make sure your assets are loaded from the root of your site. Otherwise, it will concatenate.

Example, if we are on page `/dashboard`:
```html
<!-- Will load from /dashboard/app.css -->
<link rel="stylesheet" href="app.css">

<!-- Will load from /app.css -->
<link rel="stylesheet" href="/app.css">
```

**Comment by Lsantos-art** [comment]
> > @RomainLanz Hello. I tried in every way including the old global helpdesk that no longer work like style() or script(). But in the documentation it says that just pass the path that adonis will map the public folder. I did it this way
> > ​
> 
> You should use a leading `/` to make sure your assets are loaded from the root of your site. Otherwise, it will concatenate.
> 
> Example, if we are on page `/dashboard`:
> 
> ```
> 
> <link rel="stylesheet" href="app.css">
> 
> 
> <link rel="stylesheet" href="/app.css">
> ```

My bad! I just put a "/" and it worked. Thanks for the help
