### ISSUE TITLE
Why not generate ace-manifest for each package individually?

### ISSUE THREAD

**Issue by sharifzadesina** [adonisjs/core#3693]
Just like `@adonisjs/assembeler` why we don't generate `ace-manifest.json` for each individual package that includes console commands? like `@adonisjs/core` and `@adonisjs/repl` so the end-user doesn't need to deal with commands that he/she has no control of them.

Is there any technical limitation or specific reason not to do it?

**Comment by thetutlage** [comment]
Yup, that is the eventual plan. But, if you have commands inside your project, then you will have to anyway generate a manifest file for that.

If we can get rid of having manifest file for in-application commands, then having per packages manifest file will streamline the development experience.

---

To conclude - This is one area which indeed need to some work :)

**Comment by sharifzadesina** [comment]
> Yup, that is the eventual plan. But, if you have commands inside your project, then you will have to anyway generate a manifest file for that.

Yes, but then we will have a manifest file for the commands that we have written and we know about them not the commands from inside other packages.

The first time I installed Adonis I was thinking what are all these commands inside the manifest file that I didn't write them.

> If we can get rid of having manifest file for in-application commands, then having per packages manifest file will streamline the development experience.

I think it is OK to have an application-based manifest file for the commands we write inside the application, but for the commands that are inside packages, it is better to follow `@adonisjs/assembeler`.

I just checked the source code for `@adonisjs/assembeler`, It seems it shouldn't be hard to implement what is happening for package `@adonisjs/assembeler` also for `core` and `repl` packages, so by default, fresh Adonis installations will have empty `ace-manifest.json` file.

**Comment by thetutlage** [comment]
Makes sense. Feel free to open a PR for any one package and then we can see how it all goes. Otherwise, I will pick it up once I have will some free time from other on-going things :+

**Comment by sharifzadesina** [comment]
It seems for `@adonisjs/assembler` it is hard coded to load the ace-manifest file.
https://github.com/adonisjs/core/blob/39860f3cc21ada7058f13ed6b9326a6f42ec2f05/src/utils/index.ts#L79-L82

I am closing this issue because it requires fundamental changes to implement autoloading.
