### ISSUE TITLE
Dependency vulnerabilities

### ISSUE THREAD

**Issue by IRod22** [adonisjs/core#3696]
## Package version
`@adonisjs/core`: v5.7.5

## Node.js and npm version
`node`: 17.8.0
`npm`: 8.7.0

## Sample Code (to reproduce the issue)
package.json (dependencies):
```json
{
  "devDepondencies": {
    "@adonisjs/assembler": "^5.6.2",
    "@japa/preset-adonis": "^1.0.15",
    "@japa/runner": "^2.0.7",
    "@symfony/webpack-encore": "^1.8.2",
    "adonis-preset-ts": "^2.1.0",
    "css-loader": "^6.7.1",
    "pino-pretty": "^7.6.1",
    "svelte": "^3.47.0",
    "svelte-loader": "^3.1.2",
    "typescript": "~4.6",
    "youch": "^3.1.1",
    "youch-terminal": "^2.1.3"
  },
  "dependencies": {
    "@adonisjs/ally": "^4.1.3",
    "@adonisjs/auth": "^8.1.0",
    "@adonisjs/core": "^5.7.5",
    "@adonisjs/lucid": "^17.2.0",
    "@adonisjs/repl": "^3.1.10",
    "@adonisjs/session": "^6.2.2",
    "@adonisjs/shield": "^7.0.10",
    "@adonisjs/view": "^6.1.4",
    "graphql": "^16.3.0",
    "phc-argon2": "^1.1.3",
    "proxy-addr": "^2.0.7",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.21",
    "sqlite3": "^5.0.5",
    "svelte-routing": "^1.6.0"
  }
}
```
Terminal:
```ps1
> npm audit
# npm audit report

glob-parent  <5.1.2
Severity: high
Regular expression denial of service in glob-parent - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install @adonisjs/assembler@1.1.1, which is a breaking change
node_modules/glob-parent
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/globby/node_modules/fast-glob
    globby  8.0.0 - 9.2.0
    Depends on vulnerable versions of fast-glob
    node_modules/globby
      cpy  7.0.0 - 8.1.2
      Depends on vulnerable versions of globby
      node_modules/cpy
        @adonisjs/assembler  *
        Depends on vulnerable versions of @adonisjs/sink
        Depends on vulnerable versions of cpy
        node_modules/@adonisjs/assembler

marked  <=4.0.9
Severity: high
Inefficient Regular Expression Complexity in marked - https://github.com/advisories/GHSA-5v2h-r2cx-5xgj
Inefficient Regular Expression Complexity in marked - https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
fix available via `npm audit fix --force`
Will install @adonisjs/assembler@1.1.1, which is a breaking change
node_modules/marked
  @adonisjs/sink  >=2.1.8
  Depends on vulnerable versions of marked
  Depends on vulnerable versions of marked-terminal
  node_modules/@adonisjs/sink
  marked-terminal  <=4.2.0
  Depends on vulnerable versions of marked
  node_modules/marked-terminal

8 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

## Additional Information
- OS: Windows 10
- Project created with: `adonis-ts-app` (could not find version in my packages, but it was in the [April 2022 Release](https://docs.adonisjs.com/releases/april-2022-release) with `@japa/*` configured).

### Notes and Remarks
I am very new to Github; I have learned most of the programming languages you can think of (PHP, Python, Golang, Ruby, etc.), but I've wanted to be a web developer as - thanks to `node` - JS/TS are the dominant languages a web developer needs to know, and are relatively easy to learn. I wanted to hone my web dev skills, so I'm hoping to start my own business;; two months ago I started building the website skeleton (which you all really helped me with, thx), but I was getting a lot of audit messages while installing `lucid`, `auth` and `ally` (I have another bug with `lucid`, but I will create another issue on that repo when I have time tomorrow), which is why I'm here.

Other than `lucid`, there have been no issues, but those vulnerabilities are starting to concern me, and I do not want my future clients to be scared of those vulnerabilities; the reason why I'm posting this to the core repo is that the issues are so deep in the dependency graph, therefore involving many packages at once. I wish I could contribute, but I do not have the time right now, and I would not know where to start with a framework as intricate as AdonisJS. Thank you all for understanding.

**Comment by thetutlage** [comment]
Please see https://github.com/adonisjs/core/issues/3333#issuecomment-968345404

**Comment by IRod22** [comment]
Ok, sorry I did not see that; I'm surprised that `npm` has not posted anything about those bugs on their CLI. Oh, I would like to give you all a heads up that `knex` got bumped up to v2 about a week ago. I'll create an issue on the `lucid` repo (unless someone beat me to it) that will go into more detail about the updates.

**Comment by IRod22** [comment]
Ok, I have my report on adonisjs/lucid#830
