### ISSUE TITLE
Support Cyrillic symbols for helpers

### ISSUE THREAD

**Issue by DZ8540** [adonisjs/core#3717]
## Why this feature is required (specific use-cases will be appreciated)?
Helpers for work with strings not support Cyrillic symbols, i'll be should use other packages for support this

Package: https://github.com/greybax/cyrillic-to-translit-js

Example:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/50152205/167155965-2a330138-64b3-48a2-b067-845a037e7650.png">

You can do it by default and then everyone will be happy :D

**Comment by thetutlage** [comment]
I am not sure what exactly you want us to do and also in which part of the application you want strings to support "Cyrillic symbols"?

I will appreciate, if you can open an issue with more context so that we can avoid back and forth :)

**Comment by thetutlage** [comment]
Okay, so there is a duplicate issue on the same https://github.com/adonisjs/http-server/issues/59 (I checked it later).

The related issue has more context, So let's have conversation there

**Comment by DZ8540** [comment]
> Okay, so there is a duplicate issue on the same [adonisjs/http-server#59](https://github.com/adonisjs/http-server/issues/59) (I checked it later).

Hi, yeah, that issue have the same problem with Cyrillic symbols, but it's refer only for routes, and his decision is other.

About helpers, when i want to use any helper, for example camelCase, for work with cyrillic, it is not work with cyrillic symbols, it's write just nothing to column in table

Example:
Hook for genre model with string's camel case helper
![изображение](https://user-images.githubusercontent.com/50152205/169661954-28be4aac-8ac6-4af2-83c8-d7e8158b954a.png)

How i write genre
![изображение](https://user-images.githubusercontent.com/50152205/169661994-7b42b07e-3170-495e-afd0-7ea79740d8c7.png)

Result
![изображение](https://user-images.githubusercontent.com/50152205/169662026-40ddd906-fb1f-4421-b9ad-377e4fa7d0aa.png)

He just write quotes to table when name is cyrillic. For english symbols it work normal
![изображение](https://user-images.githubusercontent.com/50152205/169662095-babf9ce6-4d31-4068-ae0b-c4cce220ae00.png)

And a package which i mentioned before, just solution for example resolve this problem. Thats all :)
