### ISSUE TITLE
Scaffold takes forever

### ISSUE THREAD

**Issue by sahil0571** [adonisjs/core#3718]
Hello there,
I was too much excited to tryout this framework but a little thing which disappointed me at first site was scaffolding newly created project takes too long to do it.
I literally waited 10 minutes for just app to be scaffolded please team do something about it.
It literally took half hour for project setup.

**Comment by thetutlage** [comment]
10 minutes is for sure too much for any project to be scaffolded. Ideally, AdonisJS apps takes between 3-15 seconds to scaffold and also install dependencies.

Maybe it has something to do with your network or simply npm taking too much time for some unknown reasons.

**Comment by thetutlage** [comment]
I will close this issue, since there is not much we can do here and we never received any such issues in the past.

**Comment by sahil0571** [comment]
Actually my network connection was very good but another thing which I have
found is that I got that issue 3 times out of i tried to make 4 projects in
adonis.
