### ISSUE TITLE
Why request multipart field giving some loop result ?

### ISSUE THREAD

**Issue by anggi117** [adonisjs/core#3723]
Hii, im using request multipart field because stream some field to S3

they giving result like this :
![image](https://user-images.githubusercontent.com/42998655/168254670-63ba9168-4229-4980-966f-59bc7056f864.png)

its any solution for me to just get all result from form-data ?

My code :
```
async submitData({response, request}) {
      var body = {}
      request.multipart.field((name, value) => {
        body[name] = value

        console.log(body)
      }).process()
}
```

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
