### ISSUE TITLE
Error when trying to run migrations both on Linux and Windows

### ISSUE THREAD

**Issue by patrickJramos** [adonisjs/core#3737]
### Discussed in https://github.com/adonisjs/core/discussions/3576

<div type='discussions-op-text'>

<sup>Originally posted by **jonatandevbr** February 21, 2022</sup>
When trying to "run migration:run" using NodeJS on Linux, the framework is unable to check which migrations have already been applied before, so it tries to apply everything again.

When running "migration:status", I get a table with all migrations with "corrupt" status.

I didn't find any documentation about the problem.

Grateful for the attention!</div>

Migrations only work when they are run exclusively from a single platform (only Linux or only Windows).

Are there any plans on fixing this?

My team preffers developing on Windows but we deploy our application (including a dev environment) on Linux.
We can work around the issue but it would be quite nice to be able to run migrations on both environments without problems.

Thanks for the attention!

**Comment by thetutlage** [comment]
It has already been fixed https://github.com/adonisjs/lucid/commit/eecdc56e198d103e91b136d3c658acb4355dfe79.

If you are still facing the issue, then please create an issue in the https://github.com/adonisjs/lucid repo and share a repo to help reproduce the issue
