### ISSUE TITLE
Navbar content UI issue on given dimension on site -> https://polls.adonisjs.dev/login

### ISSUE THREAD

**Issue by roxshivamsingh** [adonisjs/core#3751]
![image](https://user-images.githubusercontent.com/56290347/172883575-da6e1090-2b1a-48a5-9d55-08ecbc522783.png)

**Comment by thetutlage** [comment]
Yup. The demo is not responsive yet. Happy if someone wants to create a PR and do that. 

Closing the issue, since it belongs to this repo https://github.com/adonisjs-community/polls-app
