### ISSUE TITLE
Adonis.js - migration fails to create column references

### ISSUE THREAD

**Issue by squarfiuz** [adonisjs/core#3766]
Hello, I use Adonis.js for my API and I use PostgreSQL for my database. In my `database/migration/` folder I have created a `posts.ts` file which during migration `node ace make:migration` should create the posts table. The same goes for my `threads.ts` file.
The problem is that in my posts table I have indicated that one of the columns is a reference to another column in my threads table. And when I run the migration it gives me this error:
```
alter table "posts" add constraint "posts_thread_id_foreign" foreign key ("thread_id") references "threads" ("id") - the "threads" relationship does not exist
``` 

posts.ts:
```js
public async up () {
    this.schema.createTable(this.tableName, (table) => {
      table.string("id").primary().unique();
      table.string("category").notNullable();
      table.string("username").notNullable();
      table.text("message").notNullable();
      table.string("file_id");
      table.string("file_ext");
      table.string("reply_id");
      table.string("thread_id");

      /**
       * Uses timestamptz for PostgreSQL and DATETIME2 for MSSQL
       */
      table.timestamp("created_at", { useTz: true });
      table.timestamp("updated_at", { useTz: true });
    });

    this.schema.alterTable(this.tableName, (table) => {
      table.foreign("thread_id").references("id").inTable("threads").onDelete("CASCADE");
    });
};
```

threads.ts:
```js
public async up () {
    this.schema.createTable(this.tableName, (table) => {
      table.string("id").primary().unique();
      table.string("post_id");

      /**
       * Uses timestamptz for PostgreSQL and DATETIME2 for MSSQL
       */
      table.timestamp("created_at", { useTz: true })
      table.timestamp("updated_at", { useTz: true })
    });

    this.schema.alterTable(this.tableName, (table) => {
      table.foreign("post_id").references("id").inTable("posts").onDelete("CASCADE");
    });
};
```

**Comment by thetutlage** [comment]
The problem is self evident because the `post` migration file runs before the `threads` migration file and there is no threads table during that time.

You need to create that foreign key reference in a 3rd migration file.

---

Also, please issue the [Github discussions](https://github.com/adonisjs/core/discussions) to ask your questions. We use Github issues to track verified bugs or enhancements only :)
