### ISSUE TITLE
How to get IV from Encryption.encrypt() so that it can be passed to react frontend and decryption done there

### ISSUE THREAD

**Issue by pawan-khade** [adonisjs/core#3776]
I want to to do encryption in adonis js but do decryption of that text in react js front end. How to do that?. Is there any way of getting IV generated from Encryption module of Adonis so that it could be used for decryption at front end side?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
