### ISSUE TITLE
Type '"s3"' is not assignable to type '"local"' in Driver types

### ISSUE THREAD

**Issue by EmersonGarrido** [adonisjs/core#3777]
The expected type comes from property 'driver' which is declared here on type 'LocalDriverConfig & { driver: "local"; }'

Amazon S3 type not found in current version of adonis js

``` 
(property) disks: {
    [name: string]: LocalDriverConfig & {
        driver: "local";
    };
} 
```

**Comment by EmersonGarrido** [comment]
to solve the error I created a @types inside my src and put the following 
`import { DriversList } from '@adonisjs/drive-s3/build/adonis-typings/index'

interface Drive extends DriversList {
  s3: {}
}`

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
