### ISSUE TITLE
argument `auth` data did change after generate token for a created new user

### ISSUE THREAD

**Issue by eldiyar312** [adonisjs/core#3785]
## argument `auth` data did change after generate token for a created new user

- generate token for a user [code](https://docs.adonisjs.com/guides/auth/api-tokens-guard#authgenerate)

## Package version
"@adonisjs/auth": "^8.0.10",
"@adonisjs/core": "^5.4.0",

## Node.js and npm version
node v16.14.0
npm v8.5.3

## Sample Code (to reproduce the issue)
```
const inviteUserRouteHandler = async ({ auth, request, response }) => {
  const user = await User.create({
    name: 'Eldiyar',
    email,
  })
  console.log(auth.user.name) // Ivan
  const { token: access } = await auth
    .use('api')
    .generate(user, { expiresIn: Env.get('EXPIRES_IN') })
  console.log(auth.user.name) // Eldiyar
})
```

**Comment by thetutlage** [comment]
Please create issues in the correct repo and with proper information. I have no idea what exactly you expect and how the actual outcome is different.
