### ISSUE TITLE
Don't work option trim in validator

### ISSUE THREAD

**Issue by eldiyar312** [adonisjs/core#3786]
## Package version
"@adonisjs/core": "^5.8.4",

## Node.js and npm version
node v16.14.0
npm v8.5.3

## Sample Code (to reproduce the issue)
```
import { schema, rules } from '@ioc:Adonis/Core/Validator'
import { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'

export class ProductValidator {
  constructor(protected ctx: HttpContextContract) {}

  public schema = schema.create({
    name: schema.string({ trim: true }),
  })
  public messages = {}
}
```

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by hsharma1996** [comment]
@thetutlage I will be providing explanation as I am having the same issue. 
I apologise for wasting your time if I misunderstood anything. 

The problem :- 
As you can see we are using schema.string and using trim along with that. 
If you pass just whitespace character, It should give required error as spaces are trimmed but it is not giving any error hence the request is marked valid. 
I hope  I was able to explain. 
Thanks
