### ISSUE TITLE
 Failed to find application controllers

### ISSUE THREAD

**Issue by allanlisboa** [adonisjs/core#3794]
I get the following error when trying to run the project on a ubuntu server:

Cannot find module '/home/deploy/server/app/Controllers/Http/Auth/SigninsController'
Require stack:
- /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js
- /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/index.js
- /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/index.js
- /home/deploy/server/node_modules/@adonisjs/application/build/index.js
- /home/deploy/server/node_modules/@adonisjs/assembler/build/src/requireHook/ioc-transformer.js
- /home/deploy/server/node_modules/@poppinss/utils/build/src/esmRequire.js
- /home/deploy/server/node_modules/@poppinss/utils/build/index.js
- /home/deploy/server/node_modules/@adonisjs/require-ts/build/src/Compiler/index.js
- /home/deploy/server/node_modules/@adonisjs/require-ts/build/index.js
- /home/deploy/server/node_modules/@adonisjs/assembler/build/src/requireHook/index.js
- /home/deploy/server/node_modules/@adonisjs/assembler/build/register.js
- internal/preload
    err: {
      "type": "Error",
      "message": "Cannot find module '/home/deploy/server/app/Controllers/Http/Auth/SigninsController'\nRequire stack:\n- /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js\n- /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/index.js\n- /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/index.js\n- /home/deploy/server/node_modules/@adonisjs/application/build/index.js\n- /home/deploy/server/node_modules/@adonisjs/assembler/build/src/requireHook/ioc-transformer.js\n- /home/deploy/server/node_modules/@poppinss/utils/build/src/esmRequire.js\n- /home/deploy/server/node_modules/@poppinss/utils/build/index.js\n- /home/deploy/server/node_modules/@adonisjs/require-ts/build/src/Compiler/index.js\n- /home/deploy/server/node_modules/@adonisjs/require-ts/build/index.js\n- /home/deploy/server/node_modules/@adonisjs/assembler/build/src/requireHook/index.js\n- /home/deploy/server/node_modules/@adonisjs/assembler/build/register.js\n- internal/preload",
      "stack":
          Error: Cannot find module '/home/deploy/server/app/Controllers/Http/Auth/SigninsController'
          Require stack:
          - /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js
          - /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/index.js
          - /home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/index.js
          - /home/deploy/server/node_modules/@adonisjs/application/build/index.js
          - /home/deploy/server/node_modules/@adonisjs/assembler/build/src/requireHook/ioc-transformer.js
          - /home/deploy/server/node_modules/@poppinss/utils/build/src/esmRequire.js
          - /home/deploy/server/node_modules/@poppinss/utils/build/index.js
          - /home/deploy/server/node_modules/@adonisjs/require-ts/build/src/Compiler/index.js
          - /home/deploy/server/node_modules/@adonisjs/require-ts/build/index.js
          - /home/deploy/server/node_modules/@adonisjs/assembler/build/src/requireHook/index.js
          - /home/deploy/server/node_modules/@adonisjs/assembler/build/register.js
          - internal/preload
              at Function.Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
              at Function.Module._load (node:internal/modules/cjs/loader:787:27)
              at Module.require (node:internal/modules/cjs/loader:1012:19)
              at require (node:internal/modules/cjs/helpers:102:18)
              at ImportAliases.resolve (/home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js:95:23)
              at ImportAliases.resolveAsync (/home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js:113:25)
              at Ioc.import (/home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/index.js:280:42)
              at Ioc.makeAsync (/home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/index.js:391:40)
              at IocResolver.call (/home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Resolver/index.js:90:62)
              at Object.PreCompiler.runRouteHandler [as fn] (/home/deploy/server/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:51)
      "code": "MODULE_NOT_FOUND",
      "requireStack": [
        "/home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js",
        "/home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/src/Ioc/index.js",
        "/home/deploy/server/node_modules/@adonisjs/application/node_modules/@adonisjs/fold/build/index.js",
        "/home/deploy/server/node_modules/@adonisjs/application/build/index.js",
        "/home/deploy/server/node_modules/@adonisjs/assembler/build/src/requireHook/ioc-transformer.js",
        "/home/deploy/server/node_modules/@poppinss/utils/build/src/esmRequire.js",
        "/home/deploy/server/node_modules/@poppinss/utils/build/index.js",
        "/home/deploy/server/node_modules/@adonisjs/require-ts/build/src/Compiler/index.js",
        "/home/deploy/server/node_modules/@adonisjs/require-ts/build/index.js",
        "/home/deploy/server/node_modules/@adonisjs/assembler/build/src/requireHook/index.js",
        "/home/deploy/server/node_modules/@adonisjs/assembler/build/register.js",
        "internal/preload"
      ],
      "status": 500
    }

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
