### ISSUE TITLE
Error when I add S3 in adonis - But it's running (attached)

### ISSUE THREAD

**Issue by EwertonDutra** [adonisjs/core#3806]
## Package version
"devDependencies": {
    "@adonisjs/assembler": "^5.8.0",
    "@japa/preset-adonis": "^1.1.0",
    "@japa/runner": "^2.0.9",
    "adonis-preset-ts": "^2.1.0",
    "pino-pretty": "^8.1.0",
    "typescript": "~4.6",
    "youch": "^3.2.0",
    "youch-terminal": "^2.1.4"
  },
  "dependencies": {
    "@adonisjs/auth": "^8.2.1",
    "@adonisjs/bouncer": "^2.3.0",
    "@adonisjs/core": "^5.8.0",
    "@adonisjs/drive-s3": "^1.3.1",
    "@adonisjs/lucid": "^18.1.0",
    "@adonisjs/repl": "^3.1.0",
    "luxon": "^2.4.0",
    "mysql": "^2.18.1",
    "phc-argon2": "^1.1.3",
    "proxy-addr": "^2.0.7",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.21"

## Node.js and npm version
v16.16.0
8.14.0

## Sample Code (to reproduce the issue)
<img width="446" alt="env-ts como esta" src="https://user-images.githubusercontent.com/13201575/180584901-9c2dd332-350e-4303-9181-f5d8bbd67143.png">

<img width="631" alt="drive-ts fica dando um erro no TS" src="https://user-images.githubusercontent.com/13201575/180584903-06db9371-2075-46c8-96a6-fbc9742c3ead.png">

## BONUS (a sample repo to reproduce the issue)
To reproduce, just follow the step-by-step documentation to add S3

I don't know if I did something wrong, the files are as in the print

I'm reporting it, because the file shows that it has an error, but running it works, so it could be something more internal.

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
