### ISSUE TITLE
Async local storage doesn't work with debuggers

### ISSUE THREAD

**Issue by jaysson** [adonisjs/core#3808]
## Package version
5.8.0

## Node.js and npm version
Node: v18.6.0, NPM: 8.13.2

## Sample Code (to reproduce the issue)
```ts
// config/app.ts
export const http = {
  // other config
  useAsyncLocalStorage: true,
}
```
```ts
// app/Services/MyService.ts

import HttpContext from '@ioc:Adonis/Core/HttpContext'

export default class MyService {
  public myFunction() {
    const context = HttpContext.get()
    console.log(context)
  }
}
```
It works fine when run normally. However `context` is null if I try to run it with `yarn debug`, vscode, or webstorm.

## VSCode launch config
```json
{
      "type": "node",
      "request": "launch",
      "name": "Debug Backend",
      "runtimeExecutable": "node",
      "runtimeArgs": ["ace", "serve", "--watch"],
      "internalConsoleOptions": "openOnSessionStart",
      "skipFiles": ["<node_internals>/**", "${workspaceRoot}/node_modules/**/*"]
}
```

**Comment by quangthienit1994** [comment]
HttpContext working on each request, You can't use like it.

**Comment by jaysson** [comment]
> HttpContext working on each request

That's exactly what I am using it for.

> You can't use like that.

Do you mean I can't use debuggers for async local storage? As in that's a node issue?

**Comment by quangthienit1994** [comment]
I don't know what is "yarn debug", but can you use "const context = HttpContext.get()" in controllers or not ?

**Comment by jaysson** [comment]
I am able to `const context = HttpContext.get()` when a debugger is not attached to the node process, irrespective of whether it is a controller or a plain TS class. But I cannot use it if a debugger is attached to the process.

**Comment by quangthienit1994** [comment]
![image](https://user-images.githubusercontent.com/22471650/186628464-c85b8baf-476c-402b-aeeb-15c87ce126c2.png)
It's working, No problem. Please check your config and logic.

**Comment by jaysson** [comment]
You did not run the debugger. Please do that. The issue is about whether it works in conjunction with debugger. Also, I am running it on MacOS if that helps.

**Comment by quangthienit1994** [comment]
`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "runtimeExecutable": "node",
            "runtimeArgs": ["ace", "serve"],
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${file}"
        }
    ]
}`
It's running on debug of VS Code
![image](https://user-images.githubusercontent.com/22471650/186632997-dcc75045-4718-4a31-96ff-b448c9a51898.png)

**Comment by jaysson** [comment]
I am afraid you are either still not working with the debugger when the request is processing or it just works on Windows. In any case, I am attaching a video of the issue demonstrating it on a fresh AdonisJS project.

https://www.youtube.com/watch?v=SBEwUXcQb1o

**Comment by thetutlage** [comment]
@jaysson The context you have imported inside your service is from the incorrect path. Look at the usage section https://docs.adonisjs.com/guides/async-local-storage#usage

**Comment by thetutlage** [comment]
Also, I am not sure how VSCode debugger works under the hood. What happens when you use the official chrome dev-tools debugger?

Run the following command to start the server in debugging mode.

```sh
node ace serve --watch --node-args="--inspect"
```

Here is Node.js documentation on debugging https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by jaysson** [comment]
Thank you for the response @thetutlage . While I did import the wrong path in the video, I had imported the right one earlier following the guide itself. `node ace serve --watch --node-args="--inspect"` also has the same problem.

Another video: https://youtu.be/_4ywWADRh1I

**Comment by thetutlage** [comment]
Alright. Can you share this project as a repo and I will try to reproduce the issue on my end

**Comment by thetutlage** [comment]
CC @targos Pinging in case you can share some insights on using debugger with Async local storage

**Comment by jaysson** [comment]
Repo of the same code from the video. It has one route -> controller -> calls a plain TS class.

https://github.com/jaysson/adonis-als-debug

**Comment by thetutlage** [comment]
After going through this PR https://github.com/nodejs/node/pull/13870. I can see that somewhere between 8.5.0 and the latest release of Node, the issue was fixed.

If you upgrade to the latest version of (ie 18.8.0 as of today) and then try with `--inspect` flag, then it should work

**Comment by jaysson** [comment]
I am running node 18.6.0. Let me upgrade to 18.8.0 and see.

**Comment by jaysson** [comment]
Same issue on 18.8.0 (installed from homebrew). I am still on macOS big sur if that matters.

**Comment by thetutlage** [comment]
Yup, I can confirm the issue still exists. Have to decouple it from AdonisJS and see if it still exists and then report it with Node

**Comment by thetutlage** [comment]
I can reproduce it outside of AdonisJS as well. Here is a sample project. https://github.com/thetutlage/node-als-debugging

Going to confirm with @targos before opening an issue

**Comment by thetutlage** [comment]
Related issue https://github.com/nodejs/node/issues/44415

**Comment by targos** [comment]
This is fixed in Node.js and will be in the next release. In the mean time, you can use Node.js v16.x, which is not affected by the bug.
