### ISSUE TITLE
Convert Empty String to NULL Validator

### ISSUE THREAD

**Issue by pdipax** [adonisjs/core#3830]
Hi,
now to correctly manage the validation and updating of string keys I had to create a custom rule that converts the empty string to the null value. Wouldn't it be possible to integrate this logic directly into the validator?

Thank you

**Comment by thetutlage** [comment]
https://docs.adonisjs.com/guides/request#convert-empty-strings-to-null

**Comment by mcordoba** [comment]
What if we want to use this for JSON ?
I have a json api an I need to convert empty string to null so it pass the nullable validation :(

**Comment by RomainLanz** [comment]
You can use a middleware for that @mcordoba.

Here is an example:

```ts
import type { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'

export default class ConvertEmptyStringsToNull {
  public async handle({ request }: HttpContextContract, next: () => Promise<void>) {
    const body = request.body()

    travelThroughBody(body)

    request.updateBody(body)

    await next()
  }
}

function travelThroughBody(body: Record<string, any>) {
  for (const key in body) {
    if (body[key] === '') {
      body[key] = null
    }

    if (typeof body[key] === 'object') {
      travelThroughBody(body[key])
    }
  }
}
```

**Comment by mcordoba** [comment]
Yes that was my last idea. I think that would be useful to implement it in the same way you have convertEmptyStringsToNull in the bodyparser config.

Thank you

**Comment by RomainLanz** [comment]
It has been added for V6: https://github.com/adonisjs/bodyparser/commit/633df2057bc391c1950115103aa19837b0ea76cc
