### ISSUE TITLE
Send email for completed migration

### ISSUE THREAD

**Issue by budirec** [adonisjs/core#3854]
Can you give example to send email when a migration completed?
inside the email we will like to include the migration script that was ran.

I tried to add event listener for migration:start, but it catch nothing
```
Event.on('migration:start', function ({ file }) {
  Logger.debug(file)
})
```

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
