### ISSUE TITLE
S3 upload

### ISSUE THREAD

**Issue by Keanottesen** [adonisjs/core#3860]
I try to upload a file to s3. But is uploading an empty file. When I try streaming the file manually it also says that my file does not have a content-length. I guess it is the same error. But I can upload a file to s3, if I take the file from the path "uploads" with fs and upload it directly through Drive.

<img width="1124" alt="Screenshot 2022-08-10 at 13 24 57" src="https://user-images.githubusercontent.com/47158972/184082673-103f9013-210a-4f1a-a683-7a26ff47f459.png">

## Package version
5.8.4

## Node.js and npm version
v16.13.0 and 8.1.0

## Sample Code (to reproduce the issue)
`    const coverImage = request.file("file_content", {
      size: "2mb",
      extnames: ["jpg", "png", "gif"],
    })!;

    await coverImage.moveToDisk("./test");`

**Comment by pdipax** [comment]
Yes, same error for me.

**Comment by mckayze** [comment]
I had opened one shortly before this went up and it seems to be closed. Hopefully however this gets attention + fixed

**Comment by thetutlage** [comment]
@mckayze Your issue has been moved to the correct repo. https://github.com/adonisjs/drive-s3/issues/11 

The bare minimum we expect from you is to create issues in correct repos.

**Comment by mckayze** [comment]
@thetutlage I wasn't notified until a few hours ago that the repo was moved, but in the future ill create s3 related issues in the s3 space, thanks though bud 👍
