### ISSUE TITLE
Migration does not terminate (node ace migration:run, docker, CI, pipeline)

### ISSUE THREAD

**Issue by rootsmina** [adonisjs/core#3882]
I'm still having this issue when running a migration on CI, pipeline, Seems related to #1027

_Originally posted by @martinlevesque in https://github.com/adonisjs/core/issues/1027#issuecomment-520387759_

**Comment by rootsmina** [comment]
I'm running `node ace test unit` on a pipeline to execute my unit test.

On my test config i run the migrations and seeders before running the tests:

`export const runnerHooks: Required<Pick<Config, 'setup' | 'teardown'>> = {
  setup: [
    () => TestUtils.ace().loadCommands(),
    async () => {
      await Database.beginGlobalTransaction()
      await TestUtils.db().migrate()
      await TestUtils.db().seed()
      return () => Database.rollbackGlobalTransaction()
    },
  ],
  teardown: [],
}`

when i run `node ace test unit` on local the output from the migration command is `Already up to date`, but when it runs on the pipeline it tries to upgrade migrations version from "1" to "2", when it shouldn't cause in the adonis schema table all migrations are set on batch 1

**Comment by thetutlage** [comment]
- Please report the issue in the correct repo
- Provide a reproduction codebase
- And report one issue at a time. Create multiple issues if required.
