### ISSUE TITLE
"make:mailer" command not found

### ISSUE THREAD

**Issue by joelcieslar** [adonisjs/core#3889]
The `ace` command to create a [Mailer class](https://docs.adonisjs.com/guides/mailer#mailer-classes) doesn't seem to be working:

```
$ node ace make:mailer PasswordReset
[ error ]  "make:mailer" command not found
```

## Package version
AdonisJS version - v5.8.6
Node.js version - v16.15.0
NPM version - v8.5.5

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
