### ISSUE TITLE
API key authorization

### ISSUE THREAD

**Issue by pktippa** [adonisjs/core#3918]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

## Consider an RFC

Please create an [RFC](https://github.com/adonisjs/rfcs) instead, if

- Feature introduces a breaking change
- Demands lots of time and changes in the current code base.

*Delete the above section and the instructions in the sections below before submitting*

**Comment by Julien-R44** [comment]
How do you want me to explain anything to you when the issue you are submitting is totally empty?

**Comment by pktippa** [comment]
My bad, I will try to create a new ticket with requirement. Thanks.
