### ISSUE TITLE
Error when make a controller on AdonisJS5

### ISSUE THREAD

**Issue by abiliocoelho** [adonisjs/core#3919]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [GH discussions](https://github.com/adonisjs/core/discussions), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Package version
^5.8.6

## Node.js and npm version
Node.js V16.17.0 and npm V8.15.0

## Sample Code (to reproduce the issue)
When I try to run the command

node ace make:controller User  
displays the following error

Cannot find module './commands/Make\Controller' Require stack:

/Users/abiliocoelho/Desktop/socket/node_modules/@adonisjs/assembler/build/noop.js

1 resolveFileName /Users/abiliocoelho/Desktop/socket/node_modules/resolve-from/index.js:29

2 resolveFrom /Users/abiliocoelho/Desktop/socket/node_modules/resolve-from/index.js:43

3 module.exports /Users/abiliocoelho/Desktop/socket/node_modules/resolve-from/index.js:46

4 resolveFrom /Users/abiliocoelho/Desktop/socket/node_modules/@adonisjs/ace/node_modules/@poppinss/utils/build/src/Helpers/resolveFrom.js:25

5 ManifestLoader.loadCommand /Users/abiliocoelho/Desktop/socket/node_modules/@adonisjs/ace/build/src/Manifest/Loader.js:95

6 Kernel.find /Users/abiliocoelho/Desktop/socket/node_modules/@adonisjs/ace/build/src/Kernel/index.js:384

7 Kernel.execMain /Users/abiliocoelho/Desktop/socket/node_modules/@adonisjs/ace/build/src/Kernel/index.js:177

8 Kernel.handle /Users/abiliocoelho/Desktop/socket/node_modules/@adonisjs/ace/build/src/Kernel/index.js:553

9 App.handle /Users/abiliocoelho/Desktop/socket/node_modules/@adonisjs/core/build/src/Ignitor/Ace/App/index.js:226

**Comment by Julien-R44** [comment]
Hey

Please update to @adonisjs/assembler@5.9.2 

Fixed here : https://github.com/adonisjs/assembler/commit/e3947251a7dcf6e31a3085880a468ab4e250cb69
