### ISSUE TITLE
Feature Request: Implement Caching ability to routes and config

### ISSUE THREAD

**Issue by Hetarth02** [adonisjs/core#3928]
Just like Laravel gives us the ability to cache the routes and config, I think it would be great if this framework could also have the same feature set as it is also inspired by the Laravel framework. I have currently seen the view caching but would also like to have the ability to cache routes and config too.

## Why this feature is required (specific use-cases will be appreciated)?
When routes and config are cached it can increase the speed of the application overall.

## Have you tried any other work arounds?
No.

## Are you willing to work on it with little guidance?
I would be happy to work on it if provided proper guidance and ample time.

**Comment by thetutlage** [comment]
You need to a bit of research first. Just because Laravel caches something doesn't mean AdonisJS have to. Infact, can you share any performance bottlenecks you have faced so far

**Comment by Hetarth02** [comment]
I am sorry, but I didn't meant anything in an offensive way. I will do a bit of research on my end and will get back to you on the same.
