### ISSUE TITLE
Make one relationship table for any model

### ISSUE THREAD

**Issue by Barsnes** [adonisjs/core#3935]
Hello,
I am looking into making a global relationships table for my application.

The table would look like this:
| name         | type   |
|--------------|--------|
| parent_model | string |
| parent_id    | int    |
| child_model  | string |
| child_id     | int    |

Is there any way I can connect my models to this table, and be able to use it across my models?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
