### ISSUE TITLE
request.cookie undefined

### ISSUE THREAD

**Issue by rstevens354** [adonisjs/core#3941]
Im trying to set and get cookies in my Adonis 5 App using the following

```
response.cookie("oauth_token", oauth_token, {
      maxAge: 15 * 60 * 1000,
      secure: false,
      httpOnly: true,
      sameSite: true,
});

let getToken = request.cookie("oauth_token");
console.log("getToken", getToken);
```

 
   when trying to console log the value of the cookie its undefined.

any pointers?

**Comment by thetutlage** [comment]
Consider, we have an extensive suite of tests around cookies, seems like something in your app is causing this issue.

Please reproduce this issue in a fresh application and share the repo with us.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
