### ISSUE TITLE
Add Vite as new assets driver

### ISSUE THREAD

**Issue by Julien-R44** [adonisjs/core#3953]
Hello ! Good news, Vite is coming to AdonisJS soon! 🎉

I create this issue to track the progress of the work on the integration.

Overall I would say that more than half of the work is done. What is missing for the moment is mostly documentation and tests. I have a local version that works pretty well. 

# Proposed changes

## Assembler changes

- The assembler will be shipped with a new command `node ace configure vite`. In the same way as for Encore, this will initialize and configure Vite in your Adonis application.
- When you run "node ace serve", again as Encore, the dev server will be launched in the same process.

## Vite Plugin

Concretely the main thing you will have to tweak is the config of Vite via vite.config.ts. Here is the proposed API : 

```ts
import { defineConfig } from 'vite'
import Adonis from '@adonisjs/vite-plugin-adonis'

export default defineConfig({
  plugins: [
    Adonis({
      /**
       * Same as webpack. The public URI to access the static files. It should always be
       * relative from the "public" directory.
       */
      publicPath: '/assets',

      /**
       * Same as webpack. Entrypoints are the files that will be compiled by Vite.
       * You will also be able to load them using the `entryPointScripts`
       * and `entryPointStyles` template tags.
       */
      entryPoints: {
        app: ['resources/js/app.ts', 'resources/css/app.css'],
        admin: ['resources/js/admin.ts', 'resources/css/admin.css'],
      },
    }),
  ],
})
```

And you're ready to go. You can obviously tweak your configuration to add Vue, React or whatever you want. You can take advantage of the whole rollup / Vite plugin ecosystem. Note that **Typescript** and PostCSS, Sass, Less etc. are supported out of the box. No config needed.

## Picking an Asset Driver

To pick the driver you want, you must add the property "assetsDriver" in your .adonisrc.json file.

```jsonc
{
  "assetsDriver": "vite",
  "typescript": true,
  "commands": [
    "./commands",
    "@adonisjs/core/build/commands/index.js",
    "@adonisjs/repl/build/commands"
  ],
  // ....
}
```

If this property is not set, then automatic detection will be attempted. If a `vite.config.*` file is present in the root, then Vite will be chosen. And if a `webpack.config.*`, Encore will be chosen.

## Views

Everything will work as before. You can reference an entrypoint in the same way as before. Taking the Vite config from above, I can add this to an edge file : 

```html
<!DOCTYPE html>
<html lang="en">

<head>
  @vite()
  @viteReactRefresh()
  @entryPointStyles('app')
  @entryPointScripts('app')
</head>
```

Note the addition of the "vite" tag. This tag will inject the script that allows the HMR.
If you are using React with `@vitejs/plugin-react`, you will need the `@viteReactRefresh()` tag. [See here for more information](https://vitejs.dev/guide/backend-integration.html).

## Static assets

Let's imagine you want to load an image using the `asset` helper. You will have to notice Vite that you want to bundle these images. This can be done as follows : 

```ts
// resources/ts/app.ts

import.meta.glob([
  '../images/**',
  '../fonts/**',
])
```

Now you can load your image in your view in the normal way : 

```html
<img src="{{ asset('resources/images/my-image.jpg') }}" />
```

# Tracking tasks / PR

- [ ] Assembler PR https://github.com/adonisjs/assembler/pull/56
- [x] Core PR https://github.com/adonisjs/core/pull/3952
- [x] Application PR https://github.com/adonisjs/application/pull/24
- [ ] View PR https://github.com/adonisjs/view/pull/18
- [ ] create-adonis-ts-app PR https://github.com/adonisjs-community/create-adonis-ts-app/pull/51
- [x] Create repo for the vite plugin https://github.com/adonisjs/vite-plugin-adonis

- [ ] Write a migration guide from Encore to Vite https://github.com/adonisjs/docs.adonisjs.com/pull/197
- [ ] Write a new documentation section for Vite on the Website. https://github.com/adonisjs/docs.adonisjs.com/pull/198
- [x] Add more testing
- [x] Make sure it works well with Inertia, Unpoly, Htmx. I am not very familiar with these tools. But I want to have first-class support since they are popular in our ecosystem.
- [ ] Migrate some repos to Vite. This will make references PR for people. Like `polls-app` or the docs

---

Once shipped, I think we will open a second issue to collect feedback, or maybe a thread in GitHub discussions. Because there will inevitably be problems 😅

To conclude, the Core team will correct me if I'm wrong, but I'm pretty confident that we can deliver this without any breaking changes and without waiting for Adonis 6 !

Let me know if you have any suggestions or if I have forgotten anything.

**Comment by dorgelesn** [comment]
Hello Adonis team. 
Thank you for the wonderful Adonis framework.
Do you need some help on Vite Intégration ?

**Comment by KimhoutSam** [comment]
@Julien-R44 when you create Adonis app by using web and enable webpack encore do you see invalidate `ASSETS_DRIVER` env in `config/app.ts`

**Comment by iyashpal** [comment]
@Julien-R44 any update on this feature? We haven't heard about this feature for so long.

**Comment by JannieT** [comment]
I am super eager to see this happening and added my emoji's when [core v5.9.0](https://github.com/adonisjs/core/releases/tag/v5.9.0) was released with "Add Vite driver ( Not 100% ready yet )" as main summary. 

Is it somehow possible to use that release to replace Encore with Vite? 

When I upgrade to that core release and follow the [upgrade cookbook](https://github.com/adonisjs/docs.adonisjs.com/pull/197/files#diff-9e683d6ce87218488c73a8386d66030a596f4b685ef45cd5be910f796c2834a9R5) I get:

> Error: Cannot invoke instructions. Missing package "vite"

at the step where I run `node ace configure vite`

I know the new core release warns "(Not 100% ready yet)", but is it actually more like "(Not quite usable yet)"

**Comment by Julien-R44** [comment]
Sorry for the wait. But we all ran out of time because of the huge work to do on Adonis 6, and/or for others, our professional jobs.

However, integration plugin with Vite has been rewritten for Adonisjs 6 and is already working. So it will unfortunately not be released for version 5, but as soon as Adonis 6 is released it should be available to everyone 🙂  

So closing the issue for now!
