### ISSUE TITLE
Can't find “make:model” option

### ISSUE THREAD

**Issue by CoolGIS** [adonisjs/core#3959]
## Package version
4.2.2

## Node.js and npm version
node.js 18.12.0
npm 8.19.2

## Sample Code (to reproduce the issue)
In terminal,run  “npm init adonis-ts-app@latest hello-world”,then I found "make:model" disappear

**Comment by Julien-R44** [comment]
You must install Lucid first https://docs.adonisjs.com/guides/database/introduction

**Comment by nmalchy** [comment]
Hey I installed Lucid as directed and am still encountering this issue
