### ISSUE TITLE
s3 this.adapter.config.endpoint is not a function

### ISSUE THREAD

**Issue by nels0n12** [adonisjs/core#3964]
my project was working just fine since creation and installed the s3 driver package and configured and it worked just fine for a few weeks. the problem started when I deleted the node_modules folder and reinstalled my packages (which was successful), but after that, I get an error while uploading files to my s3. the files are being successfully uploaded to my s3 but I still get that error. 
>the error 👇
```
{
    "message": "this.adapter.config.endpoint is not a function",
    "stack": "TypeError: this.adapter.config.endpoint is not a function\n    at S3Driver.getUrl (D:\\projects\\development\\backend\\node\\nelsonbrandz-accounts-adonis\\node_modules\\@adonisjs\\drive-s3\\build\\src\\Drivers\\S3.js:220:66)\n    at File.moveToDisk (D:\\projects\\development\\backend\\node\\nelsonbrandz-accounts-adonis\\node_modules\\@adonisjs\\bodyparser\\build\\src\\Multipart\\File.js:177:44)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at ProfileController.updateProfileAvatar (D:\\projects\\development\\backend\\node\\nelsonbrandz-accounts-adonis\\app\\Controllers\\Http\\ProfileController.ts:141:5)\n    at Object.PreCompiler.runRouteHandler [as fn] (D:\\projects\\development\\backend\\node\\nelsonbrandz-accounts-adonis\\node_modules\\@adonisjs\\http-server\\build\\src\\Server\\PreCompiler\\index.js:44:31)\n    at AuthMiddleware.handle (D:\\projects\\development\\backend\\node\\nelsonbrandz-accounts-adonis\\app\\Middleware\\Auth.ts:74:5)\n    at Server.handleRequest (D:\\projects\\development\\backend\\node\\nelsonbrandz-accounts-adonis\\node_modules\\@adonisjs\\http-server\\build\\src\\Server\\index.js:108:13)"
}
```
![image](https://user-images.githubusercontent.com/55479584/200084217-5955af89-e50c-4fc3-8fe8-9b78fb54dd00.png)

> this issue seems to only appear if I delete and reinstall project packages. I confirmed this by creating a new project and configured s3 which worked well until I deleted the node_modules and reinstalled

A SPEEDY RESPONSE WILL BE MUCH APPRECIATED

**Comment by RomainLanz** [comment]
Roll back your driver and watch your words....
https://github.com/aws/aws-sdk-js-v3/issues/4122

**Comment by epileftro85** [comment]
Sorry, is this still a current error? which version of driver should I use in order to get rid of this?

**Comment by McSneaky** [comment]
> Sorry, is this still a current error? which version of driver should I use in order to get rid of this?

Latest version of Drive. If this doesn't work, then add `endpoint` to your S3 config
Something like this: `endpoint: "https://s3.REGION.amazonaws.com/BUCKET"`
