### ISSUE TITLE
Visual Studio "Go to implementation" shortcut links to type definition

### ISSUE THREAD

**Issue by pinkynrg** [adonisjs/core#3975]
## Why this feature is required (specific use cases will be appreciated)?
I would like to navigate the source code whenever needed in an agile way.

## Have you tried any other workarounds?
I realized that maybe the source maps are missing based on this answer on GitHub:

> [...] libraries can bundle [declaration maps](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---declarationmap) that map from .d.ts files back to source .ts (or .js) files. However many libraries currently do not include these.

https://stackoverflow.com/a/46897441/7754093

## Are you willing to work on it with little guidance?
Surely

**Comment by thetutlage** [comment]
Can you please start by explaining the problem first? Because, the "Go to implementation" should work and works right now all editors supporting TypeScript

**Comment by pinkynrg** [comment]
I would expect that clicking here:

<img width="797" alt="Screen Shot 2022-11-23 at 00 20 05" src="https://user-images.githubusercontent.com/1474127/203445767-c241a9b1-b18c-4273-aefe-dc3838237223.png">

Would bring me here
<img width="719" alt="Screen Shot 2022-11-23 at 01 08 14" src="https://user-images.githubusercontent.com/1474127/203445809-904a73dc-c46f-4651-9842-f630318d8831.png">

Not here
<img width="627" alt="Screen Shot 2022-11-23 at 00 20 18" src="https://user-images.githubusercontent.com/1474127/203445846-f7689c8b-1556-48f1-b8d4-c45ad7e1fe28.png">

**Comment by arthur-er** [comment]
The unbundled ts code isn't included on the code you install from NPM, making it impossible to alt+click and go into the source code.

**Comment by RomainLanz** [comment]
This is currently not possible in AdonisJS 5, will be in v6.
