### ISSUE TITLE
Passing arguments to validation class returning an error

### ISSUE THREAD

**Issue by 3adel-bassiony** [adonisjs/core#3996]
Hello
I followed the [documentation](https://docs.adonisjs.com/guides/validator/introduction#using-validator) for using the validation class and passing the arguments to it, but when I try to pass any argument I defined before in the class it's return an error in the controller, the error because it's require to pass the `ctx` first then I should pass the extra arguments I defined, so I think there is something wrong because the documentation didn't mention anything for passing the `ctx`.

here is the full error I got from VSCode:
<img width="1092" alt="Screenshot_2022-12-01_at_4 51 47_PM" src="https://user-images.githubusercontent.com/81669622/205450052-71735eab-666a-45c8-a078-37fb6e7c289c.png">

and here is the constructor for the validation class:
`constructor(protected ctx: HttpContextContract, public type: string) {}`

## Package version
Latest version: v5.9.0

## Node.js and npm version
v19.0.1

## Sample Code (to reproduce the issue)
`const payload = await request.validate(new UpdateCategoryValidator({ type: 'test'}))`

**Comment by mikesaintsg** [comment]
No need to add `type` as a parameter, your constructor should just be:
```js
constructor(protected ctx: HttpContextContract) {}
```

**Comment by 3adel-bassiony** [comment]
@mikesaintsg but in the documentation they mentioned that if I want to pass something to the validator i should pass it like this 🤔

**Comment by mikesaintsg** [comment]
Ah, sorry, if this is within the HttpContext, you don't need to pass any arguments or even create new instance of the class, just replace your payload line with the following:

```js
const payload = await request.validate(UpdateCategoryValidator)
```

Here is a snapshot of that section in the documentation, note the highlighted part below the image

![image](https://user-images.githubusercontent.com/45922630/217647471-90097e5b-d2bb-430a-84ba-b34ee12a4657.png)

**Comment by thetutlage** [comment]
Can you share your validator class?

**Comment by 3adel-bassiony** [comment]
@thetutlage  Sure, here is the validator class, I just want to pass the type to the validator class

```typescript
import { schema, rules, CustomMessages } from '@ioc:Adonis/Core/Validator'
import type { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'

export default class UpdateCategoryValidator {
    constructor(protected ctx: HttpContextContract, public type: string) {}

    /*
     * Define schema to validate the "shape", "type", "formatting" and "integrity" of data.
     *
     * For example:
     * 1. The username must be of data type string. But then also, it should
     *    not contain special characters or numbers.
     *    ```
     *     schema.string({}, [ rules.alpha() ])
     *    ```
     *
     * 2. The email must be of data type string, formatted as a valid
     *    email. But also, not used by any other user.
     *    ```
     *     schema.string({}, [
     *       rules.email(),
     *       rules.unique({ table: 'users', column: 'email' }),
     *     ])
     *    ```
     */
    public schema = schema.create({
        category_type_id: schema.string.optional({}, [
            rules.unique({
                table: 'categories_types',
                column: 'type',
                where: {
                    type: this.type,
                },
            }),
            rules.minLength(4),
            rules.maxLength(255),
            rules.trim(),
        ]),
        title_en: schema.string.optional({}, [
            rules.minLength(4),
            rules.maxLength(255),
            rules.trim(),
        ]),
        title_ar: schema.string.optional({}, [
            rules.minLength(4),
            rules.maxLength(255),
            rules.trim(),
        ]),
    })

    /**
     * Custom messages for validation failures. You can make use of dot notation `(.)`
     * for targeting nested fields and array expressions `(*)` for targeting all
     * children of an array. For example:
     *
     * {
     *   'profile.username.required': 'Username is required',
     *   'scores.*.number': 'Define scores as valid numbers'
     * }
     *
     */
    public messages: CustomMessages = {}
}
```

**Comment by RomainLanz** [comment]
I would recommend using a `refs` [^1] for that, there is an example on how to use it with the `unique` rule [^2].

[^1]: https://docs.adonisjs.com/guides/validator/schema-caching#using-refs
[^2]: https://docs.adonisjs.com/reference/validator/rules/unique#using-refs

**Comment by 3adel-bassiony** [comment]
@RomainLanz  Thank you 🙏

**Comment by RomainLanz** [comment]
Does that fix your issue?

**Comment by RomainLanz** [comment]
Cool! Closing then.
