### ISSUE TITLE
Default Hasher Mismatch

### ISSUE THREAD

**Issue by arabbani** [adonisjs/core#3997]
here it is saying inside the comment that ``argon`` is the default hasher. But the default prop is set to ``scrypt``

<img width="553" alt="Screenshot 2022-12-05 214059" src="https://user-images.githubusercontent.com/13854024/205825782-94576f3e-3b1b-412e-a1be-aa99e76658e8.png">

## Package version
5.9.0

## Node.js and npm version
nodejs - 18.12.1
npm - 8.19.2

**Comment by thetutlage** [comment]
Can you please send a PR to update the comment in the template? https://github.com/adonisjs/core/blob/develop/templates/config/hash.txt#L26

**Comment by arabbani** [comment]
the default should be ``scrypt`` right? @thetutlage

**Comment by thetutlage** [comment]
Yes, it should be. Since scrypt is inbuilt into Node.js, it removes the need of installing a driver first.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
