### ISSUE TITLE
Application Error at indicative.adonisjs.com

### ISSUE THREAD

**Issue by soubhikchatterjee** [adonisjs/core#4006]
Looks like indicative.adonisjs.com is down (probably because you were running on a free tier of heroku which shutdown their free plans)

Please get it up 

Thanks

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
