### ISSUE TITLE
Array / Object error when the array length 21 or more

### ISSUE THREAD

**Issue by Joan1590** [adonisjs/core#4007]
## Package version
"@adonisjs/core": "^5.8.0",

## Node.js and npm version
Node: v18.12.0
NPM: 8.19.2

## Sample Code (to reproduce the issue)
I send to api put request with a privilege array of numbers: 

privileges[0]: 
1
privileges[1]: 
2
privileges[2]: 
3
privileges[3]: 
4
privileges[4]: 
5
privileges[5]: 
6
privileges[6]: 
8
privileges[7]: 
9
privileges[8]: 
10
privileges[9]: 
11
privileges[10]: 
12
privileges[11]: 
13
privileges[12]: 
14
privileges[13]: 
15
privileges[14]: 
16
privileges[15]: 
17
privileges[16]: 
18
privileges[17]: 
19
privileges[18]: 
20
privileges[19]: 
21
privileges[20]: 
22

Then when i'm validate with schema, the body is converted to a object with this format: 
{'0':'0', '1':'1'}

But if i sent 20 or less, i get the array correctly like this: [1,2,3,4,5,6,7,8,9,10]

**Comment by Joan1590** [comment]
If you need a temporal solution, i use this on a middleware body parser: 
` // Check if input is an object

      if (typeof request.input(key) === 'object' && request.input(key) !== null) {

        // If the keys are numbers, convert them to an array

        if (Object.keys(request.input(key)).every((key) => !isNaN(Number(key)))) {

          const bodyTemp = request.body()

          bodyTemp[key] = Object.values(request.input(key))

          request.updateBody({

            ...bodyTemp,

          })

        }

      }
`

**Comment by RomainLanz** [comment]
Hey @Joan1590!

Please properly format your issue and give us a way to reproduce the problem.
It is currently not understandable.

**Comment by Joan1590** [comment]
> Hey @Joan1590!
> 
> Please properly format your issue and give us a way to reproduce the problem. It is currently not understandable.

Can you give an example ?

**Comment by thetutlage** [comment]
- The code blocks should be formatted
- There are no code examples, so we do not know what code to write to reproduce the issue.
- There are request data samples, so again we do not know how to reproduce the issue.

**Comment by Joan1590** [comment]
This is the example code (is a validation schema):

```
public async store({ request, response, auth }: HttpContextContract) {

const data = await request.validate({
      schema: schema.create({
        privileges: schema.array
            .optional()
            .members(schema.number([rules.exists({ table: 'privileges', column: 'id' })])),
      }),
    })
    
}
```

I send to this schema, the array of numbers above: (``` privileges[0]: 1 ``` ) is a form data. 

Then i get error on validate, because the privileges params is a object, BUT if i send the same data but with length 20 or less, the validator recognizes that it is an array 😂 

I make the parser to form, for convert the object to array, but i dont know, why this convert the array to object when the array is more of 20 elemets. 

Is it more cleary 
@thetutlage @RomainLanz  ?

**Comment by Joan1590** [comment]
Fixed !!, the error is on front-end of my code!! 

But that parser works too, then im going to close this issue

**Comment by Joan1590** [comment]
All was about, a bad configuration for qs, the request body was too large, then you need to change the QueryStream params in the bodyparser file in the form part:
```
form: {
    encoding: 'utf-8',
    limit: '100mb',
    queryString: {
      arrayLimit: 100000,
      depth: 100000,
      parameterLimit: 100000,
    },

    /*
    |--------------------------------------------------------------------------
    | Convert empty strings to null
    |--------------------------------------------------------------------------
    |
    | Convert empty form fields to null. HTML forms results in field string
    | value when the field is left blank. This option normalizes all the blank
    | field values to "null"
    |
    */
    convertEmptyStringsToNull: true,

    types: ['application/x-www-form-urlencoded'],
  },
  ```
  
  I feel so stupid, thank you for the support @RomainLanz  @thetutlage
