### ISSUE TITLE
Test DB seeder bug

### ISSUE THREAD

**Issue by mortezabonak** [adonisjs/core#4041]
Hi,
In the `bootstrap.ts` file, which is included in the `test` folder, when we want to seed in another database, we face a problem.
The problem is that assuming the connection is specified inside the `db()` function, it is still executed inside the main seed database.

This is my database connections inside of database config file:

```
  connections: {
    pg: {
      client: 'pg',
      connection: {
        host: Env.get('PG_HOST'),
        port: Env.get('PG_PORT'),
        user: Env.get('PG_USER'),
        password: Env.get('PG_PASSWORD', ''),
        database: Env.get('PG_DB_NAME'),
      },
      migrations: {
        naturalSort: true,
      },
      healthCheck: false,
      debug: false,
    },

    // test DB
    testPg: {
      client: 'pg',
      connection: {
        host: Env.get('PG_HOST'),
        port: Env.get('PG_PORT'),
        user: Env.get('PG_USER'),
        password: Env.get('PG_PASSWORD', ''),
        database: Env.get('TEST_PG_DB_NAME'),
      },
      migrations: {
        naturalSort: true,
      },
      healthCheck: false,
      debug: false,
    },

  }
}

export default databaseConfig
```

and this is my `runnerHooks` inside of the `bootstrap.ts` file:
```
export const runnerHooks: Pick<Required<Config>, 'setup' | 'teardown'> = {
  setup: [
    () => TestUtils.ace().loadCommands(),
    () => TestUtils.db('testPg').migrate(),
    () => TestUtils.db('testPg').seed(),
  ],
  teardown: [],
}
```
Of course, there is no problem with running the migration, and when the test runs, the migration changes are performed on the `testPg` database.

**Comment by McSneaky** [comment]
> Of course, there is no problem with running the migration, and when the test runs, the migration changes are performed on the testPg database.

I'm slightly confused, what's the bug?

**Comment by sumitbhanushali** [comment]
@McSneaky i guess @mortezabonak is able to run migrations on `testPg` database but his seed function is being run on `pg`

**Comment by mortezabonak** [comment]
> @McSneaky i guess @mortezabonak is able to run migrations on `testPg` database but his seed function is being run on `pg`

exactly

**Comment by sumitbhanushali** [comment]
@mortezabonak i guess it would better if you provide a demo project. It will help maintainers in replicating issue and fix it sooner

**Comment by thetutlage** [comment]
Since you have not shared the seeder code. I suspect you are not using the `this.connection` property when executing queries. I recommend reading the docs https://docs.adonisjs.com/guides/database/seeders#customizing-database-connection

Also, please re-open the issue with a sample reproduction repo, as I would like to avoid too much back and forth for gather information
