### ISSUE TITLE
npm test script is missing

### ISSUE THREAD

**Issue by guoyunhe** [adonisjs/core#4044]
## Package version
5.9.0

## Node.js and npm version
18.12.1

## Sample Code (to reproduce the issue)

Run `pnpm create adonis-ts-app your-project` to create a new project, choose `api` type.

Then look into `package.json`. Here is no `test` in `scripts`.

For most CI workflow, it requires `npm test` or `npm run test:ci`.

AdonisJS already has built-in test framework. But users have to manually configure a test script.

**Comment by RomainLanz** [comment]
Hey @guoyunhe! 👋🏻 

Could you please create a pull request to add the `test` script in the `package.json` file?

**Comment by guoyunhe** [comment]
@RomainLanz here it is https://github.com/adonisjs-community/create-adonis-ts-app/pull/57
