### ISSUE TITLE
Add option to change cached files folder path

### ISSUE THREAD

**Issue by KevinRouchut** [adonisjs/core#4050]
## Explanation

Currently, when we use the `node ace serve` command, the cache is stored here: `./node_modules/.cache/adonis-require-ts`

In a monorepo project, the **node_modules** folder is at the root of the project, so we no longer have a **node_modules** folder in the Adonis app folder.

The "problem" is that the Adonis development server will create a **node_modules** folder only to store the cache, this will "pollute" unnecessarily the file explorer of the IDE.

The solution would therefore be to give the possibility to configure the path to the caching folder in `.adonisrc.json` ([like Vite](https://vitejs.dev/config/shared-options.html#cachedir)), as well as add a parameter to the `node ace serve` command.

We could for example configure the path to the **node_modules** folder at the root of the project :

![image](https://user-images.githubusercontent.com/8747883/213556786-6618dbaf-860e-483b-9ca6-8708374c7950.png)

Good news, `@adonisjs/require-ts` already has an option ([cachePath](https://github.com/adonisjs/require-ts#register)).

But `@adonisjs/assembler` [doesn't use it](https://github.com/adonisjs/assembler/blob/9cfd8180f75948ded60171c446638b5fb6b3b23f/src/requireHook/index.ts#L18).

### .adonisrc.json

```json
...
  "devServer": {
    "cachePath": "../../node_modules/.cache/adonis"
  },
...
```

### ❯ node ace serve --help

```
Start the AdonisJS HTTP server, along with the file watcher. Also starts the webpack dev server when webpack encore is installed

Usage: serve

Flags
  --assets boolean        Start webpack dev server when encore is installed. Use "--no-assets" to disable
  -w, --watch boolean     Watch for file changes and re-start the HTTP server on change
  -p, --poll boolean      Detect file changes by polling files instead of listening to filesystem events
  --node-args string[]    CLI options to pass to the node command line
  --encore-args string[]  CLI options to pass to the encore command line
  --cache-path string     Path to cache folder       <------
```

**Comment by thetutlage** [comment]
Please send a PR for the same in the assembler repo

**Comment by KevinRouchut** [comment]
> Please send a PR for the same in the assembler repo

Ok I'll try when I have a moment.

In the meantime, I found a very simple solution to solve the problem, I use the `CACHE_DIR` environment variable that `find-cache-dir` package offers (and that `@adonisjs/require-ts` and `Japa` use in internal).

So, for example:
```

**Comment by KevinRouchut** [comment]
> Please send a PR for the same in the assembler repo

Ok I'll try when I have a moment.

In the meantime, I found a very simple solution to solve the problem, I use the `CACHE_DIR` environment variable that `find-cache-dir` package offers (`Adonis` and `Japa` use it internally).

So, for example, just put this line on top of `ace` and `test.ts` files:
```ts
process.env.CACHE_DIR = "../../node_modules/.cache";
```
