### ISSUE TITLE
Error when using the validation and create function to create new resource

### ISSUE THREAD

**Issue by 3adel-bassiony** [adonisjs/core#4053]
## Package version
    "@adonisjs/auth": "^8.2.3",
    "@adonisjs/core": "^5.9.0",
    "@adonisjs/i18n": "^1.5.6",
    "@adonisjs/lucid": "^18.3.0",
    "@adonisjs/mail": "^8.1.2",
    "@adonisjs/redis": "^7.3.2",
    "@adonisjs/repl": "^3.1.11",
    "@adonisjs/view": "^6.2.0",

## Node.js and npm version
v19.3.0

## Sample Code (to reproduce the issue)
``` typescript
       const featureSchema = schema.create({
            name_en: schema.string({}, [rules.minLength(4), rules.maxLength(255), rules.trim()]),
            name_ar: schema.string({}, [rules.minLength(4), rules.maxLength(255), rules.trim()]),
            is_active: schema.boolean.optional(),
        })

        const payload = await request.validate({ schema: featureSchema })

        const feature = await Feature.create(payload) // I got an error here

        // const feature = await Feature.create({
        //     nameEn: payload.name_en,
        //     nameAr: payload.name_ar,
        //     isActive: payload.is_active,
        // })
```

I got this error when trying to create a new resource or update it, the same example working with other resources and other controllers but in this resource only I got this error.
I checked the model file and everything is correct even this method is working when sending a request but there is an error in the typescript which prevent the project from building

here is the screenshot for the method and the error:

![Screenshot_2023-01-19_at_11 51 51_AM](https://user-images.githubusercontent.com/81669622/213910089-738b1350-5a1e-4461-9171-14eaff718e10.png)

The method is working when inserting new resource and I'm sure it's correct because I used this way in other controllers, but this one gets the error only in typescript and prevent the project from building
If I replace the payload with an object like this it's working too and the error will disappear, but Why? I used the first way to validate the request payload and pass it to the create function directly without needing to map it on every property! and actually this way is the way written in the documentation.

![Screenshot_2023-01-19_at_11 58 59_AM](https://user-images.githubusercontent.com/81669622/213910160-6e0f0997-f299-413f-86b8-0d3fd7df019f.png)

**Comment by thetutlage** [comment]
I think the error is more than clear. In validator, you have field names in `snake_case` and model needs them in `camelCase`. And please, do not open issues for asking questions. Use the discussions or discord

**Comment by 3adel-bassiony** [comment]
> I think the error is more than clear. In validator, you have field names in `snake_case` and model needs them in `camelCase`. And please, do not open issues for asking questions. Use the discussions or discord

Yes, I understand the error but I tried to use a validator with snake_case and the model in camelCase and it's working!
But sometimes I got this error so I think there is something wrong 🤔

I usually create a validator class in snake case and validate them and pass the payload to the create function and it's working so that's why I opened an issue

**Comment by 3adel-bassiony** [comment]
Btw, If I ignored this error it's working too, and the resource created successfully
