### ISSUE TITLE
User password is not salted

### ISSUE THREAD

**Issue by guoyunhe** [adonisjs/core#4054]
## Package version
5.9.0

## Node.js and npm version
18.13.0, 8.19.3

## Steps to reproduce

1. Just create a new app with auth
2. Register a user with password
3. Login and logout
4. Change APP_KEY
5. Try to login with original password

## Expected result

Second login should fail because APP_KEY(the salt) changed.

## Actual result

Second login succeeded.

## Why we need salt

https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/

**Comment by RomainLanz** [comment]
We are not using the `APP_KEY` to salt passwords. It is a dynamic salt stored inside the hash.

**Comment by thetutlage** [comment]
Lemme add more context to it.

First, the article talks about SHA256, which I think should not be preferred over Argon, Bcrypt or even Scrypt.

Second, we do use a salt, but the salt is random and not same for two passwords

**Comment by guoyunhe** [comment]
Got it. Thanks for explanation!
