### ISSUE TITLE
How do you validate route parameters in validate?

### ISSUE THREAD

**Issue by teletubiii** [adonisjs/core#4058]
i want to validate route parameters with exist rule but the schema create only use the body request, and in the documentation doesnt say nothing about how to do it.

import { schema, rules } from '@ioc:Adonis/Core/Validator'

export const productStockResetSchema = {
  productId: schema.number([rules.exists({ table: 'product', column: 'id' })]),
}

**Comment by RomainLanz** [comment]
Hey @teletubiii! 👋🏻 

I believe it would be easier to use the ORM for that kind of validation.
You can use the `Model.findOrFail(id)`[^1] that will throw when the given record is not found.

In case you still want to validate route parameters, you can use matcher[^2].

[^1]: https://docs.adonisjs.com/reference/orm/base-model#static-findorfail
[^2]: https://docs.adonisjs.com/guides/routing#params-matchers

**Comment by McSneaky** [comment]
Had similar question in [Discord](https://discord.com/channels/423256550564691970/423263894165913601/970781402205397085)
**Question:**
> Is there any cleaner way to validate both, request params and body at same time?
> `post_id` is request param, `body` and `title` are from POST
>    ```ts
>    const validated = await request.validate({
>      schema: schema.create({
>        body: schema.string(),
>        title: schema.string(),
>        post_id: schema.string({}, [
>          rules.uuid(),
>          rules.unique({ table: 'comments', column: 'post_id' }),
>        ]),
>      }),
>      data: {
>        ...params,
>        ...request.body(),
>      },
>    })
>    ```

**Answer:**
> You can do it as follows.
>    ```ts
>    const validated = await request.validate({
>      schema: schema.create({
>        body: schema.string(),
>        title: schema.string(),
>        params: schema.object().members({
>          post_id: schema.string([
>            rules.uuid(),
>            rules.unique({ table: 'comments', column: 'post_id' }),
>          ]),
>        })
>      }),
>    })
>    ```

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
