### ISSUE TITLE
Customise Adonis logger

### ISSUE THREAD

**Issue by assaad97** [adonisjs/core#4059]
hello,

im using adonisjs v5.9.0, and im having a trouble using adonis logger, my question is how can i change some information logged in a log file, for example i have this log ```{"level":30,"time":"2023-02-02T16:42:49.918Z","pid":3672750,"hostname":"a_hostname","name":"authLogger","username":"virk","password":"[PRIVATE]","msg":"user signup"}``` and i would like to know if it is possible to customise keys like hostname and its value, maybe add other keys to generalised.

i know the logger is based on pino, and if what im asking already exists, can you please give a code example of that, since the docuentation is lacking it.

and also is you can add how to redirect logs into a file in dev mode on the docs that would be cool too.

thanks in advance

**Comment by mikesaintsg** [comment]
The default logger Pino config is exposed in the config/app.ts under logger exported const

For config information, you'd have to look into:
https://getpino.io/#/docs/api

If you want to redirect the logs to a file, pino uses streams, so you could redirect the stream to your custom write stream.

>If you're not too familiar with streams, the a flag directs the stream to append, so it won't just overwrite and erase the file contents from the previous logs

Here is a quick example of that:
```js
import * as fs from "fs";
import * as path from "path";

const logstream = fs.createWriteStream(path.join('logger.txt'), { flags: 'a' })

export const logger: LoggerConfig = {
    stream: logstream
}
```

Lastly, instead of trying to change the config of the default logger, you can create a child logger with your own configurations: 

```js
  import Logger from "@ioc:Adonis/Core/Logger";
  const logger = Logger.child({ name: 'child'})
  logger.info('info!')
```

**Comment by mikesaintsg** [comment]
Also, you can register a different Logger in your AppProvider instead to replace the default Logger:

```js
  public register () {
    // Register your own bindings
    const config = this.app.container.resolveBinding('Adonis/Core/Config').get('app.logger', {})
    this.app.container.singleton('Adonis/Core/Logger', () => new Logger({...config, name: 'custom'}))
  }
```

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
