### ISSUE TITLE
Updating entry via query selection does not trigger @beforeUpdate()

### ISSUE THREAD

**Issue by banani0720** [adonisjs/core#4063]
## Package version

Adonis Core 5.8.3
Adonis Lucid 18.0.1
## Node.js and npm version

Node 16.15.1
npm 8.11.0

## Sample Code (to reproduce the issue)

UserService.ts
```ts
public async updatePassword(updateUserPassword: UpdateUserPasswordDTO) {
    return await User.query()
      .where('email', updateUserPassword.email)
      .update('password', updateUserPassword.password )
  }
```

User.ts
```ts
@beforeSave()
  public static async hashPassword(user: User) {
    console.log('user', user)
    if (user.$dirty.password) {
      user.password = await Hash.make(user.password)
    }
  }
```

The expectation I would have here is that on updating the password the `@beforeSave()` block and its associated function would be called and the resulting password would be Hashed. However, when I perform the update like so, the hashing does not occur and further the log statement doesn't get invoked leading me to believe that this function is in fact never called. As a result I am resorting to hashing the password inside the User Service which isn't exactly ideal

**Comment by Melchyore** [comment]
@banani0720  Hey!

Not sure if `Model.query()` executes hooks.

**Comment by RomainLanz** [comment]
Hey @banani0720! 👋🏻 

As stated in the documentation, hooks are not triggered with `Model.update()` method.

![](https://user-images.githubusercontent.com/2793951/217060564-fd6f2821-fc52-45ab-9a05-63e45e34967e.png)

📚  https://docs.adonisjs.com/guides/models/crud-operations#why-not-use-the-update-query-directly

**Comment by banani0720** [comment]
@RomainLanz thanks so much for getting back to me, I must have perused the docs 10 times to look for a  fix I must've missed it completely. Thanks for that info that really helped me to move forward.
