### ISSUE TITLE
URL generation within view : E_CANNOT_FIND_ROUTE

### ISSUE THREAD

**Issue by bencagri** [adonisjs/core#4079]
## Prerequisites

hello, Im facing a problem using `{{ route() }}` helper in view. It doesnt work when route is a group with `domain`;
When I remove domain, it works. But I want this named route should work only under one subdomain.

## Package version
5.9.6

## Node.js and npm version
Node : v14.21.3
Npm: 6.14.18

## Sample Code (to reproduce the issue)
```
Route.group(() => {
  //login & logout
  Route.get('login', 'AuthController.index').as('login')
  Route.post('login', 'AuthController.login').as('login.post')
  Route.get('logout', 'AuthController.logout').as('logout')
}).domain('sub.app.local').as('app')
```

route helper in view doesnt work 
example;  `{{ route('app.login.post') }}`

`E_CANNOT_FIND_ROUTE: Cannot find route for "app.login.post" identified`

I get below when i do `node ace list:routes`
```
GET|HEAD    sub.app.local/login ──────────────────────────────────────────────────────────────────────────────────────────────────── app.login › AuthController.index
POST        sub.app.local/login ──────────────────────────────────────────────────────────────────────────────────────────────── app.login.post › AuthController.login
GET|HEAD    sub.app.local/logout ───────────────────────────────────────────────────────────────────────────────────────────────── app.logout › AuthController.logout

```

**Comment by thetutlage** [comment]
Please read the documentation https://docs.adonisjs.com/reference/views/globals/route

And use issues tracker to report only bugs and use the discussion forum to ask questions
