### ISSUE TITLE
Routing error when there are optional parameters

### ISSUE THREAD

**Issue by equeraltovivas** [adonisjs/core#4094]
When one of parameters of a route is optional, other mandatory parameters seem to behave as optional.

![image](https://user-images.githubusercontent.com/81225508/222473889-f449c322-7d18-4e71-b4d8-aa1a30cf2740.png)

**Comment by thetutlage** [comment]
Not sure what should I looking at to reproduce this error. Please share a proper reproduction code as a repo and not just a screenshot
