### ISSUE TITLE
If we have a new created migration, but do not want to execute, when migration run??

### ISSUE THREAD

**Issue by omnishiv** [adonisjs/core#4120]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [GH discussions](https://github.com/adonisjs/core/discussions), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

**Comment by Julien-R44** [comment]
Just delete your migration? 

Please create an issue respecting the template and explaining your problem more clearly. Here what you want is hardly understandable
