### ISSUE TITLE
Service Provider inside another Service Provider: Invalid module name in augmentation, module '@ioc:Job/Queue' cannot be found.ts(2664) 

### ISSUE THREAD

**Issue by AdSegura** [adonisjs/core#4144]
## Package version
Framework version: 5.9.0
Assembler version: 5.9.5

## Node.js and npm version
Node v18.15.0
Npm 9.5.0

## Sample Code (to reproduce the issue)
![Untitled](https://user-images.githubusercontent.com/11212478/236525570-b6701d17-efa9-4ba3-a5ee-1c0871d7836a.png)

```js
declare module '@ioc:Job/Queue' {
  import JobService from 'services/JobService'

  const JobsController: JobService

  export default JobsController
}
```
Hello.

I created a service provider that uses another service provider as a dependency.

App compiles, but VScode gives me a warning inside `contracts/my-declare-module-file.ts`

`Invalid module name in augmentation, module '@ioc:Job/Queue' cannot be found.ts(2664)
module "@ioc:Job/Queue"`

Provider:

```js
export default class JobProvider {
  public static needsApplication = true
  constructor(protected app: ApplicationContract) {}

  public register() {
    // Register your own bindings
    this.app.container.singleton('Job/Queue', () => {
      const { Queue } = this.app.container.resolveBinding('Setten/Queue')
      return new (require('../services/JobService').default)(Queue)
    })
  }
``` 
This provider is listed inside `adonisrc.json` providers key.

I've tried to import the IOC module directly inside my service provider, it works, but same issue with `invalid module`, tried restarting vscode with same result and tried to use Fresh from Jetbrains, and it gave me the same warning.

**Comment by AdSegura** [comment]
Don't know how, but changing the namespace worked.

**Comment by noukaza** [comment]
same issue i changed the name namespace but doesn’t work for me
