### ISSUE TITLE
When Use domain i give E_CANNOT_FIND_ROUTE

### ISSUE THREAD

**Issue by BluestarCo** [adonisjs/core#4179]
i create route like this
```javascript
Route.get('/posts', ({ view  }) => {
  return view.render('post')
}).domain('api.localhost').as('posts.show')
```

when use it inside template
```html
      <a href="{{ route('posts.show') }}">Show</a>
```

i give this error

**E_CANNOT_FIND_ROUTE: Cannot find route for "posts.show" identifier**

**Comment by Julien-R44** [comment]
https://docs.adonisjs.com/reference/views/globals/route#lookup-within-a-domain
