### ISSUE TITLE
Adonis Encryption and decryption weird behaviour 

### ISSUE THREAD

**Issue by gauravds** [adonisjs/core#4216]
I encrypted the text using custom define key like:
```
static encrypting(value: string | undefined) {
    const algo = Encryption.child({ secret: Env.get('CREDENTIAL_ENCRYPTION_KEY') })
    if (value) {
      return algo.encrypt(value)
    }
  }

  static decrypting(value: string | undefined) {
    const algo = Encryption.child({ secret: Env.get('CREDENTIAL_ENCRYPTION_KEY') })
    if (value) {
      return algo.decrypt(value)
    }
  }
```

Using the local system, I encrypted a few pieces of content into the database and then uploaded them to the production database. 
I used the same `APP_KEY` and `CREDENTIAL_ENCRYPTION_KEY` for encryption at local and production.

The problem is, in production, while decrypting the string it always returns `null`. But If I encrypt some text on production directly and that decrypts, then the text decrypts properly. 

The only difference between local code and production code is the build process. The local system runs in TS and the production app is on JS (Docker container).

Any idea what could be the issue if .env and codebase are the same?

**Comment by thetutlage** [comment]
Are you sure the key is the same? Maybe try logging it at runtime to double check?

**Comment by gauravds** [comment]
@thetutlage Yes, I found the issues. It's related to the environment code. I think here is the code https://github.com/adonisjs/env/blob/master/src/Parser/index.ts#L118-L171. 

If I have some env variable having '$' in between so the Env file actually replaces the '$' until the next special char occurs.  

If I mentioned an env variable within the .env file like => `ENCRYPTION_KEY=z$C&E)H@McQfT`
In local it would be converted as `z&E)H@McQfT` removed `$C`.

In production, environments are loaded by the container using s3(I put my env file into s3 and loaded it into the ECS task definition), not by providing the .env file into the container. In this case, env file is not processing this and took the string as it is. So this is the whole problem. 

What should be the fix for this behavior, BTW what is the purpose to modify the key by `$`?

Should I raise an issue on the https://github.com/adonisjs/env repo for the same?

**Comment by RomainLanz** [comment]
You should escape the `$` sign in your env variable.

https://docs.adonisjs.com/guides/environment-variables#escape-the--sign
