### ISSUE TITLE
"Loved by people across the globe" this section cards are not proper aligned

### ISSUE THREAD

**Issue by piyushgarg1999** [adonisjs/core#4232]
Screenshot => ![alignent of blocks](https://github.com/adonisjs/core/assets/70831837/4b57148a-88f8-4ce7-b297-91f651ad2ec2)

Reproduce
1.open the https://adonisjs.com/
2.scroll down to feedback section
3.cards are not proper alligned

**Comment by McSneaky** [comment]
What browser is that?

Seems to be all good on both Firefox and Chromium (Brave)
![image](https://github.com/adonisjs/core/assets/6796697/2e0bc956-a776-46ba-b35c-202cbfbb4291)

**Comment by piyushgarg1999** [comment]
@McSneaky Nope this isn’t looks good let me show the Screenshot 
![IMG_1018](https://github.com/adonisjs/core/assets/70831837/818e1fdd-63c2-4308-ace7-9ed0690040d2)

**Comment by RomainLanz** [comment]
It is fixed! Thanks!
