### ISSUE TITLE
Enum not work with MySQL ?

### ISSUE THREAD

**Issue by Nico7522** [adonisjs/core#4233]
Hello,

I have a simple enum like that 

`     table.enum('categorie', ['pizza', 'dessert', 'boisson', 'autre']).notNullable()`

And when i send my product to the DB, whatever the categorie i pass, the alway set to "pizza". 

I don't think enum is not supported, i have checked before. 

I can't see what i'm doing wrong.

**Comment by thetutlage** [comment]
Please reference the `enum` type API docs. https://docs.adonisjs.com/reference/database/table-builder#enum--enu

For next time, please provide a complete reproduction of the error, so that we can reproduce it on our end

**Comment by Nico7522** [comment]
It was just mySQL that enabled it. Need to set the strict mode.
