### ISSUE TITLE
How to verify bigint type？

### ISSUE THREAD

**Issue by h25302** [adonisjs/core#4240]
How to verify bigint type？

Similar to
```
schema.create({
    test: schema.number()
  })
```

What can I do to write like this:
```
schema.create({
    test: schema.bigint()
  })
```

My English is not good, I hope you can understand it

**Comment by RomainLanz** [comment]
Hey @h25302! 👋🏻 

Our validator does not support `BigInt` at the moment. What you can do is parse it as a string and manually instantiate a BigInt.

You can also create a [custom rule](https://docs.adonisjs.com/guides/validator/custom-rules#document) in the meantime to validate that your string is a BigInt value.

**Comment by paoloevan** [comment]
i've published a pull request to bigint validation https://github.com/adonisjs/validator/pull/175

**Comment by h25302** [comment]
Thank you very much. I hope to use it soon

**Comment by pragyamishra56** [comment]
@RomainLanz cloud you please assign me this issue it would be my 1st contribution

**Comment by RomainLanz** [comment]
Hey @pragyamishra56! 👋🏻 

The PR was already taken care of https://github.com/adonisjs/validator/pull/176
