### ISSUE TITLE
Geeting Error when using a npm package

### ISSUE THREAD

**Issue by seekex21** [adonisjs/core#4247]
## Prerequisites

I am using a myQ package for my project

https://www.npmjs.com/package/@hjdhjd/myq
`npm install @hjdhjd/myq`

and getting error 

![image](https://github.com/adonisjs/core/assets/100364198/315c33f2-ba9d-4347-a0c4-5038e1cb2f1c)

My code is ..

` import  {myQApi} from "@hjdhjd/myq"`

`const myQ = new myQApi('*****@gmail.com','****@123@')`
  `return await myQ.refreshDevices()`

I google this error and getting a link for solution 

https://stackoverflow.com/questions/71804844/how-would-you-fix-an-err-require-esm-error/71805136#71805136

But when I add  "type": "module" in my package.josn

my project is getting other error 
![image](https://github.com/adonisjs/core/assets/100364198/81ba3461-c371-40d6-93be-9af562f21f8a)

## Package version
`npm install @hjdhjd/myq`
v7.5.0

## Node.js and npm version
v18.17.1

## Sample Code (to reproduce the issue)
` import  {myQApi} from "@hjdhjd/myq"`

`const myQ = new myQApi('*****@gmail.com','****@123@')`
  `return await myQ.refreshDevices()`

**Comment by RomainLanz** [comment]
Hey @seekex21! 👋🏻 

The package `@hjdhjd/myq` has been built to support ESM code base.
AdonisJS 5 is currently running under CJS. Therefore you cannot use `@hjdhjd/myq` (or at least, their latest version).

AdonisJS 6 will run under ESM.

**Comment by seekex21** [comment]
@RomainLanz How I can use AdonisJS 6?
Any luck for me.

**Comment by seekex21** [comment]
Thank you for a quick response  but 6.0.9 not working, we need work with latest version.

**Comment by seekex21** [comment]
I am Using Express with ESM.
