### ISSUE TITLE
Concept of rule chaining like some other validation libraries

### ISSUE THREAD

**Issue by sanwalmehmood** [adonisjs/core#4284]
AdonisJS does not natively support the concept of rule chaining like some other validation libraries.

For Example

<img width="392" alt="image" src="https://github.com/adonisjs/core/assets/28820382/d01d0a58-cf28-4f0a-bf83-5645ae6b8a55">

    `email: schema.string([
            rules.email(),
            rules.maxLength(255),
            rules.trim(),
            rules.escape(),
            rules.ensureVerifiedEmailExistence()
          ]),`

**Comment by Julien-R44** [comment]
Please take a look at https://vinejs.dev/ : that will be the validation library builtin in AdonisJS 6 

See https://github.com/adonisjs/core/discussions/4184 for more details :

> ## New Validation Library
> The current validation module of AdonisJS has served us well, but it desperately needs some improvements. Right now:
> 
> It lacks a union data type. There is no way to validate a field as a string or a number.
> The API to create custom rules is rough. We have witnessed many individuals struggling to create custom rules.
> The state of the package codebase was not great. It made it harder for us to make big changes confidently. A significant rewrite was needed.
> Finally, we developed a framework agnostic validation library called [VineJS](https://vinejs.dev/). VineJS will be the official validation system for AdonisJS v6.
> 
> VineJS is much faster than the version used in V5, and it's also more comprehensive. It makes it easy to create custom rules, schema types and validate complex schemas.
> 
> You can learn more about VineJS in our introduction live stream. [youtube.com/watch?v=YdBt0s8NA4I](https://www.youtube.com/watch?v=YdBt0s8NA4I)
> 
> > Note
> > You can continue to use the existing validation module in your v6 projects. There is no need to migrate immediately to VineJS.
> 
> In fact, you can use VineJS and the existing validation module together in an AdonisJS application. This will allow you to migrate one validator at a time.
