### ISSUE TITLE
How to generate wildcard signed url?

### ISSUE THREAD

**Issue by bolingopez34** [adonisjs/core#4324]
### Discussed in https://github.com/adonisjs/core/discussions/4323

<div type='discussions-op-text'>

<sup>Originally posted by **tsulatsitamim** December 25, 2023</sup>
I got error "E_CANNOT_MAKE_ROUTE_URL: "*" param is required to make URL for "/download/*"</div>

**Comment by RomainLanz** [comment]
Hey! 👋 

Your issue does not follow our guidelines.

1. Make sure you only report bugs or submit feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience, not just you.

If you are not submitting a bug and neither a feature request, then please use the [Github Discussion](https://github.com/adonisjs/core/discussions)


**In any case, issues that are not descriptive enough will be closed. Please respect our time.**
