### ISSUE TITLE
Node ace configure tests [error] "configure" command not found

### ISSUE THREAD

**Issue by xpuliapushi** [adonisjs/core#4336]
i follow the document guid and install 
try everything, yarn , pnpm, npm
and still got this issue

node -v  17.9.1
CUSTOMIZE PROJECT
> Select the project structure · api
> Enter the project name · hello-world
> Setup eslint? (y/N) · true
> Setup prettier? (y/N) · true

RUNNING TASKS
> Scaffold project 44 ms
> Install dependencies 8.89 s
> Configure installed packages 841 ms
  Command failed with exit code 1: node ace configure tests
[ error ]  "configure" command not found

[ error ]  Unable to create project. Cleaning up

i use powershell and as administrator

**Comment by Julien-R44** [comment]
i guess you are using the wrong version of adonisjs/assembler. please rollback to `@adonisjs/assembler@5.9.6` and it should works fine

@adonisjs/assembler 7.x.x is for Adonis 6 which will be available soon
