### ISSUE TITLE
Cannot read tsconfig after installation

### ISSUE THREAD

**Issue by shankiflang** [adonisjs/core#4342]
### Package version

5.8.0

### Describe the bug

Hi,
I've just done a `pnpm create adonis-ts-app backend` and I get an error on all my typescript pages:
`Parsing Error: Cannot read /tsconfig.json`

It looks like it's looking for the tsconfig file at the root of my parent folder when it should be looking for it at "./".

### Reproduction repo

https://github.com/shankiflang/adonis_tsconfig_error

**Comment by shankiflang** [comment]
> Please try adding `"baseUrl": "./"` in your Tsconfig

Same problem :/

Here is my tsconfig file :
```json
{
  "extends": "adonis-preset-ts/tsconfig.json",
  "include": [
    "**/*"
  ],
  "exclude": [
    "node_modules",
    "build"
  ],
  "compilerOptions": {
    "outDir": "build",
    "rootDir": "./",
    "baseUrl": "./",
    "sourceMap": true,
    "paths": {
      "App/*": [
        "./app/*"
      ],
      "Config/*": [
        "./config/*"
      ],
      "Contracts/*": [
        "./contracts/*"
      ],
      "Database/*": [
        "./database/*"
      ]
    },
    "types": [
      "@adonisjs/core",
      "@adonisjs/repl",
      "@japa/preset-adonis/build/adonis-typings",
      "@adonisjs/ally"
    ]
  }
}
```

**Comment by shankiflang** [comment]
> Make sure to reload your editor.

No change

> Also run a tsc --noEmit in your terminal and send the output if issue persists please

Here are the clean installation errors

```bash
✗ npx tsc --noEmit
test.ts:20:21 - error TS2724: '"@japa/runner"' has no exported member named 'processCliArgs'. Did you mean 'processCLIArgs'?

20 import { configure, processCliArgs, run, RunnerHooksHandler } from '@japa/runner'
                       ~~~~~~~~~~~~~~

  ../../node_modules/.pnpm/@japa+runner@3.1.1/node_modules/@japa/runner/build/index.d.ts:20:25
    20 export declare function processCLIArgs(argv: string[]): void;
                               ~~~~~~~~~~~~~~
    'processCLIArgs' is declared here.

test.ts:20:42 - error TS2305: Module '"@japa/runner"' has no exported member 'RunnerHooksHandler'.

20 import { configure, processCliArgs, run, RunnerHooksHandler } from '@japa/runner'
                                            ~~~~~~~~~~~~~~~~~~

test.ts:37:40 - error TS7036: Dynamic import's specifier must be of type 'string', but here has type 'URL'.

37         importer: (filePath) => import(filePath),
                                          ~~~~~~~~

tests/bootstrap.ts:8:15 - error TS2459: Module '"@japa/runner"' declares 'Config' locally, but it is not exported.

8 import type { Config } from '@japa/runner'
                ~~~~~~

  ../../node_modules/.pnpm/@japa+runner@3.1.1/node_modules/@japa/runner/build/index.d.ts:2:15
    2 import type { Config } from './src/types.js';
                    ~~~~~~
    'Config' is declared here.


Found 4 errors in 2 files.

Errors  Files
     3  test.ts:20
     1  tests/bootstrap.ts:8
```

**Comment by Julien-R44** [comment]
Okay this is another error. 

We are currently in the process of releasing Adonis 6 and `create-adonis-ts-app` installs the wrong version of Japa, not compatible with Adonis 5. I'll push a fix

In the meantime, you need to rollback to @japa/runner@2.5.1

**Comment by shankiflang** [comment]
Ok perfect for japa but I still have the typescript "error".

Everything works normally but I get a red line at the top of all my files with the typescript error because it's not looking for the tsconfig where it should. The `tsc --noEmit` command doesn't currently return anything

**Comment by Julien-R44** [comment]
If `tsc --noEmit` doesnt returns anything, then this is an issue with your editor.

If you are using Vscode, i would recommend : F1 > Select Typescript version, and pick `Use workspace version`. Then reload editor one more time.

otherwise, without more information, it will be difficult to help

**Comment by shankiflang** [comment]
Hum that's interesting. When I open the adonis folder directly in vscode, no problem. But here I'm working in monorepo, so it's the parent folder that I open and then I get the error. I should point out that I have a nextjs next to it in typescript which doesn't have the error.
Could this be because adonis uses typescript 4? 

Here is my folder structure :
```
├── apps
│   ├── backend
│   │   └── **/*.ts (adonis)
│   ├── frontend
│   │   └── **/*.ts (nextjs)
│   └── ... (other services)
├── pnpm-workspace.yaml
├── ...
```

**Comment by Julien-R44** [comment]
Not sure if this is the issue. Difficult to say without a reproduction repo

Adonis is compatible with Typescript 5. So i would recommend installing only one typescript version in your root `package.json` ( 5.1.6 for example. I am using this version in a Adonis/Nuxt monorepo and it works just fine ) and retry like that. Otherwise, if possible please, share a reproduction repo so i can take a quick look

**Comment by shankiflang** [comment]
Ok, you I created a test repo : https://github.com/shankiflang/adonis_tsconfig_error 

Here is the error I get :
![image](https://github.com/adonisjs/core/assets/32774804/b97fef7d-16d8-4882-86b2-8b0956d41f53)

**Comment by Julien-R44** [comment]
Okay so this is an Eslint related issue. Please update your Adonis `package.json` as following : 

```jsonc
{
  "eslintConfig": {
    "extends": [
      "plugin:adonis/typescriptApp",
      "prettier"
    ],
    "parserOptions": {
      "project": true // 👈👈👈
    },
    "plugins": [
      "prettier"
    ],
    "rules": {
      "prettier/prettier": [
        "error"
      ]
    }
  },
}
  ```
  
  And it should be good 
  
  You can read more about it here : https://typescript-eslint.io/blog/parser-options-project-true/

**Comment by Julien-R44** [comment]
Feel free to re-open if issue persist

**Comment by shankiflang** [comment]
> Okay so this is an Eslint related issue. Please update your Adonis `package.json` as following :
> 
> ```js
> {
>   "eslintConfig": {
>     "extends": [
>       "plugin:adonis/typescriptApp",
>       "prettier"
>     ],
>     "parserOptions": {
>       "project": true // 👈👈👈
>     },
>     "plugins": [
>       "prettier"
>     ],
>     "rules": {
>       "prettier/prettier": [
>         "error"
>       ]
>     }
>   },
> }
> ```
> 
> And it should be good
> 
> You can read more about it here : https://typescript-eslint.io/blog/parser-options-project-true/

Perfect ! Thanks a lot !
