### ISSUE TITLE
Github CI tests aren't correctly reported

### ISSUE THREAD

**Issue by nicolas-goyon** [adonisjs/core#4349]
### Package version

Adonisjs : 3.0.9

### Describe the bug

Hello, in [this discussion](https://github.com/adonisjs/core/discussions/4338), I detailed my concern regarding the tests that fail but don't appear to be accurately reported to the GitHub Action. The action displays as successful, despite the presence of failing tests. I'm unsure whether the issue lies with me, Adonis, or the module used by Adonis.

### Reproduction repo

https://github.com/HarumiaStar/awi-backend

**Comment by Julien-R44** [comment]
The reproduction repo seem to not be available. Private ?

**Comment by nicolas-goyon** [comment]
oh my bad, i'll create a new repo for this.

**Comment by nicolas-goyon** [comment]
Hi back , here is the new [repo](https://github.com/nicolas-goyon/demoGithubCIAdonis), in this repo you can see that the last github action passed correctly even if the second test failed. You could see in the logs that the tests are printed as failed but the step is considered as successfull.

The repo is clean, nothing on it just added one test from the inital npm init [...]

**Comment by Julien-R44** [comment]
this seems to be related to NodeJS version ( 14 )
i'm not sure why, but at this point, i would just recommend to upgrade to at least Node 18
node 14 has been deprecated since 2 years

**Comment by RomainLanz** [comment]
Node `18` is in maintenance mode. Nowadays, you should at least be on Node `20`.

**Comment by nicolas-goyon** [comment]
Okay it was that, thanks !
