### ISSUE TITLE
ts-node does not seem to be a dev dependency

### ISSUE THREAD

**Issue by jaysson** [adonisjs/core#4361]
### Package version

6.2.2

### Describe the bug

`ace.js` explicitly depends on `ts-node/esm`. However, `ts-node` is listed as a `devDependency`, and not a `dependency`. Thus, `ace` cannot be used without installing the dev packages.

Steps to reproduce:
- Create a new project
- Build it using `npm run build`
- Install the dependencies in the build folder using `npm ci --omit dev` as indicated in the build command result
- Remove the root node_modules
- Run `node ace list` in `build` folder

This is not immediately apparent when build folder is always inside the application root. I encountered it since I was trying Dockerize the application with multi stage builds, where the first stage builds and second stage copies just the built files and runs it.

As a workaround, I am installing all packages in `build`.

**Comment by Julien-R44** [comment]
Yup, thanks, we are aware of this issue and workin on a fix

In the meantime, you can : 

- Install all dependencies
- Or simpler: you can just run `node ace bin/console.js your-command` like `node ace bin/console.js migration:run` for example

**Comment by Julien-R44** [comment]
This has been fixed with this release : https://github.com/adonisjs/assembler/releases/tag/v7.1.1 

Added a quick note in the documentation : https://docs.adonisjs.com/guides/typescript-build-process#creating-production-build
