### ISSUE TITLE
TypeScript being Optional 

### ISSUE THREAD

**Issue by Mehdi-Azmoudeh** [adonisjs/core#4362]
### Package version

6

### Describe the bug

Hi.. Just wanted to know if usage of TypeScript is still optional in v6 or not? Cause I have a massive codebase in v4.1 and want to move it to v6 as fast as possible. TypeScript being mandatory is a big concern right now.

**Comment by RomainLanz** [comment]
Hey @Mehdi-Azmoudeh! 👋🏻 

TypeScript has been mandatory since Adonis 5, which was released 4 years ago.
There are currently no plan to make AdonisJS 6 usable without TypeScript.

**Comment by thetutlage** [comment]
Closing since not actionable
