### ISSUE TITLE
Cannot find module '#exceptions/handler' or its corresponding type declarations

### ISSUE THREAD

**Issue by jonathan-hermans** [adonisjs/core#4434]
### Package version

adonisjs 6.2.2

### Describe the bug

Due to character case issues, Ubuntu needs the "Exceptions" folder to be manually changed to the lowercase "exceptions".

**Comment by jonathan-hermans** [comment]
Also the Handler.js and Handler.js.map need to be renamed.

**Comment by RomainLanz** [comment]
Hey @jonathan-hermans! 👋🏻 

Those files are already lowercase in any new AdonisJS v6 application.
I am not sure what is your issue.
