### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by ashermyers** [adonisjs/core#4481]
### Package version

latest

### Describe the bug

Cannot seem to find the health check implementation in v6. This was present in v5.. Any plans to add this to v6?

**Comment by SwartZCoding** [comment]
> ### Package version
> latest
> 
> ### Describe the bug
> Cannot seem to find the health check implementation in v6. This was present in v5.. Any plans to add this to v6?
> 
> ### Reproduction repo
> _No response_
Hi ! The HealthCheck module will become standalone. It seems to me that it is scheduled to be released soon. But we don't have a specific date.

**Comment by SwartZCoding** [comment]
> ### Package version
> latest
> 
> ### Describe the bug
> Cannot seem to find the health check implementation in v6. This was present in v5.. Any plans to add this to v6?
> 
> ### Reproduction repo
> _No response_

Hi ! The HealthCheck module will become standalone. It seems to me that it is scheduled to be released soon. But we don't have a specific date.

**Comment by ashermyers** [comment]
Ok thanks!
