### ISSUE TITLE
Adonis 6 migration with 'uuid' as primary key

### ISSUE THREAD

**Issue by Steveperi** [adonisjs/core#4483]
### Package version

adonis 6

### Describe the bug

Hello 
I want to create a table with uuid for primary key. My migration code is:
```
import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'xp.groups'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.uuid('id').primary().defaultTo(this.db.rawQuery('uuid_generate_v4()').knexQuery)
      table.string('name', 255).notNullable()
      table.string('suffix', 255).notNullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
```

But when I run migration I have the the following error:
![Screenshot 2024-03-29 at 4 00 53 PM](https://github.com/adonisjs/core/assets/6014414/719caf94-4747-47c5-90e3-72dfcc25f781)
The same code works for adonis 5

Thank you

**Comment by RomainLanz** [comment]
Hey @Steveperi,

This is the code I am using in AdonisJS 6 to use autogenerated UUID in PostgreSQL.

```ts
table.uuid('id').primary().defaultTo(this.db.rawQuery('gen_random_uuid()').knexQuery);
```

**Comment by Steveperi** [comment]
> Hey @Steveperi,
> 
> This is the code I am using in AdonisJS 6 to use autogenerated UUID in PostgreSQL. There's no need to use the old `uuid_generate_v4()` method.
> 
> ```ts
> table.uuid('id').primary().defaultTo(this.db.rawQuery('gen_random_uuid()').knexQuery);
> ```
> 
> Note that the error is about your table name, you used `xp.groups`.

I use postgres and 'xp' is schema where table belong in adonis 5 this works.  
`table.uuid('id').primary().defaultTo(this.db.rawQuery('gen_random_uuid()').knexQuery)`
doesn't work.
When I use this code works fine:
`table.increments('id')`

Thank you

**Comment by Steveperi** [comment]
i solve the problem. I replace code with this: 
```
this.schema.withSchema('xp').createTable(this.tableName, (table) => {
      table.uuid('id').primary().defaultTo(this.db.rawQuery('uuid_generate_v4()').knexQuery)

      table.timestamp('created_at')
      table.timestamp('updated_at')
    })
```
Thank you for your time

**Comment by phenomenal-hardy** [comment]
For anyone reading, remember to setup a migration to create the `uuid-ossp extension` so you can use `uuid_generate_v4()`

```javascript
// database/migrations/{random}_setup_extensions.ts
import { BaseSchema } from '@adonisjs/lucid/schema'

export default class SetupExtensions extends BaseSchema {
  
  async up() {
    this.schema.raw('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
  }

  async down() {
    this.schema.raw('DROP EXTENSION IF EXISTS "uuid-ossp"')
  }
}
```

then you can write your access token table as follow:


```javascript

// database/migrations/{random}_create_access_tokens_table.ts
  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.uuid('id').primary().defaultTo(this.db.rawQuery('uuid_generate_v4()').knexQuery)
      table
        .uuid('tokenable_id')
        .notNullable()
        .references('id')
        .inTable(User.table)
        .onDelete('CASCADE')
// rest of columns ...
}
```

now the error `id is null`  when issuing a token is fixed 

```javascript

const user = await User.verifyCredentials(email, password)
const token = User.accessTokens.create(user, ['*'])

```
