### ISSUE TITLE
Adonis js doesnt look filename with extension, build ERROR

### ISSUE THREAD

**Issue by MrSharpp** [adonisjs/core#4522]
### Package version

6.2.2

### Describe the bug

I am building a API Project with adonis js.
it's working fine in dev enviroment, till i tried to deploy it and got to know that the build files doesn't run.

it doesn't looks for the file with extension instead it looks file_upload, if i rename file_upload.js -> file_upload, it works and then it shows error for the next file. in build folder.

### Reproduction repo
https://github.com/MrSharpp/adonis-bug-rep

**Comment by MrSharpp** [comment]
closing as this is related to auto-swagger

**Comment by EncouragedEntity** [comment]
How did you resolve it?
