### ISSUE TITLE
Hashing

### ISSUE THREAD

**Issue by kevinmelo** [adonisjs/core#4585]
### Package version

6.9.0

### Describe the bug

I have a project running NodeJs + argon2 and i'm studying to migrate my project to adonisjs, but i had a problema in the `hash.verify` from adonisjs.

If i use `hash.verify` from adonis using argon2 it me return false, but if i use the argon2 lib and only call `argon2.verify(hashedValue, plainValue)` it's return true. 

i'm not using any custom configuration in argon2 in both project, only using the default ones, don't know what type os configs adonis use in the drive, but there is a problem. To solve my problem today, i create a custom `CustomHashDriver` that use `argon2` lib direct

**Comment by RomainLanz** [comment]
Hey @kevinmelo! 👋🏻 

We are following the [`PHC` string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md) in AdonisJS hash module. If your hashed were not previously using this format, I would recommend to migrate them by using the `hash.needsReHash ` method when you are doing authentication.

📚 https://docs.adonisjs.com/guides/security/hashing#checking-if-a-password-needs-to-be-rehashed

**Comment by kevinmelo** [comment]
Ok, i will try creating a migration and reHashing every password, thanks

**Comment by kevinmelo** [comment]
@RomainLanz but there is a problem, how can reHashig something that is already hashed? And how i can assure that the password passing via login is the correct password to reHash him, I can't unHash password, and can't accept the any types password to reHash

**Comment by thetutlage** [comment]
When a user logs in, you have access to their raw password. So you verify this raw password using your custom argon driver and then re-hash it with the AdonisJS argon driver.

Also, if you want, you do not even have to do all this re-hashing. Just create a custom argon2 driver and use it in your app. Not everything has to use official drivers, given you have an existing app

**Comment by kevinmelo** [comment]
Yeah... i prefer using the framework default one, but in this case i created a custom hash drive to only use argons2 ate the end... thabks for your time
