### ISSUE TITLE
Feature - Vine and request

### ISSUE THREAD

**Issue by kevinmelo** [adonisjs/core#4589]
### Package version

latest

### Describe the bug

In Adonijs you can validate the request using vine in this way:  `request.validateUsing(validator)`

And in the docs there is a example that you can validate, cookies, header, params and the body ([link](https://docs.adonisjs.com/guides/basics/validation#validating-cookies-headers-and-route-params)). Would be great if you can validate the query string too.

Today i need to validate the querystring in the following way: `await validator.validate(request.qs())`

**Comment by aikrom** [comment]
[Using validators inside controllers
](https://docs.adonisjs.com/guides/basics/validation#using-validators-inside-controllers)

**Comment by kevinmelo** [comment]
> [Using validators inside controllers ](https://docs.adonisjs.com/guides/basics/validation#using-validators-inside-controllers)

i know i can use like that... as a mention and put the same link. But in adonis you can create a single validation that validate all the request (excluding the query string)

**Comment by aikrom** [comment]
So, we need to do a little research to understand why it's possible to check headers, cookies, and parameters, but not query strings.

We need to look at [this](https://github.com/adonisjs/core/blob/c48e72b1bc5287c5add43a6dc13cd91ccf37af03/modules/http/request_validator.ts#L55) first to understand how `request.validateUsing(...)` works. Then we find [this](https://github.com/adonisjs/core/blob/c48e72b1bc5287c5add43a6dc13cd91ccf37af03/modules/http/request_validator.ts#L81) part:

```ts
/**
 * Data to validate
 */
const data = validatorOptions.data || {
  ...this.#ctx.request.all(),
  ...this.#ctx.request.allFiles(),
  params: this.#ctx.request.params(),
  headers: this.#ctx.request.headers(),
  cookies: this.#ctx.request.cookiesList(),
}
```
And to further understand what `request.all()` does, we need to open [this](https://github.com/adonisjs/http-server/blob/06a28eed841ec64263249a8373cca017f7e6720d/src/request.ts#L237) method and find out:

```ts
all(): Record<string, any> {
   return this.#requestData
}
```
And then we need to look around and find where ([1](https://github.com/adonisjs/http-server/blob/06a28eed841ec64263249a8373cca017f7e6720d/src/request.ts#L190), [2](https://github.com/adonisjs/http-server/blob/06a28eed841ec64263249a8373cca017f7e6720d/src/request.ts#L207)) the value for `#requestData` was set. For example:

```ts
updateBody(body: Record<string, any>) {
  this.#requestBody = body
  this.#requestData = { ...this.#requestBody, ...this.#requestQs }
}
```

And now we understand that when we use `request.validateUsing(...)` we can validate all the request data. Great! 

P.S. If we don't like this approach, we can override `request.validateUsing(...)` to make it work the way we want.

**Comment by thetutlage** [comment]
Code digging is a good exercise. But we have this mentioned in the docs too :)

<img width="911" alt="Screenshot 2024-05-30 at 1 58 44 PM" src="https://github.com/adonisjs/core/assets/1706381/0770f711-d535-413f-9e7b-d52a9c62833b">

**Comment by kevinmelo** [comment]
Hmm, then body and query string are the same thing for adonis, don't matter where they come from. Thanks.

At the end is better to override the class and make the query string separated.
