### ISSUE TITLE
Broken Installation of the Slim Starter Kit.

### ISSUE THREAD

**Issue by gurvirsinghbaraich** [adonisjs/core#4601]
### Package version

latest

## Steps to reproduce.
1. npm init adonisjs@latest <appname> -- --db=mysql
2. Choose the starter kit.
3. Decline installation using npm.

## Error Overview
From the documentation provided I did copy the command (`npm init adonisjs@latest todoapp -- --db=mysql`) and ran it to install the slim starter kit.

During the installation process the command line asks a question to install dependencies using `npm`, to which I declined. Now it installs the project without dependencies. I did install dependancies using `bun` and when I ran the project I got an error messaging saying – "SyntaxError: The requested module 'node:module' does not provide an export named 'register'" (file: ace.js).

**Comment by gurvirsinghbaraich** [comment]
> A screenshot showing the error message (might be helpful)

![Screenshot 2024-06-03 at 10 43 11 AM](https://github.com/adonisjs/core/assets/161711856/21e3ff15-2dfb-4bbd-9ef7-7672810b6bac)

**Comment by thetutlage** [comment]
AdonisJS is a Node.js framework and not Bun framework and hence `bun dev` cannot be used to start the development server.

**Comment by gurvirsinghbaraich** [comment]
@thetutlage 
Bro Bro, I already knew you answer please run it using npm dev the output is same (I should have mentioned it yesterday). I am using node v18.17.0

Come on mac, how can you mark the issue invalid and completed without taking a look.

**Comment by gurvirsinghbaraich** [comment]
Though, I did actually fix the error and this works with bun as well. The problem was I was using node v18.17.0 as mentioned, switching to a newer version solved the bug in your code.

**Comment by thetutlage** [comment]
- Your screenshot shows `bun dev`. So it is safe for me to assume you are using Bun.
- The documentation states we need `Node >= 20.6`.


We get many issues reported throughout the day where there is some misconfiguration on the developer's end (as in your case too). So it is practically impossible to reproduce all these issues ourselves.

**Comment by gurvirsinghbaraich** [comment]
@thetutlage Sorry man, I might have accidentally skipped the node version requirement. Really sorry for wasting your time.
