### ISSUE TITLE
Install version 5 of Adonis in node 18 e 20

### ISSUE THREAD

**Issue by EwertonDutra** [adonisjs/core#4611]
### Package version

10.7.0

### Describe the bug

**Only run the code of install version 5 adonisjs** 

![bug ao instaalar adonis na versao 18 node](https://github.com/adonisjs/core/assets/13201575/dcfea67f-2548-4719-8c36-a3a37a37ff07)
Version 18 node ❌

![bug ao instalar na versao 20-14-0](https://github.com/adonisjs/core/assets/13201575/557e5e0b-6b3e-4821-a378-fcb74789d812)
Version 20 node ❌

In version 14 of node work 👍

**Logs in attachment**
[2024-06-12T13_46_08_826Z-debug-0.log](https://github.com/user-attachments/files/15806363/2024-06-12T13_46_08_826Z-debug-0.log)
[2024-06-12T13_48_57_439Z-debug-0.log](https://github.com/user-attachments/files/15806364/2024-06-12T13_48_57_439Z-debug-0.log)

I am using windows 11 and run code in Terminal windows (not cmd)

### Reproduction repo

project is not created

**Comment by thetutlage** [comment]
Please use the forum to get help for the previous version. The issue tracker is to tracks bugs related to the current version.
